Merge recent changes from dev to master
mileweb/docs-content-cdn pull request #107
Opened 2020-10-24 08:43 UTC by nibinqtl

Let's do this bi-weekly.

2020-10-25 00:26 UTC, burtonquantil requested changes
Marc and I both need to fix links to the origin_fast_route directive.
aws-bucket.md needs a lot of work.

2020-10-25 00:26 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +Deploy a Property to Staging.
Is this supposed to formatted differently as the title of a section?

Suggestion:  Deploy the property to staging.

2020-10-25 00:26 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +Suppose no issues occurred during the “Validate & Save” - congratulations. Now we can deploy property and test our Staging deployment.
Suggestion:  If the property was saved and validated without any issue, we can now deploy the property and test our staging deployment.

2020-10-25 00:26 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +To test staging deployments, we should know the staging servers IP addresses:
"we should get the staging servers' IP addresses"

2020-10-25 00:26 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +Now, let's pick one of those addresses returned above and check if everything we have setup and deployed previously works.
Suggestion: Replace with "Now, let's pick one of those addresses and check if everything we have previously set up and deployed  works."

2020-10-25 00:26 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +By requesting the same item again, we will see that now cache status is **HIT**
Suggestion:  "By requesting the same item again, we will see the cache status change to **HIT**

2020-10-25 00:26 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +Everything works as expected, so let's deploy everything to production.
remove the second "everything"

2020-10-25 00:26 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +To deploy the configuration to production, we should do it both in **"Certificates"** and **"Edge Configurations"**. Navigate to **"Certificates"** first, select certificate, set *Deployment destinat
I suggest changing the first sentence to:  "To deploy the configuration to production, we must deploy both the certificate and the property.  Navigate to **"Certificates"** first. Select the certificate.   In the *Deployment Destination" field, choose "Production", and click **"Deploy Configuration"**.

@marcfishelquantil

2020-10-25 00:26 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +Before we can try it in production, we should Create/Change the CNAME record of your DNS and point it to the *Edge Hostname* we have created in the beginning(`files-waytoo-digital.qtlcdn.com`)
Suggestion: Before we can try it in production, we must modify our DNS by creating or changing the CNAME record for files.waytoo.digital to point it to the edge hostname we created earlier, `files-waytoo-digital.qtlcdn.com`.

2020-10-25 00:26 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +Actually, you also can do use the production IP address to check if everything is ok before you will change the DNS record. Just like that:
Suggestion:  You can also use the cURL utility to check that everything is OK before modifying your DNS server:

2020-10-25 00:26 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +Congratulations. You've just accelerated Amazon S3 Bucket with **CDN360**
Congratulations! You've just accelerated an Amazon S3 bucket with **CDN360**.

2020-10-25 00:26 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +Now, let's block the public access to our bucket and setup a CDN360 to access it.
Now, let's block public access to our bucket and set up CDN360 to access it.

2020-10-25 00:26 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +Previously we have made our bucket public. Now, in bucket settings, we should set the default permissions back to make the bucket private again.
Suggestion:  "Previously, we made our bucket public.  Now in AWS' bucket settings, we should set the default permission back to make the bucket private again."

2020-10-25 00:26 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +Now we can edit our property settings and setup the `Origin Authentication for S3`. Before doing that, make sure you know: *1) AWS Bucket region*, *2) AWS Acces Key*, *3) AWS Access Secret*.
Change "setup" to "set up".
Change "Acces" to "Access".

(Is it obvious to the user how they get those three pieces of information?)

2020-10-25 00:26 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +All right. Now go to **"Edge Configurations** then choose the property we configured before.
Change to:  Alright, now go to **Edge Configurations** and choose the property we configured before.

2020-10-25 00:26 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +Click *"Clone"* to create a new configuration version. Now we can edit it. Click on *"Edit"* and then in *"Advanced Settings"* set the Authentication Method to *"AWS S3"* and fill the required fields
Change "fill the required" to "fill in the required"

2020-10-26 01:13 UTC, snikitin-qtl commented
There the PR to address AWS page's language issues -> https://github.com/mileweb/docs-content-cdn/pull/109

2020-11-04 17:28 UTC, burtonquantil approved these changes
OK to merge

2020-11-07 10:49 UTC, merged