Updates for AWS tutorial made by Marc
mileweb/docs-content-cdn pull request #109
Opened 2020-10-26 01:11 UTC by snikitin-qtl

2020-10-26 01:12 UTC, snikitin-qtl commented
@burtonquantil please check this out. We will merge it to dev and update the PR for emerging dev to master. Thanks.

2020-10-26 01:48 UTC, nibinqtl approved these changes
LGTM

2020-10-26 20:55 UTC, burtonquantil requested changes
Thanks for the revisions, Marc. Please check my additional comments.

2020-10-26 20:55 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +1. In the Traffic Management page, create an Edge Hostname.
@marcfishelquantil  Shouldn't "Edge Hostname" be lowercased?

2020-10-26 20:55 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +2. After creating the Edge Hostname, access it in terminal to make sure it works:
Shouldn't "Edge Hostname"  be lowercased since it's not a label, title, or product name.

2020-10-26 20:55 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +Now let's generate a certificate and sign it automatically with Let’s Encrypt.
@marcfishelquantil  @nibinqtl 
Why do we still say "sign it automatically"?  Shouldn't we say "renew it automatically"?    Our form says "Auto Renew".

2020-10-26 20:55 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +Deploy a Certificate to the Staging Environment
Can you double check the rendering of "Deploy a Certificate to the Staging Environment "?
On my screen, the rendering of this aws-bucket.md looks off.
![image](https://user-images.githubusercontent.com/16617920/97226132-ce5f1780-1790-11eb-9f0d-0d93d2b3be59.png)

2020-10-26 20:55 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +2. Complete the **Property Name**, an optional **Description** for the property, and a **Description** of the configuration version.
@marcfishelquantil  I think "Enter" or "Add" is better than "Complete". For example, you refer to entering a hostname in the Hostnames field below.    However, this is minor.

2020-10-26 20:55 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +We have created an origin. Next we will create an initial edge-logic configuration.
@marcfishelquantil  Why are we referring to the hyphenated "edge-logic"  rather than "edge logic"?
As far as I know, we haven't done that before  in our portal or the portal help https://docs.cdnetworks.com/cdn/docs/portal/edge-configurations/creating-property

2020-10-26 20:55 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +11. Click **"OK"**. The system generates the following edge-logic script:
@marcfishelquantil  Again, why "edge-logic" ?

2020-10-26 20:55 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +13. Click **Validate and Save** to make sure that everything is configured properly.
@marcfishelquantil  Did you miss my comment in Bin's pull request?
Why do we say "Validate and Save" when the button in our portal is "Save and Validate"?
![image](https://user-images.githubusercontent.com/16617920/97227090-35310080-1792-11eb-989d-216c9c102098.png)

2020-10-26 20:55 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +Assuming that no issues occurred after validating and saving, you can now deploy the property to the staging environment for testing.
@marcfishelquantil   Since our button says "Save & Validate",  why switch to "validating and saving"?

2020-10-26 20:55 UTC, burtonquantil commented on docs/recipes/aws-bucket.md
> +Before we release the property to production, we should create or change the CNAME record of our DNS and point it to the Edge Hostname we created earlier (`files-waytoo-digital.qtlcdn.com`).
@marcfishelquantil  does "Edge Hostname" really need to be capitalized?

2020-10-29 22:48 UTC, marcfishelquantil commented on docs/recipes/aws-bucket.md
> +1. In the Traffic Management page, create an Edge Hostname.
@burtonquantil Agreed, in this context, "edge hostname" should be lowercase.

2020-10-29 22:48 UTC, marcfishelquantil commented on docs/recipes/aws-bucket.md
> +2. After creating the Edge Hostname, access it in terminal to make sure it works:
@burtonquantil Same comment as above: "edge hostname" should be lowercase.

2020-11-03 06:29 UTC, snikitin-qtl commented on docs/recipes/aws-bucket.md
> +1. In the Traffic Management page, create an Edge Hostname.
Addressed in PR update

2020-11-03 06:29 UTC, snikitin-qtl commented on docs/recipes/aws-bucket.md
> +2. After creating the Edge Hostname, access it in terminal to make sure it works:
Addressed in PR update

2020-11-03 06:29 UTC, snikitin-qtl commented on docs/recipes/aws-bucket.md
> +Now let's generate a certificate and sign it automatically with Let’s Encrypt.
Addressed in PR update

2020-11-03 06:29 UTC, snikitin-qtl commented on docs/recipes/aws-bucket.md
> +Deploy a Certificate to the Staging Environment
Addressed in PR update

2020-11-03 06:29 UTC, snikitin-qtl commented on docs/recipes/aws-bucket.md
> +2. Complete the **Property Name**, an optional **Description** for the property, and a **Description** of the configuration version.
Addressed in PR update

2020-11-03 06:29 UTC, snikitin-qtl commented on docs/recipes/aws-bucket.md
> +11. Click **"OK"**. The system generates the following edge-logic script:
Addressed in PR update

2020-11-03 06:29 UTC, snikitin-qtl commented on docs/recipes/aws-bucket.md
> +13. Click **Validate and Save** to make sure that everything is configured properly.
Addressed in PR update

2020-11-03 06:29 UTC, snikitin-qtl commented on docs/recipes/aws-bucket.md
> +Assuming that no issues occurred after validating and saving, you can now deploy the property to the staging environment for testing.
Addressed in PR update

2020-11-03 06:29 UTC, snikitin-qtl commented on docs/recipes/aws-bucket.md
> +Before we release the property to production, we should create or change the CNAME record of our DNS and point it to the Edge Hostname we created earlier (`files-waytoo-digital.qtlcdn.com`).
Addressed in PR update

2020-11-03 15:43 UTC, burtonquantil approved these changes
This looks OK to merge.
If there's anything else, we can get it fixed later @marcfishelquantil

2020-11-03 15:44 UTC, merged