NCAS-2374 #comment merged changes for sprint 92 that have already bee…
mileweb/docs-content-cdn pull request #111
Opened 2020-10-28 17:19 UTC by burtonquantil

…n reviewed by our QA team

2020-11-03 22:23 UTC, nibinqtl requested changes

2020-11-03 22:23 UTC, nibinqtl commented on apispec/openapi.json
> +      "description": "A property is the configuration of one or more hostnames (domains) that need to be <a href=\"#tag/Deployment-Management\">deployed</a> to the CDN360 servers. A property can have
For the image src, can we remove "https://docs.cdnetworks.com" and start from the URI?

2020-11-03 22:23 UTC, nibinqtl commented on apispec/openapi.json
> +                          "description": "Refer to https://docs.cdnetworks.com/cdn/docs/edge-logic/intro"
Can we remove "https://docs.cdnetworks.com" and start from the URI?

2020-11-03 22:23 UTC, nibinqtl commented on apispec/openapi.json
> +                          "description": "If you plan to allow CDNetworks to renew your TLS certificate through Let's Encrypt, set this to <i>false</i>. \n If you plan to handle certificate renewal y
Please update the description based on https://docs.google.com/document/d/19e8APetleIp-8hc3Hy1qYhrThsWqN803VZYswzjX1lg/edit

2020-11-03 23:22 UTC, burtonquantil commented on apispec/openapi.json
> +      "description": "A property is the configuration of one or more hostnames (domains) that need to be <a href=\"#tag/Deployment-Management\">deployed</a> to the CDN360 servers. A property can have
Yes, I believe this will work because it is part of an img tag.  I will fix this.

2020-11-04 00:35 UTC, burtonquantil commented
I made your requested changes in a new pull request because I had trouble figuring out how to resolve some GitHub conflict.

2020-11-04 00:35 UTC, closed without merging