Recent changes to be released
mileweb/docs-content-cdn pull request #119
Opened 2020-11-11 07:28 UTC by nibinqtl

2020-11-12 20:09 UTC, burtonquantil requested changes
Only a few minor suggested improvements.

2020-11-12 20:09 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +CDN360 has gzip always on, and applies it to the default MIME types above. In addition, compression is only activated when the response body size is greater than 1000 bytes. The default behavior shou
Remove the parentheses around  "up to 20".

2020-11-12 20:09 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +Please notice that when used together, `&&` has higher precedence than `||` and using parenthesis to group sub-conditions is not supported.
I think "parenthesis" should be "parentheses".  @marcfishelquantil

2020-11-12 20:09 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +*  Support of integer value comparison with `<`, `<=`, `>`, `>=`. The user has to make sure both operands are valid integers, otherwise the result will be `false`. A valid integer can be either decim
In most of this document, you refer to "you" whereas here you switch to the third person with "The user".
It ought to be consistent.
I recommend:
"Make sure both operands are valid integers. Otherwise, the result will be `false`."

2020-11-12 20:09 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +Sets caching time for different response codes. We enhanced the open-source version to support setting `time` with a variable. The specified time is only applied to responses without caching instruct
@marcfishelquantil   "only applied to"  or "applied only to"?

2020-11-12 20:09 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +Real-Time Log is a powerful feature of CDN360 that when enabled, sends a log entry for each request in real-time to an ingestion server of your choosing. The format of the log entry is highly configu
Modify " To avoid overwhelming the ingestion server, the user can set a sample rate "  to 
"To avoid overwhelming the ingestion server, set a sample rate"

2020-11-12 21:10 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +2. The new parameter ```if(condition)``` has been introduced to allow adding the header based on some condition. If the condition is true, the ```add_header``` directive adds the header and the value
@nibinqtl @burtonquantil I agree with Burton. No other comments.

2020-11-12 21:16 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +CDN360 has gzip always on, and applies it to the default MIME types above. In addition, compression is only activated when the response body size is greater than 1000 bytes. The default behavior shou
@nibinqtl @burtonquantil Please change "...compression is only activated when the..." to "...compression is activated only when the..."
Please delete "vast."
Please change "We are working on supporting wildcards like `text/*` and `*javascript` with an ETA of Nov. 2020." to "Support for wildcards such as `text/*` and `*javascript` will be provided in November 2020." Caveat: I would advise not specifying a date in case the date slips. In this case, we could say the following: "Support for wildcards such as `text/*` and `*javascript` will be provided in the future."

2020-11-12 21:16 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +Please notice that when used together, `&&` has higher precedence than `||` and using parenthesis to group sub-conditions is not supported.
@nibinqtl @burtonquantil Correct. Please use "parentheses" instead of "parenthesis."

2020-11-12 21:24 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +*  Support of integer value comparison with `<`, `<=`, `>`, `>=`. The user has to make sure both operands are valid integers, otherwise the result will be `false`. A valid integer can be either decim
@nibinqtl @burtonquantil I agree with Burton. Or simply remove "The user has to" and start the sentence with "Make sure both operands..." 
Please add a semicolon after "..valid integers" and add a comma after "otherwise" as follows: "...valid integers; otherwise. the result..."
Please change "hexidecimal" to "hexadecimal."
The comma after "decimal" is not necessary. I believe you added it to show that the leading 0x belongs to hexadecimal and not decimal. One way around this is the following: "A valid integer can be either a decimal value or hexadecimal value that has a leading '0x'."

2020-11-12 21:34 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +Sets caching time for different response codes. We enhanced the open-source version to support setting `time` with a variable. The specified time is only applied to responses without caching instruct
@nibinqtl @burtonquantil Please use "applied only."
Another suggestion. Instead of "A value of 0 makes those contents not cached. If you can identify dynamic/non-cacheable contents based on request, you should use `proxy_cache_bypass` and `proxy_no_cache` to bypass caching." how about the following: "A value of 0 makes the contents not cached. If you can identify dynamic/non-cacheable contents based on request, use `proxy_cache_bypass` and `proxy_no_cache` to bypass caching."

2020-11-12 21:36 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +Real-Time Log is a powerful feature of CDN360 that when enabled, sends a log entry for each request in real-time to an ingestion server of your choosing. The format of the log entry is highly configu
@nibinqtl @burtonquantil Consider changing "of your choosing" to "of your choice." 
Consider changing the preposition "in" to "of" as follows: "The parameter value can be an integer of [0,65536]."

2020-11-14 08:21 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +2. The new parameter ```if(condition)``` has been introduced to allow adding the header based on some condition. If the condition is true, the ```add_header``` directive adds the header and the value
updated

2020-11-14 08:21 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +CDN360 has gzip always on, and applies it to the default MIME types above. In addition, compression is only activated when the response body size is greater than 1000 bytes. The default behavior shou
updated

2020-11-14 08:21 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +Please notice that when used together, `&&` has higher precedence than `||` and using parenthesis to group sub-conditions is not supported.
updated

2020-11-14 08:21 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +*  Support of integer value comparison with `<`, `<=`, `>`, `>=`. The user has to make sure both operands are valid integers, otherwise the result will be `false`. A valid integer can be either decim
updated

2020-11-14 08:21 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +Sets caching time for different response codes. We enhanced the open-source version to support setting `time` with a variable. The specified time is only applied to responses without caching instruct
updated

2020-11-14 08:22 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +Real-Time Log is a powerful feature of CDN360 that when enabled, sends a log entry for each request in real-time to an ingestion server of your choosing. The format of the log entry is highly configu
This directive has been removed, due to NCAS-2434

2020-11-16 20:04 UTC, burtonquantil approved these changes
OK to merge.

2020-11-17 00:59 UTC, merged