document change for Release27Nov2020
mileweb/docs-content-cdn pull request #123
Opened 2020-11-22 09:12 UTC by nibinqtl

2020-11-24 18:54 UTC, burtonquantil commented on docs/edge-logic/faq.md
> +Use the directive [`enable_websocket`](</docs/edge-logic/supported-directives.md#enable_websocket>) in the location where websocket is needed. Make sure the client uses HTTP/1.1 (not HTTP/2) to conne
I suggest using "changed using" instead of "changed by".

2020-11-24 18:55 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +This directive enables proxying the WebSocket protocol. The client must make sure not to use HTTP/2. The default read and send timeouts are set to 21s and can be changed by the `origin_read_timeout`
I believe "changed using" is better than "changed by". @marcfishelquantil

2020-11-24 18:57 UTC, burtonquantil requested changes
I made a couple of minor suggestions.

2020-11-24 18:57 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +* When slicing is enabled, the server automatically removes the `Accept-Encoding` header in the request to origin to disable compression. If this behavior is overridden, for example, by the `origin_s
I think the last sentence should end with "a corrupted response."

2020-11-25 09:12 UTC, nibinqtl commented on docs/edge-logic/faq.md
> +Use the directive [`enable_websocket`](</docs/edge-logic/supported-directives.md#enable_websocket>) in the location where websocket is needed. Make sure the client uses HTTP/1.1 (not HTTP/2) to conne
updated.

2020-11-25 09:12 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +This directive enables proxying the WebSocket protocol. The client must make sure not to use HTTP/2. The default read and send timeouts are set to 21s and can be changed by the `origin_read_timeout`
updated.

2020-11-25 09:12 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +* When slicing is enabled, the server automatically removes the `Accept-Encoding` header in the request to origin to disable compression. If this behavior is overridden, for example, by the `origin_s
updated.

2020-11-25 18:22 UTC, burtonquantil approved these changes
OK to merge.

2020-12-04 22:03 UTC, burtonquantil submitted a review, later dismissed
OK to merge

2020-12-10 20:39 UTC, nibinqtl commented
@burtonquantil @marcfishelquantil Release27Nov2020 has already been deployed. Can we push this PR to production?
Please approve it if you don't see any blocking issue.

2020-12-10 21:17 UTC, burtonquantil approved these changes
OK to merge. I keep approving but then there seem to be additional updates to dev which were reviewed and separately approved which cause the old review to become 'stale'.

2020-12-10 22:19 UTC, merged