Burton ncas2441
mileweb/docs-content-cdn pull request #125
Opened 2020-11-24 18:51 UTC by burtonquantil

2020-11-25 09:23 UTC, nibinqtl requested changes

2020-11-25 09:23 UTC, nibinqtl commented on apispec/openapi.json
> +                          "description": "This setting controls how the URI of the incoming request is incorporated into the cache key. The default setting, \"preRewrite\", puts the URI into the cach
This setting makes a difference only when there is "rewrite" directive in the edge logic. It is more accurate to say: "When \"rewrite\" directive is used in the edge logic to modify the request URI, this settings controls whether the value before or after the modification is incorporated into the cache key. The default setting, \"preRewrite\", puts the URI before modification into the cache key. If the \"rewrite\" directive converts multiple different URIs into the same value, you may wish to use the setting \"postRewrite\" to achieve a higher cache hit ratio."

2020-12-01 22:39 UTC, burtonquantil commented on apispec/openapi.json
> +                          "description": "This setting controls how the URI of the incoming request is incorporated into the cache key. The default setting, \"preRewrite\", puts the URI into the cach
@nibinqtl  I just generated the openapi.json with the changes you approved in the other pull request. Thanks.

2020-12-03 23:05 UTC, nibinqtl approved these changes
Looks good now.

2020-12-04 21:46 UTC, merged