Help edits for Sprint 95
mileweb/docs-content-cdn pull request #129
Opened 2020-12-08 22:31 UTC by marcfishelquantil

These edits cover the changes in Sprint 95.

2020-12-08 23:21 UTC, burtonquantil requested changes
Marc, please check my comments.

2020-12-08 23:21 UTC, burtonquantil commented on docs/portal/managing-standby-tasks.md
> +# Managing Standby Tasks
The use of "tasks" isn't quite consistent with our portal.  The user can have a standby task for staging and one for production at the same time. The user can add one or more deployment and undeployment actions to each task. There isn't technically a standby task for each certificate and property undeployment and deployment as implied by your phrasing.  The portal's interface represents what is supported by our API.  https://docs.cdnetworks.com/cdn/apidocs#operation/createDeployment (The call can specify multiple actions to do in one deployment task.)

2020-12-08 23:49 UTC, marcfishelquantil commented on docs/portal/certificates/updating-certificates.md
> +7. To deploy the certificate now, click <strong>Deploy Now</strong>. To deploy it at a later time, click <strong>Add to Standby task</strong> to add this task to the [standby queue](</docs/portal/man
Yes, it needed to be updated. I fixed this, but the reason I did not do so initially was that I believe we no longer use this figure in the help. Now I realize that if we no longer use a figure, I will simply delete it. Again, thank you.

2020-12-08 23:49 UTC, marcfishelquantil commented on docs/portal/managing-standby-tasks.md
> +# Managing Standby Tasks
Got it, thank you. Please see updated wording in my next upload.

2020-12-09 00:06 UTC, burtonquantil approved these changes
I was debating internally whether using "subqueue" is good. There are technically two different deployment tasks that can be created, one for production and one for staging.

2020-12-09 00:10 UTC, merged