Change for Release25Dec2020
mileweb/docs-content-cdn pull request #133
Opened 2020-12-25 12:20 UTC by nibinqtl

2020-12-25 12:22 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +### `clent_body_timeout`
@yongguangbai , please review the accuracy of the description of these 3 directives.

2020-12-29 11:44 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +### `proxy_set`
@yongguangbai @laharikommi1 , please review the accuracy of this part of the document.

2020-12-29 18:07 UTC, burtonquantil requested changes
Fix names of several directives.

2020-12-29 18:07 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +**Syntax**: `clent_body_timeout time;`<br/>
shouldn't this be **client_body_timeout** instead of _clent_body_timeout_ ? It should have been reviewed before getting onto docdev.quantil.com?

2020-12-29 18:07 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +**Syntax**: `clent_header_timeout time;`<br/>
**client**_header_timeout instead of clent_header_timeout?

2020-12-29 18:07 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +### `clent_send_timeout`
**clien**t_send_timeout insead of clent_send_timeout

2020-12-29 18:38 UTC, yongguangbai commented on docs/edge-logic/supported-directives.md
> +This directive assigns the `value` to the `$variable`, similar to the [`set`](#set) directive. The difference is that `proxy_set` is executed after the response header is received from the origin (in
1. "set" directive doesn't support if parameter;
2. "value" can be text, variables or their combination;
3. When upstream variable is used in value, this directive only works on the response headers after proxy_add_upstream_header modified them.

2020-12-29 18:41 UTC, yongguangbai commented on docs/edge-logic/supported-directives.md
> +**Syntax**: `clent_send_timeout time;`<br/>
it should be "client_send_timeout".

2020-12-30 01:11 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +The directive is merged across different levels (http/server/location/location if). If the same variable is assigned in different levels, the assignment in the innermost level takes effect.
@yongguangbai @laharikommi1 , please confirm this part.

2020-12-30 01:12 UTC, nibinqtl commented
Just updated the document to address the comments. Please review again. @burtonquantil @yongguangbai

2020-12-30 22:49 UTC, burtonquantil requested changes
Added a few small suggestions

2020-12-30 22:49 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +# if origin responds a "cachetime" header, use it to override the default
The English here is not quite right.  Do you mean 'if origin responds **with** a "cachetime" header... '   ?

2020-12-30 22:49 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +This directive assigns the `value` to the `$variable`. The `value` can be another variable or a composition of variables and literals. While looking very similar to the [`set`](#set) directive, the b
Suggestion 1: 
"While this directive looks very similar to the [`set`](#set) directive, it differs in when it is executed."

Suggestion 2:
Add a comma after "Therefore".

Suggestion 3:
Replace "after modified" with "after being modified" or "after modification" 

@marcfishelquantil  check this too.

2020-12-31 02:22 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +This directive assigns the `value` to the `$variable`. The `value` can be another variable or a composition of variables and literals. While looking very similar to the [`set`](#set) directive, the b
thanks. suggestions accepted..

2020-12-31 02:22 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +# if origin responds a "cachetime" header, use it to override the default
fixed.

2020-12-31 02:53 UTC, burtonquantil submitted a review, later dismissed
OK to me.

2020-12-31 06:27 UTC, yongguangbai commented on docs/edge-logic/supported-directives.md
> +The directive is merged across different levels (http/server/location/location if). If the same variable is assigned in different levels, the assignment in the innermost level takes effect.
It is correct.

2020-12-31 09:06 UTC, nibinqtl commented
Let's wait for @marcfishelquantil to fix https://github.com/mileweb/docs-content-cdn/pull/135

2020-12-31 20:08 UTC, nibinqtl commented
@burtonquantil @marcfishelquantil , please review again and approve this PR if it is OK to release to public. Thanks!

2020-12-31 23:45 UTC, burtonquantil approved these changes
OK to merge.
There are a couple of minor things that we can fix next week.

2020-12-31 23:45 UTC, burtonquantil commented on docs/portal/reports.md
> +| CPU Time| Reports the CPU time consumed in each time interval to serve your properties. You can toggle the unit between **seconds** and **number of cores**. For example, if 3000 seconds of CPU time
There is an extraneous period after the first sentence, but it's not a blocker.

2020-12-31 23:45 UTC, burtonquantil commented on docs/portal/tasks/validations.md
> +**Note:** You can also use the **Search** box at the top to filter the results. Filtering is not case-sensitive.
I've commented to Marc about the difference between Release25Dec2020 and Release08Jan2021 which is getting mixed up here.   He has a separate pull request to handle. I don't think it's worth holding up the doc update for this.

2020-12-31 23:53 UTC, merged

2020-12-31 23:53 UTC, nibinqtl commented
Released to master.