removed reference to clicking X in date range search field
mileweb/docs-content-cdn pull request #137
Opened 2020-12-31 20:34 UTC by marcfishelquantil

2020-12-31 21:22 UTC, burtonquantil requested changes
check the comment I made.

2020-12-31 21:22 UTC, burtonquantil commented on docs/portal/tasks/deployments.md
> +2. To filter results by time range, click the icon circled in the following figure, select or enter a start date and end date, and then click the icon to the right of the **End date** field.
I still don't understand the comment about clicking the icon to the right of the **End  date** field.
In Release25Dec2020's UI, the filtering  occurs without me having to click any icon. I just pick the dates and it does it.

2021-01-01 09:09 UTC, nibinqtl commented on docs/portal/tasks/deployments.md
> +2. To filter results by time range, click the icon circled in the following figure, select or enter a start date and end date, and then click the icon to the right of the **End date** field.
I think @marcfishelquantil is talking about this icon:
![image](https://user-images.githubusercontent.com/16727726/103436056-8adbbc00-4bcc-11eb-85e6-d85f46278218.png)
But I feel we really do not need to mention this kind of details. The UI should be straightforward enough.
If we mention too much details, it also makes the document too difficult to maintain.
Because every time to make a small changes to the UI, we also need to change the document.
The document should only need to explain concepts or work flow that are unique in our product.
For example, in this case, we should only mention that by clicking the filter icon, the user will be able to specify a start and an end date to filter the results.

2021-01-01 16:05 UTC, burtonquantil commented on docs/portal/tasks/deployments.md
> +2. To filter results by time range, click the icon circled in the following figure, select or enter a start date and end date, and then click the icon to the right of the **End date** field.
@nibinqtl   I agree and spoke to Marc about simplifying this yesterday. I gave him some examples avoiding references to **End Date** field and icons.

2021-01-04 03:24 UTC, marcfishelquantil commented on docs/portal/tasks/deployments.md
> +2. To filter results by time range, click the icon circled in the following figure, select or enter a start date and end date, and then click the icon to the right of the **End date** field.
@nibinqtl I will fix this and upload a new help deliverable.

2021-01-08 03:39 UTC, marcfishelquantil commented
Please review latest upload called "Updated directives and topics describing filters."

2021-01-08 22:02 UTC, burtonquantil approved these changes
OK to merge

2021-01-08 22:06 UTC, merged