Merge the latest changes to production
mileweb/docs-content-cdn pull request #138
Opened 2021-01-13 08:14 UTC by nibinqtl

2021-01-13 08:16 UTC, nibinqtl commented
@burtonquantil @marcfishelquantil , please take a look at my changes to faq.md

2021-01-13 22:32 UTC, marcfishelquantil commented on docs/edge-logic/faq.md
> +# ignore the Vary header, just pass it to the client
How about removing the word "just" in line 45?

2021-01-13 22:42 UTC, marcfishelquantil commented on docs/edge-logic/faq.md
> +Use the directive [`enable_websocket`](</docs/edge-logic/supported-directives.md#enable_websocket>) in the location where websocket is needed. Make sure the client uses HTTP/1.1 (not HTTP/2) to conne
Please add the word "the" after "where" so it reads as follows: "in the location where the websocket is needed."

2021-01-13 23:19 UTC, marcfishelquantil commented on docs/edge-logic/faq.md
> +If you use CDN360, your clients will connect to our PoP that is closest to them. The round trip time (RTT) can be a few hundred milliseconds smaller compared to connecting to the origin server direct
How about rewording this to the following:
If you use CDN360, your clients will connect to the CDN360 PoP that is closest to them. The round trip time (RTT) can be a few hundred milliseconds faster compared to connecting to the origin server directly. The TCP and TLS handshakes usually take 3-4 RTTs, which can be a second faster through CDN. By default, the CDN360 servers maintain persistent connections to the origin. You can increase the [keep-alive timeout](/docs/portal/edge-configurations/managing-origins) by up to 10 minutes in the origin configurations. In the meantime, if you know the content is not cacheable at all, use...

2021-01-13 23:23 UTC, marcfishelquantil commented on docs/edge-logic/faq.md
> +In many cases, "dynamic" does not mean the content is not cacheable at all. For example, the end users will not feel the difference if you cache the NBA score for 1 second. If you have 10 requests pe
Please consider the following rewording. Please note that "paremeter" is misspelled.
In many cases, "dynamic" does not mean the content is not cacheable. For example, end users will not experience the difference if you cache the NBA score for 1 second. If you have 10 requests per second to fetch the score, you can save 90% of the bandwidth and processing power. If the response depends on a query parameter or request header values, make sure those variables are [included in the cache key](#how-do-you-include-query-parameters-andor-request-headers-in-the-cache-key).

2021-01-13 23:34 UTC, marcfishelquantil commented on docs/edge-logic/faq.md
> +CDN360 has a directive [`origin_fast_route`](</docs/edge-logic/supported-directives.md#origin_fast_route>) to enable a "Fast Route" to access the origin. This is one of the most powerful features of
How about the following:
CDN360 has a directive [`origin_fast_route`](</docs/edge-logic/supported-directives.md#origin_fast_route>) that enables a "Fast Route" to access the origin. This powerful feature is based on CDN360's award-wining [High-speed Data Transmission](https://www.cdnetworks.com/enterprise-applications/high-speed-data-transmission/) (HDT) technology. This technology ensures that our servers always have the best possible channel to reach your origin, even under challenging situations. This directive can also be used for highly cacheable contents if the origin is hard to reach from certain networks or when the cache-miss performance is critical to you. However, the traffic served through the ""Fast Route" may be charged with a high price due to the higher cost associated with it. To try out this feature, contact the CDN360 support team.

2021-01-13 23:35 UTC, marcfishelquantil commented
@nibinqtl Bin, please see my feedback and let me know whether you have questions. Thank you.

2021-01-19 20:53 UTC, burtonquantil requested changes
I made a few recommendations.

2021-01-19 20:53 UTC, burtonquantil commented on docs/edge-logic/faq.md
>  ### How to support websocket?
In  http://docdev.quantil.com/cdn/docs/edge-logic/supported-directives#enable_websocket you refer to "the WebSocket protocol".   References only refer to "WebSocket" not "websocket"  https://en.wikipedia.org/wiki/WebSocket
Does this reference need to be updated?

2021-01-19 20:53 UTC, burtonquantil commented on docs/edge-logic/faq.md
> +Use the directive [`enable_websocket`](</docs/edge-logic/supported-directives.md#enable_websocket>) in the location where websocket is needed. Make sure the client uses HTTP/1.1 (not HTTP/2) to conne
should that actually be "the WebSocket protocol is needed" ?

2021-01-19 20:53 UTC, burtonquantil commented on docs/edge-logic/faq.md
> +Dynamic contents are usually generated on-the-fly for each request and are different across different visitors. Some examples are:
"across" doesn't sound like the right preposition to use.  @marcfishelquantil  I suggest changing "across different visitors to "for different visitors".

2021-01-19 20:53 UTC, burtonquantil commented on docs/edge-logic/faq.md
> +If you only have the origin server at a central data center or cloud, the performance can be quite poor if the visitor is far away from or does not have good connection to the data center. How can we
I haven't heard people say "at cloud" or "at the cloud".   I suggest "in a central data center or in the cloud" instead of  "at a central data center or cloud".

Also, insert the word "a" in front of "good"  , i.e.,  " a good connection"

2021-01-19 20:53 UTC, burtonquantil commented on docs/edge-logic/faq.md
> +If you use CDN360, your clients will connect to our PoP that is closest to them. The round trip time (RTT) can be a few hundred milliseconds smaller compared to connecting to the origin server direct
A further rewrite of the second sentence could condense it to " The round trip time (RTT) can be a few hundred milliseconds faster than directly connecting to the origin server."  
I think the word "the" should be inserted before CDN.  "... faster through the CDN".

2021-01-19 20:53 UTC, burtonquantil commented on docs/edge-logic/faq.md
> +In many cases, "dynamic" does not mean the content is not cacheable at all. For example, the end users will not feel the difference if you cache the NBA score for 1 second. If you have 10 requests pe
what is "the NBA score"?  Are you referring to the score of a professional NBA game?   I think "an NBA score" might be better. Not every reader is an NBA fan, so they may not recognize "NBA".   It may be better to say "cache the score of a basketball game".

2021-01-19 20:53 UTC, burtonquantil commented on docs/edge-logic/faq.md
> +CDN360 has a directive [`origin_fast_route`](</docs/edge-logic/supported-directives.md#origin_fast_route>) to enable a "Fast Route" to access the origin. This is one of the most powerful features of
Please change "award-wining" to "award-winning".  
Also change "charged with a high price" to "charged a higher price".    I haven't heard anyone use the word "with" like this.

2021-01-19 20:53 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +CDN360 has gzip always on, and applies it to the default MIME types above. In addition, compression is activated only when the response body size is greater than 1000 bytes. The default behavior shou
I sounds better to say "CDN360 always uses gzip and applies it to the default MIME types above."

2021-01-19 21:26 UTC, nibinqtl commented on docs/edge-logic/faq.md
> +# ignore the Vary header, just pass it to the client
We want to emphasize the fact that nothing else is done except passing it down.

2021-01-19 21:29 UTC, nibinqtl commented on docs/edge-logic/faq.md
> +Use the directive [`enable_websocket`](</docs/edge-logic/supported-directives.md#enable_websocket>) in the location where websocket is needed. Make sure the client uses HTTP/1.1 (not HTTP/2) to conne
Updated

2021-01-19 21:34 UTC, nibinqtl commented on docs/edge-logic/faq.md
> +If you use CDN360, your clients will connect to our PoP that is closest to them. The round trip time (RTT) can be a few hundred milliseconds smaller compared to connecting to the origin server direct
Updated

2021-01-19 21:37 UTC, nibinqtl commented on docs/edge-logic/faq.md
> +In many cases, "dynamic" does not mean the content is not cacheable at all. For example, the end users will not feel the difference if you cache the NBA score for 1 second. If you have 10 requests pe
Updated.

2021-01-19 21:44 UTC, nibinqtl commented on docs/edge-logic/faq.md
> +CDN360 has a directive [`origin_fast_route`](</docs/edge-logic/supported-directives.md#origin_fast_route>) to enable a "Fast Route" to access the origin. This is one of the most powerful features of
Updated

2021-01-19 21:45 UTC, nibinqtl commented on docs/edge-logic/faq.md
>  ### How to support websocket?
Updated

2021-01-19 21:45 UTC, nibinqtl commented on docs/edge-logic/faq.md
> +Dynamic contents are usually generated on-the-fly for each request and are different across different visitors. Some examples are:
Updated

2021-01-19 21:46 UTC, nibinqtl commented on docs/edge-logic/faq.md
> +If you only have the origin server at a central data center or cloud, the performance can be quite poor if the visitor is far away from or does not have good connection to the data center. How can we
Updated

2021-01-19 21:48 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +CDN360 has gzip always on, and applies it to the default MIME types above. In addition, compression is activated only when the response body size is greater than 1000 bytes. The default behavior shou
Updated.

2021-01-19 21:49 UTC, nibinqtl commented
I believe I addressed all suggestions. Please review again. @burtonquantil @marcfishelquantil

2021-01-19 22:59 UTC, burtonquantil submitted a review, later dismissed
OK to merge

2021-01-19 23:22 UTC, nibinqtl commented
@burtonquantil , I just merged your #139 and now this PR needs approval again.

2021-01-19 23:30 UTC, burtonquantil approved these changes
Thanks @nibinqtl  . OK to merge.

2021-01-19 23:39 UTC, merged