Changes to be release by 1/29
mileweb/docs-content-cdn pull request #140
Opened 2021-01-26 23:36 UTC by nibinqtl

2021-02-01 02:43 UTC, burtonquantil requested changes
I gave some small suggestions.

2021-02-01 02:43 UTC, burtonquantil commented on docs/edge-logic/faq.md
> +We also created a proprietary directive [`origin_header_modify`](</docs/edge-logic/supported-directives.md#origin_header_modify>) to manipulate the response header from origin, before any other proce
I suggest changing "before any other processings happen to the response."   to  "before any other processing of the response."

2021-02-01 02:43 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +Allows access for the specified network or address. (Work in progress to make this apply only on edge. <span class="badge yellow">ETA: Apr. 2021</span>)
I suggest changing "access for" to "access to".

2021-02-01 02:43 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +Denies access for the specified network or address. (Work in progress to make this apply only on edge. <span class="badge yellow">ETA: Apr. 2021</span>)
Suggest changing "access for" to "access from"

2021-02-01 22:46 UTC, marcfishelquantil commented on docs/edge-logic/faq.md
> +We also created a proprietary directive [`origin_header_modify`](</docs/edge-logic/supported-directives.md#origin_header_modify>) to manipulate the response header from origin, before any other proce
Burton's suggestion sounds good. Or how about "before the response is processed further."?

2021-02-01 22:46 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +Allows access for the specified network or address. (Work in progress to make this apply only on edge. <span class="badge yellow">ETA: Apr. 2021</span>)
I agree with Burton.

2021-02-01 22:47 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +Denies access for the specified network or address. (Work in progress to make this apply only on edge. <span class="badge yellow">ETA: Apr. 2021</span>)
I agree with Burton.

2021-02-01 22:52 UTC, marcfishelquantil commented on apispec/openapi.json
> +                    }
Please replace "Please contact our support team if you require it." with "Please contact our support team for assistance."

2021-02-01 22:53 UTC, marcfishelquantil commented on apispec/openapi.json
> +                    }
Please replace "Please contact our support team if you require it." with "Please contact our support team for assistance."

2021-02-01 23:06 UTC, marcfishelquantil commented on apispec/openapi.json
>          "operationId": "getStagingServers",
Please consider changing " If you use options 2 or 3 above, you should periodically check if the IP address is still valid using this API." to " If you use option 2 or 3 above, check periodically whether the IP address is still valid using this API."

2021-02-01 23:15 UTC, marcfishelquantil commented on docs/edge-logic/faq.md
> +By default, the cache key of CDN360 includes only the hostname and URI without the query string in the request. It also includes a special variable that is accessible in the Edge Logic: `$cache_misc`
How about changing "By default, the cache key of CDN360 includes only the..." to "By default, the CDN360 cache key includes only the..."

2021-02-01 23:16 UTC, marcfishelquantil commented on docs/edge-logic/faq.md
> +In order to consolidate the responses from the origin to improve the cache hit ratio, we created a dedicated directive [`sanitize_accept_encoding`](</docs/edge-logic/supported-directives.md#sanitize_
General comment: The term "in order" is superfluous and often can be removed without harming the sentence. In this case, please consider starting the sentence with "To consolidate the responses..."

2021-02-01 23:28 UTC, marcfishelquantil commented
Thank you for allowing me to add my comments.

2021-02-12 10:02 UTC, nibinqtl commented on docs/edge-logic/faq.md
> +We also created a proprietary directive [`origin_header_modify`](</docs/edge-logic/supported-directives.md#origin_header_modify>) to manipulate the response header from origin, before any other proce
Just updated

2021-02-12 10:02 UTC, nibinqtl commented on docs/edge-logic/faq.md
> +By default, the cache key of CDN360 includes only the hostname and URI without the query string in the request. It also includes a special variable that is accessible in the Edge Logic: `$cache_misc`
Just updated

2021-02-12 10:05 UTC, nibinqtl commented on docs/edge-logic/faq.md
> +In order to consolidate the responses from the origin to improve the cache hit ratio, we created a dedicated directive [`sanitize_accept_encoding`](</docs/edge-logic/supported-directives.md#sanitize_
I feel "in order to" emphasizes the goal. I believe this is the reason for the existence of this phrase?

2021-02-12 10:13 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +Allows access for the specified network or address. (Work in progress to make this apply only on edge. <span class="badge yellow">ETA: Apr. 2021</span>)
Just changed to "access from"

2021-02-12 10:13 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +Denies access for the specified network or address. (Work in progress to make this apply only on edge. <span class="badge yellow">ETA: Apr. 2021</span>)
Just changed to "access from"

2021-02-12 10:15 UTC, nibinqtl commented
@burtonquantil and @marcfishelquantil , please do a final review of this.

2021-02-12 20:17 UTC, burtonquantil commented on docs/edge-logic/faq.md
> +In order to consolidate the responses from the origin to improve the cache hit ratio, we created a dedicated directive [`sanitize_accept_encoding`](</docs/edge-logic/supported-directives.md#sanitize_
Both are grammatically correct, and the meaning is the same, so it is not strictly necessary to change it.

However,  "To consolidate" is better because it is more succinct. 
If you say "I'm going to the store to get bread", that is straightforward. It is not necessary to say "I'm going to the store in order to get bread".

2021-02-12 20:19 UTC, burtonquantil approved these changes
OK to merge to production.

2021-02-12 20:19 UTC, burtonquantil commented on docs/edge-logic/faq.md
> +We also created a proprietary directive [`origin_header_modify`](</docs/edge-logic/supported-directives.md#origin_header_modify>) to manipulate the response header from origin, before any other proce
the comma after "origin" looks unnecessary.

2021-02-12 21:23 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +Allows access for the specified network or address. (Work in progress to make this apply only on edge. <span class="badge yellow">ETA: Apr. 2021</span>)
"access from" sounds good.

2021-02-12 21:24 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +Denies access for the specified network or address. (Work in progress to make this apply only on edge. <span class="badge yellow">ETA: Apr. 2021</span>)
sounds good.

2021-02-12 21:25 UTC, marcfishelquantil commented on docs/edge-logic/faq.md
> +By default, the cache key of CDN360 includes only the hostname and URI without the query string in the request. It also includes a special variable that is accessible in the Edge Logic: `$cache_misc`
How about replacing " the cache key of CDN360 includes only " with " the CDN360 cache key includes only "?

2021-02-12 21:26 UTC, marcfishelquantil commented
Thank you for allowing me to comment one more time.

2021-02-13 18:21 UTC, marcfishelquantil commented on docs/edge-logic/faq.md
> +We also created a proprietary directive [`origin_header_modify`](</docs/edge-logic/supported-directives.md#origin_header_modify>) to manipulate the response header from origin, before any other proce
The comma is unnecessary.

2021-02-16 06:56 UTC, nibinqtl commented on docs/edge-logic/faq.md
> +We also created a proprietary directive [`origin_header_modify`](</docs/edge-logic/supported-directives.md#origin_header_modify>) to manipulate the response header from origin, before any other proce
will fix next time.

2021-02-16 06:56 UTC, merged