To be released by 2/23
mileweb/docs-content-cdn pull request #149
Opened 2021-02-16 11:59 UTC by nibinqtl

@burtonquantil and @marcfishelquantil , please review the new file added by me: REST API acceleration

2021-02-17 20:20 UTC, marcfishelquantil commented on docs/edge-logic/faq.md
Please change line 34 as follows (changes are in CAPS): "We also created a proprietary directive [`origin_header_modify`](</docs/edge-logic/supported-directives.md#origin_header_modify>) to manipulate the response header from THE origin PRIOR TO processing the response. This can be very useful if you need to override A header value (such as cache time) from the origin that may affect the CDN servers' behavior."

2021-02-17 20:22 UTC, marcfishelquantil commented on docs/portal/accessing-portal/navigating-ui.md
> +- Content that has been requested and when, the IP address from which requests were made, the value of the User-Agent HTTP request header, and the size of the content requested.
Looks fine to me. A more verbose definition could be: "- Content that has been requested and THE START AND END TIME OF THE REQUEST, the IP address from which requests were made, the value of the User-Agent HTTP request header, and the size of the content requested."

or

"Content that has been requested and THE TIME when IT WAS REQUESTED, the IP address from which requests were made, the value of the User-Agent HTTP request header, and the size of the content requested."

2021-02-17 20:26 UTC, burtonquantil requested changes
I made some suggestions.

2021-02-17 20:26 UTC, burtonquantil commented on docs/recipes/api-acceleration.md
> +API calls are usually considered dynamic HTTP requests, since the responses are generated
Remove the comma after "API calls are usually considered dynamic HTTP requests".

2021-02-17 20:26 UTC, burtonquantil commented on docs/recipes/api-acceleration.md
> +of a mobile or web app may reload the same page repeatedly, which may generate lots of
Suggestion:  "For example, the user of a mobile or web app may repeatedly reload the same page generating lots of "
What do you think @marcfishelquantil  ?

2021-02-17 20:26 UTC, burtonquantil commented on docs/recipes/api-acceleration.md
> +duplicated API calls in a short period of time. Some caching using CDN can result in a
Replace "duplicated" with "duplicate".

2021-02-17 20:26 UTC, burtonquantil commented on docs/recipes/api-acceleration.md
> +duplicated API calls in a short period of time. Some caching using CDN can result in a
Suggestion: Some caching using **a** CDN  can drastically improve the performance.

2021-02-17 20:26 UTC, burtonquantil commented on docs/recipes/api-acceleration.md
> +* You currently setup the DNS server to resolve this hostname to 2 IP addresses: `1.1.1.1`
Change "setup" to the verb "set up".

I prefer to see "two" versus "2", but that's minor.

2021-02-17 20:26 UTC, burtonquantil commented on docs/recipes/api-acceleration.md
> +In order to use CDN360 to accelerate this service, we need to do the following:
Replace "In order to use" with "To use" .
Marc mentioned in another place that "In order" is really unnecessary verbiage.

2021-02-17 20:26 UTC, burtonquantil commented on docs/recipes/api-acceleration.md
> +no longer be used because we later will CNAME it to a CDN360 edge hostname to direct
Change "later will" to "will later".

Is it proper to use "CNAME" as a verb?

2021-02-17 20:26 UTC, burtonquantil commented on docs/recipes/api-acceleration.md
> +upload the certificate for `api.company.com` to the CDN360 platform. We recommend the use
Suggest replacing "the use of " to "using"

2021-02-17 20:26 UTC, burtonquantil commented on docs/recipes/api-acceleration.md
> +<p align=center><img src="/docs/resources/images/recipes/api/upload-certificate.png" alt="upload certificate" width="700"></p>
in sprint 101 which we will release soon, we changed the certificate selection to radio buttons per your request. NCP-2164

2021-02-17 20:26 UTC, burtonquantil commented on docs/recipes/api-acceleration.md
> +* Go to the CDN360 portal to create an property to accelerate this API service. The
Change "an property" to "a property".

2021-02-17 20:26 UTC, burtonquantil commented on docs/recipes/api-acceleration.md
> +to reach the origin to ensure security. The `Host` header value is specified to be the
I suggest simplifying  "is specified to be " to simply "is ".

2021-02-17 20:26 UTC, burtonquantil commented on docs/recipes/api-acceleration.md
> +default, CDN360 will pass the `Host` header value received from client to the origin. We also
I suggest changing   "from client" to "from the client"

2021-02-17 20:26 UTC, burtonquantil commented on docs/recipes/api-acceleration.md
> +chose "Always Direct" to reach the origin without going through a parent cache. This is because we want to
Suggestion: combine sentences.    
"... through a parent cache because we want to minimize latency and know there will not be a cache hit across different servers".

2021-02-17 20:26 UTC, burtonquantil commented on docs/recipes/api-acceleration.md
> +cached content will be only served to the same user from the same IP address. Combined
I think "will be only served" should be "will be served only" ?  @marcfishelquantil

2021-02-17 20:26 UTC, burtonquantil commented on docs/recipes/api-acceleration.md
> +clients to use the `Cache-Control: no-cache` header field to by pass cache. When a CDN360
change "by pass cache" to "bypass the cache"

2021-02-17 20:26 UTC, burtonquantil commented on docs/recipes/api-acceleration.md
> +Any request to `api.company.com` will now be routed to the CDN360 platform. Every cache-miss
I think "cache-miss"  should be "cache miss".

2021-02-17 20:26 UTC, burtonquantil commented on docs/recipes/api-acceleration.md
> +cached copy expires, the content will be served immediately by the CDN360 server, with
remove the comma after "CDN360 server" .
Change "turn-around" to "turnaround"

2021-02-17 20:26 UTC, burtonquantil commented on docs/recipes/api-acceleration.md
> +much smaller turn-around time. The end user will experience an improved performance and
Change "an improved performance" to "improved performance"

2021-02-17 20:26 UTC, marcfishelquantil commented on docs/portal/identities-and-access/overview.md
> +| 1 | Identity and access management tasks are organized into the following tabs:<ul> <li>**Users** allows administrators to manage users. Operators and viewers are limited to seeing other portal use
Looks fine to me.

2021-02-17 20:27 UTC, marcfishelquantil commented on docs/portal/reports.md
> +| Access Log Download| Shows what content has been requested and when it was requested, the IP address from which requests were made, the value of the User-Agent HTTP request header, and the size of
Please see my comment above on line 31.

2021-02-17 20:28 UTC, marcfishelquantil commented on docs/portal/reports.md
> +| Hostname | For Access Log Download reports, select a property hostname. Logs of visitors to the hostname will be generated for you to view and download.
Looks fine to me.

2021-02-17 20:32 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +of a mobile or web app may reload the same page repeatedly, which may generate lots of
Since you use "may" earlier in this sentence, how about rewording the text string from "..which may generate lost of..." to "...which can generate a lot of..."

2021-02-17 20:33 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +drastic improvement of the performance. In this article, we are going to use an example to illustrate how
Please change "drastic improvement of the performance" to "significant performance improvement" or "significant improvement in performance."

2021-02-17 20:56 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +* You currently setup the DNS server to resolve this hostname to 2 IP addresses: `1.1.1.1`
setup should be two words (set up).

2021-02-17 20:57 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +* The client is using the `Authorization` request header to pass the credential to the
In lines 17 & 18, please consider using "uses" instead of "is using." Please add a period after "PATCH" at the end of the sentence on line 17.

2021-02-17 20:58 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +variable `$remote_user`. Please notice that this does not mean you have to use the basic
The words "Please notice that" are extraneous and can be removed.

2021-02-17 20:59 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +In order to use CDN360 to accelerate this service, we need to do the following:
Please remove "In order." Also, please remove "we need to."

2021-02-17 21:01 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +CDN360 servers need to use it to reach the origin servers. The name `api.company.com` can
Please change "need to use it" to "use the DNS record"

2021-02-17 21:02 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +client's traffic to the platform to be accelerated.
please change " later will CNAME it to a" to " CNAME it later to a"

2021-02-17 21:02 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +upload the certificate for `api.company.com` to the CDN360 platform. We recommend the use
Please change "the use of" to "you use"

2021-02-17 21:04 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +important thing in this step is to enter the correct hostname to be accelerated: `api.company.com`.
Consider changing "The important thing in this step is..." to "It is important to" or "Be sure to".

2021-02-17 21:05 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +one required by the origin. In this case, we can actually leave it empty because by
Please add a comma after "because".

2021-02-17 21:07 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +cached content will be only served to the same user from the same IP address. Combined
Please change "will be only served to" to "will be served only to".

2021-02-17 21:07 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +with HTTPS and the short cache time of 1 minute, this should be safe enough for the vast
Please consider changing "safe enough" to "sufficiently safe".

2021-02-17 21:08 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +server sees this field value, it will go directly to origin without looking up the cache.
Should be "to the origin".

2021-02-17 21:09 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +Last but not least, we enabled the [Fast Route to origin](/docs/edge-logic/supported-directives#origin_fast_route)
"Last but not least" is too colloquial IMHO. How about "Lastly" instead?

2021-02-17 21:10 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +* If you still don't have one, create an "edge hostname" based on your intended delivery
Still don't have what? Please replace "one" with "edge hostname".

2021-02-17 21:10 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +destination and performance/cost requirement. Then, update the DNS record of `api.company.com`
Please remove the comma after "Then".

2021-02-17 21:12 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +much smaller turn-around time. The end user will experience an improved performance and
Please add "a" between "with" and "smaller" as follows: "with a much smaller". Or how about replacing "smaller" with "faster" as in: "with a much faster".

2021-02-17 21:12 UTC, marcfishelquantil commented on docs/recipes/api-acceleration.md
> +the origin server will be alleviated from generating the same content repeatedly in a
Instead of "be alleviated from generating" how about "not have to generate".

2021-02-24 11:15 UTC, nibinqtl commented
I think I addressed all suggestions made by @burtonquantil and @marcfishelquantil . Please take another look.

2021-02-24 19:59 UTC, burtonquantil approved these changes
OK to merge.

2021-02-25 00:35 UTC, merged