added supported variables
mileweb/docs-content-cdn pull request #156
Opened 2021-02-23 01:07 UTC by ronyayoung

Please help review the supported-variables.md file and the manifest.json file.  Thanks.

2021-02-23 01:53 UTC, nibinqtl approved these changes
Technically looks good to me.

2021-02-23 19:18 UTC, burtonquantil requested changes
I made some suggestions

2021-02-23 19:18 UTC, burtonquantil commented on docs/edge-logic/supported-variables.md
> +| $cache_misc | A variable for adding additional information to default cache-key |
@nibinqtl  are you sure "cache-key" is supposed to be written with a hyphen?

2021-02-23 19:18 UTC, burtonquantil commented on docs/edge-logic/supported-variables.md
> +| $sorted_querystring_arg | Variable provides a (ASCII based) sorted list of input query parameters <br> Modifiable by directive 'sorted_querystring_filter_parameter' |
I suggest rephrasing as:  "Variable providing an ASCII based sorted list of input query parameters.  It can be modified by the 'sorted_querystring_filter_parameter'.

2021-02-23 19:31 UTC, marcfishelquantil commented on docs/edge-logic/supported-variables.md
> +| $cache_misc | A variable for adding additional information to default cache-key |
Using "adding" and "additional" in the same sentence is redundant. Please remove one of them. How about: "A variable for adding information to..." Also, I agree with Burton that "cache-key" does not require a hyphen.

2021-02-23 19:32 UTC, marcfishelquantil commented on docs/edge-logic/supported-variables.md
> +| $sorted_querystring_arg | Variable provides a (ASCII based) sorted list of input query parameters <br> Modifiable by directive 'sorted_querystring_filter_parameter' |
If you accept Burton's suggestion, please insert a hyphen between "ASCII" and "based."

2021-02-23 19:33 UTC, marcfishelquantil reviewed
I made some comments as well, all of them grammatical suggestions.

2021-02-24 07:35 UTC, ronyayoung commented on docs/edge-logic/supported-variables.md
> +| $cache_misc | A variable for adding additional information to default cache-key |
Thanks for the feedback. I changed the "adding additional" to "adding extra" in the sentence as I'd like to emphasize the $cache_misc is intended for adding more information to the default cache key.

2021-02-24 09:20 UTC, nibinqtl commented on docs/edge-logic/supported-variables.md
> +| $cache_misc | A variable for adding additional information to default cache-key |
I'm not sure.

2021-02-24 09:25 UTC, nibinqtl commented on docs/edge-logic/supported-variables.md
> +CDN360 EdgeLogic directives support open-source Nginx defined [variables](http://nginx.org/en/docs/varindex.html).  For the advanced and proprietary directives, CDNetworks also introduced the followi
I feel it is better to rephrase as: "CDN360 Edge Logic supports variables defined by the open-source nginx. In addition, we also introduced the following ones:"

2021-02-26 06:46 UTC, nibinqtl approved these changes
Let's push this to dev and see how it looks on docdev.quantil.com

2021-02-26 22:52 UTC, burtonquantil submitted a review, later dismissed
OK to merge.

2021-02-26 22:52 UTC, burtonquantil commented on docs/edge-logic/supported-variables.md
> +| $sorted_querystring_arg | Variable provides a (ASCII based) sorted list of input query parameters <br> Modifiable by directive 'sorted_querystring_filter_parameter' |
Minor suggestion: Though you inserted a <br> tag to break the line in two, I think it would actually be better to end sentences with periods.

2021-02-26 22:52 UTC, burtonquantil commented on docs/edge-logic/supported-variables.md
> +| $time_rfc822 | Variable to keep the current time in the RFC822 time zone format <br> - for example: "Mon, 28 Sep 1970 06:00:00 GMT" |
I'm not sure what is meant by "keep the current time".

@nibinqtl

2021-02-27 08:18 UTC, nibinqtl approved these changes
This is a good start.

2021-02-28 05:04 UTC, merged