Release by 3/3
mileweb/docs-content-cdn pull request #158
Opened 2021-02-25 00:55 UTC by nibinqtl

2021-03-01 07:19 UTC, nibinqtl commented
Hi @marcfishelquantil and @burtonquantil , can you please review this one?

2021-03-02 00:36 UTC, burtonquantil requested changes
I made suggestions and comments.

2021-03-02 19:48 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +This directive specifies the origin to fetch the content. It is a wrapper of the NGINX [proxy_pass](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass) directive. It takes one parame
In addition to supporting Burton's comment, please consider changing "If you want to drop the query string..." to "To drop the query string...".

2021-03-02 20:04 UTC, marcfishelquantil commented on docs/edge-logic/built-in-variables.md
> +Here are all the built-in variables supported by the CDN360 servers. You can use them in Edge Logic or the real-time log. Please notice that not all variables are supported in both places.
Please consider replacing "Here are all..." with "The following are all..."
In the last sentence, please consider deleting the words "Please notice that" and start the sentence with "Not all variables are..."

2021-03-02 20:14 UTC, marcfishelquantil commented on docs/edge-logic/built-in-variables.md
> +If you use the CDN360 portal to edit the property, the autocompletion feature will bring up all the supported variables if you type a `$` at the right position.
Please consider replacing "bring up" with "lists". Or consider replacing the entire sentence with the following: "If you use the CDN360 portal to edit the property, typing '$' at the right position lists all the supported variables."

2021-03-02 20:23 UTC, marcfishelquantil commented on docs/edge-logic/built-in-variables.md
> +| $invalid_referer | empty string, if the “Referer” request header field value is considered valid, otherwise “1” | <span class="badge green">Yes</span> | <span class="badge green">Yes</span> |
Please delete the comma between "empty string" and "if."
Please consider the following punctuation changes: from "value is considered valid, otherwise" to "value is considered valid; otherwise,".

2021-03-02 20:26 UTC, marcfishelquantil commented on docs/edge-logic/built-in-variables.md
> +| $pipe | p if request is pipelined, or . otherwise. | <span class="badge yellow">No</span> | <span class="badge green">Yes</span> |
Please consider changing "p if request is pipelined, or . otherwise. " to "p if request is pipelined; otherwise, type a period (.)"

2021-03-02 20:27 UTC, marcfishelquantil commented on docs/edge-logic/built-in-variables.md
> +| $qtl_req_id | unique ID for the request | <span class="badge green">Yes</span> | <span class="badge green">Yes</span> |
You could change " unique ID for the request" to " unique request ID."

2021-03-02 20:33 UTC, marcfishelquantil commented on docs/edge-logic/built-in-variables.md
> +| $tcpinfo_delivery_rate | TCP connection performance metrics to report the rate at which the sent data is acknowledged in bytes/s | <span class="badge yellow">No</span> | <span class="badge green">Y
Please consider changing "TCP connection performance metrics to report the rate at which the sent data is acknowledged in bytes/s " to "TCP connection performance metrics, in bytes/s, to report the rate at which the sent data is acknowledged"

2021-03-02 20:36 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +This directive belongs to the nginx [rewrite module](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html). It is executed `imperatively` with the other directives in the same module in an earl
Should nginx be Nchanged to GINX?

2021-03-02 20:37 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +This directive belongs to the nginx [rewrite module](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html). It is executed `imperatively` with the other directives in the same module in an earl
Same comment as above about capitalizing NGINX.

2021-03-02 20:43 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +This directive belongs to the nginx [rewrite module](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html). It is executed `imperatively` with the other directives in the same module in an earl
@marcfishelquantil  I've seen it written as "nginx", "NGINX", and "Nginx".  Book titles seem to use one of the latter two.

2021-03-02 20:51 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +This directive specifies the origin to fetch the content. It is a wrapper of the NGINX [proxy_pass](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass) directive. It takes one parame
Please consider changing "If you want to drop the query string, just put `$uri` after the origin name" to "To drop the query string, add `$uri` after the origin name"

2021-03-02 20:56 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +Defines conditions under which the response will not be taken from a cache. If at least one value of the string parameters is not empty and is not equal to “0” then the response will not be taken fro
Do we need the "a" in the string "Defines conditions under which the response will not be taken from a cache."?

In the second sentence, please change "If at least one value of the string parameters is not empty and is not equal to “0” then the response will not be taken from the cache." to "If at least one value of the string parameters is not empty and is not equal to “0”, the response will not be taken from cache."

In the third sentence, what does "those" conditions refer to? If it refers to at least one value of the string parameters being not empty and not equal to “0”, then say "...not cacheable according to the conditions above." OR say "This should be used if you know the content is not cacheable because at least one value of the string parameters is not empty and is not equal to “0”."

2021-03-02 20:57 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +Please notice that this directive does not prevent the response from being save in the cache.
Please consider deleting "Please notice that." and start the sentence with "This directive does not..."

2021-03-02 20:58 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +If the client request method is listed in this directive then the response will be cached. “GET” and “HEAD” methods are always added to the list, though it is recommended to specify them explicitly.
Please change "If the client request method is listed in this directive then the response will be cached." to "If the client request method is listed in this directive, the response will be cached."

2021-03-02 20:59 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +Defines conditions under which the response will not be saved to a cache. If at least one value of the string parameters is not empty and is not equal to “0” then the response will not be saved:
Please see my comment above.

2021-03-02 21:00 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +Since the content is not saved, usually there is no point to look up the cache under the same conditions. Therefore, this directive is commonly used together with the [`proxy_cache_bypass`](#proxy_ca
You could change "usually there is no point to look up" to "usually there is no point in looking up".

2021-03-02 21:01 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +This directive belongs to the nginx [rewrite module](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html). It is executed `imperatively` with the other directives in the same module in an earl
Here and elsewhere, please capitalize NGINX when it refers to the product. Please keep it lowercase in URLs.

2021-03-05 11:12 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +This directive specifies the origin to fetch the content. It is a wrapper of the NGINX [proxy_pass](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass) directive. It takes one parame
fixed

2021-03-05 11:13 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +Sets caching time for different response codes. We enhanced the [open-source version](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_valid) to support setting `time` with a vari
fixed.

2021-03-05 11:16 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +This directive belongs to the nginx [rewrite module](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html). It is executed `imperatively` with the other directives in the same module in an earl
The nginx official documentation uses all lower case. http://nginx.org/en/docs/

2021-03-05 11:20 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +This directive specifies the origin to fetch the content. It is a wrapper of the NGINX [proxy_pass](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass) directive. It takes one parame
fixed.

2021-03-05 11:23 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +Defines conditions under which the response will not be taken from a cache. If at least one value of the string parameters is not empty and is not equal to “0” then the response will not be taken fro
fixed.

2021-03-05 11:28 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +This directive belongs to the nginx [rewrite module](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html). It is executed `imperatively` with the other directives in the same module in an earl
In will use the all lower case version consistently in this document, to follow the convention of the official document site.

2021-03-05 11:42 UTC, nibinqtl commented on docs/edge-logic/built-in-variables.md
> +| $connection_requests | current number of requests in the connection | <span class="badge yellow">No</span> | <span class="badge green">Yes</span> |
Yes.

2021-03-05 11:43 UTC, nibinqtl commented on docs/edge-logic/built-in-variables.md
> +| $host | host header or matched server_name | <span class="badge green">Yes</span> | <span class="badge green">Yes</span> |
Yes.

2021-03-05 11:58 UTC, nibinqtl commented
I think I addressed all the comments.

2021-03-05 11:59 UTC, nibinqtl commented
@burtonquantil @marcfishelquantil , please take another look.

2021-03-06 00:14 UTC, burtonquantil requested changes
I posted a few small suggestions and questions.

2021-03-06 00:14 UTC, burtonquantil commented on docs/edge-logic/built-in-variables.md
> +| $content_type | request content-type header | <span class="badge green">Yes</span> | <span class="badge green">Yes</span> |
Should this be similar to the line above and be rewritten as   "request's Content-Type header" ?

2021-03-06 00:14 UTC, burtonquantil commented on docs/edge-logic/built-in-variables.md
> +| $http_host | request Host header | <span class="badge green">Yes</span> | <span class="badge green">Yes</span> |
Is this better written as "request's Host header" ?

2021-03-06 00:14 UTC, burtonquantil commented on docs/edge-logic/built-in-variables.md
> +| $ssl_protocol | returns protocol name like: TLSv1.1 | <span class="badge yellow">No</span> | <span class="badge green">Yes</span> |
Minor: The colon is unnecessary.

2021-03-06 00:14 UTC, burtonquantil commented on docs/edge-logic/built-in-variables.md
> +| $time_rfc822 | current time in RFC822 | <span class="badge green">Yes</span> | <span class="badge green">Yes</span> |
RFC 822 describe mail message format.  What does "current time in RFC822" mean?

2021-03-06 00:14 UTC, burtonquantil commented on docs/edge-logic/built-in-variables.md
> +| $upstream_response_time | keeps time spent on receiving the response from the upstream server; <br> the time is kept in seconds with millisecond resolution | <span class="badge green">Yes</span> |
I think "on receiving" should simply be "receiving".

2021-03-06 00:14 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +This directive does not prevent the response from being save in the cache.
Grammar correction:  "save" should be "saved"

2021-03-06 00:34 UTC, nibinqtl commented
Addressed Burton's comments again

2021-03-06 00:35 UTC, nibinqtl commented on docs/edge-logic/built-in-variables.md
> +| $time_rfc822 | current time in RFC822 | <span class="badge green">Yes</span> | <span class="badge green">Yes</span> |
There is a chapter in this RFC about date and time format: https://tools.ietf.org/html/rfc822#section-5.1

2021-03-06 00:40 UTC, burtonquantil commented on docs/edge-logic/built-in-variables.md
> +| $time_rfc822 | current time in RFC822 | <span class="badge green">Yes</span> | <span class="badge green">Yes</span> |
"current time in RFC822 format" would be better then.

2021-03-06 00:41 UTC, burtonquantil submitted a review, later dismissed
OK to merge. I asked Marc to take a quick look at your pull request as well.

2021-03-06 00:57 UTC, nibinqtl commented on docs/edge-logic/built-in-variables.md
> +| $time_rfc822 | current time in RFC822 | <span class="badge green">Yes</span> | <span class="badge green">Yes</span> |
I decided to hide this variable because rfc822 is outdated. It uses 2 digits to represent year.

2021-03-06 01:56 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +Sets caching time for different response codes. We enhanced the [open-source version](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_valid) to support setting `time` with a vari
Please add a period to the end of "etc"

2021-03-06 02:11 UTC, burtonquantil approved these changes
OK to merge.

2021-03-06 02:11 UTC, burtonquantil commented on docs/edge-logic/built-in-variables.md
> +| $qtl_upstream_cache_status | edge cache HIT, MISS etc. | <span class="badge green">Yes</span> | <span class="badge green">Yes</span> |
There ought to be a comma after "MISS".  However, what are the other possibilities?

2021-03-06 02:45 UTC, nibinqtl commented on docs/edge-logic/built-in-variables.md
> +| $qtl_upstream_cache_status | edge cache HIT, MISS etc. | <span class="badge green">Yes</span> | <span class="badge green">Yes</span> |
There are more. We can introduce them later.

2021-03-06 02:46 UTC, merged