To be released on 4/7
mileweb/docs-content-cdn pull request #163
Opened 2021-03-31 08:34 UTC by nibinqtl

2021-03-31 08:55 UTC, nibinqtl commented
@marcfishelquantil @burtonquantil , please help review the new article about secure content delivery

2021-04-01 01:15 UTC, nibinqtl commented
Thanks @marcfishelquantil . I merged your edits and made some additional changes. I may make some more changes before the release. Will need you to review again.

2021-04-01 01:58 UTC, burtonquantil requested changes
I made a few small suggestions.

2021-04-01 01:58 UTC, burtonquantil commented on docs/recipes/secure-delivery.md
> +Security and protection of privacy have raised increasing concerns over the last few years — and for good reason. Hardly a day goes by when the headlines aren't filled with another major security bre
Simplify the first sentence.
"Security and protection of privacy are increasing concerns over the last few years"

2021-04-01 01:58 UTC, burtonquantil commented on docs/recipes/secure-delivery.md
> +Based on regularly updated rules, the firewall rejects suspicious packets that may endanger services and forwards only the "safe" packets to the servers located behind the firewall. This feature is e
"transparent to customers"  - Since you began the article addressing the audience with "your" and "you", shouldn't this be "... transparent to you"  ?

2021-04-01 01:58 UTC, burtonquantil commented on docs/recipes/secure-delivery.md
> +#Step 2: sign STS with secKey
Minor suggestion: I think inserting an empty row between the steps improves readability, though of course, it is irrelevant to the software.

2021-04-01 01:58 UTC, burtonquantil commented on docs/recipes/secure-delivery.md
> +* CDN360 supports TLS certificates with both RSA and ECDSA algorithms. You can even configure 2 certificates with different algorithms in the same property and have the server pick one based on the c
I'd use "two" instead of "2" , but it's OK if you wish to leave it as is.

2021-04-01 01:58 UTC, burtonquantil commented on docs/recipes/secure-delivery.md
> +* If your site supports HTTPS, a good practice is to redirect all HTTP requests to the HTTPS counterpart. You can achieve this on the [CDN360 portal](/docs/portal/edge-configurations/creating-propert
I would rewrite the last sentence slightly
"You can achieve this **using** the [CDN360 portal](/docs/portal/edge-configurations/creating-property.md#tls-settings) **by selecting an option from a list**.

2021-04-07 22:04 UTC, nibinqtl commented on docs/recipes/secure-delivery.md
> +Security and protection of privacy have raised increasing concerns over the last few years — and for good reason. Hardly a day goes by when the headlines aren't filled with another major security bre
made a small change but decided to keep the "raised".

2021-04-07 22:06 UTC, nibinqtl commented on docs/recipes/secure-delivery.md
> +Based on regularly updated rules, the firewall rejects suspicious packets that may endanger services and forwards only the "safe" packets to the servers located behind the firewall. This feature is e
changed to "all the users"

2021-04-07 22:23 UTC, nibinqtl commented on docs/recipes/secure-delivery.md
> +* If your site supports HTTPS, a good practice is to redirect all HTTP requests to the HTTPS counterpart. You can achieve this on the [CDN360 portal](/docs/portal/edge-configurations/creating-propert
rewrote with a screenshot of the dropdown list

2021-04-07 22:33 UTC, nibinqtl commented
Hi @burtonquantil and @marcfishelquantil , please take a look at all the changes I have made after your last reviews.

2021-04-07 22:49 UTC, marcfishelquantil commented on docs/recipes/secure-delivery.md
> +* If your site supports HTTPS, a good practice is to redirect all HTTP requests to the HTTPS counterpart. You can achieve this on the [CDN360 portal](/docs/portal/edge-configurations/creating-propert
In the last sentence, I would suggest replacing "with" with "using". I would also remove "simply." Here are some suggestions to consider that include or omit "with" and "simply."

"You can achieve this on the [CDN360 portal](/docs/portal/edge-configurations/creating-property.md#tls-settings) using a drop-down list." 

"You can achieve this on the [CDN360 portal](/docs/portal/edge-configurations/creating-property.md#tls-settings) simply by using a drop-down list."

"You can easily achieve this on the [CDN360 portal](/docs/portal/edge-configurations/creating-property.md#tls-settings) by using a drop-down list."

"You can achieve this easily on the [CDN360 portal](/docs/portal/edge-configurations/creating-property.md#tls-settings) by using a drop-down list."

"Redirecting HTTP requests to HTTPS on the [CDN360 portal](/docs/portal/edge-configurations/creating-property.md#tls-settings) is as easy as selecting a the redirect option in a drop-down list."

"To redirect HTTP requests to HTTPS on the [CDN360 portal](/docs/portal/edge-configurations/creating-property.md#tls-settings), just select the redirect option from a drop-down list."

2021-04-07 22:59 UTC, burtonquantil approved these changes
OK to merge

2021-04-07 23:05 UTC, merged