To be release on 4/22
mileweb/docs-content-cdn pull request #167
Opened 2021-04-09 10:26 UTC by nibinqtl

2021-04-09 18:45 UTC, burtonquantil requested changes
Only a couple of minor suggestions.

2021-04-09 18:45 UTC, burtonquantil commented on docs/edge-logic/faq.md
> +We modified the open-source NGINX to strictly follow the HTTP standard regarding 'zero-time cache'. When `no-cache` or `max-age=0` is present in the `Cache-Control` header field, the response is stil
Omit the comma before "but expires immediately".

2021-04-09 18:45 UTC, burtonquantil commented on docs/edge-logic/faq.md
> +If the above mentioned default behavior is not meeting your requirement, you can use the following directives to alter it.
Suggestion:   If the default behavior does not meet your requirements, use the following directives to alter it.

2021-04-09 19:08 UTC, marcfishelquantil commented on docs/edge-logic/faq.md
> +We modified the open-source NGINX to strictly follow the HTTP standard regarding 'zero-time cache'. When `no-cache` or `max-age=0` is present in the `Cache-Control` header field, the response is stil
In the second sentence, please add the word "to" between "is" and "honor." So the sentence reads "...the default behavior of CDN360 edge servers is to "honor the origin"."
In the last sentence in the first paragraph, please delete "In the meantime," as it adds nothing to the sentence.

2021-04-09 19:11 UTC, marcfishelquantil commented on docs/edge-logic/faq.md
> +If the above mentioned default behavior is not meeting your requirement, you can use the following directives to alter it.
The first sentence is pretty long. How about breaking it into 2 sentences: "...to the edge server. Efforts have  been made..."
In the second sentence, please add a comma between "above" and "mentioned." How about rewording this sentence as follows: "If the default behavior mentioned above does not meet your requirement, use the following directives to change the behavior."

2021-04-09 20:21 UTC, nibinqtl commented on docs/edge-logic/faq.md
> +We modified the open-source NGINX to strictly follow the HTTP standard regarding 'zero-time cache'. When `no-cache` or `max-age=0` is present in the `Cache-Control` header field, the response is stil
Thanks, updated.

2021-04-09 20:21 UTC, nibinqtl commented on docs/edge-logic/faq.md
> +If the above mentioned default behavior is not meeting your requirement, you can use the following directives to alter it.
Thanks, updated.

2021-04-09 22:49 UTC, nibinqtl commented
@burtonquantil @marcfishelquantil , please take another look.

2021-04-10 00:36 UTC, burtonquantil approved these changes
OK to merge.

2021-04-10 01:00 UTC, merged