Document change for Release30Apr2021
mileweb/docs-content-cdn pull request #173
Opened 2021-04-24 01:18 UTC by nibinqtl

2021-05-08 05:45 UTC, nibinqtl commented
@burtonquantil or @marcfishelquantil , can you make a final review of this PR?

2021-05-10 01:44 UTC, burtonquantil requested changes
Just a couple of small suggestions.

2021-05-10 01:44 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +*   [$client_country_code](/cdn/docs/edge-logic/built-in-variables#client_country_code):  client’s ISO3166 country code
Replace "ISO3166" with "ISO 3166" .

2021-05-10 01:44 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +Turning it on allows a background subrequest to be fired to update an expired cache item, while a stale cached response is returned to the client. It should help with the responsiveness in serving po
The commas aren't necessary. 
Also, I'd change "in serving" to "when serving"

2021-05-10 02:07 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +*   [$client_country_code](/cdn/docs/edge-logic/built-in-variables#client_country_code):  client’s ISO3166 country code
fixed

2021-05-10 02:07 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +Turning it on allows a background subrequest to be fired to update an expired cache item, while a stale cached response is returned to the client. It should help with the responsiveness in serving po
Thanks, fixed.

2021-05-10 02:48 UTC, burtonquantil approved these changes
OK to merge

2021-05-10 04:30 UTC, merged