NCAS-2757 #comment added descriptions of API updates for sprint t 107…
mileweb/docs-content-cdn pull request #182
Opened 2021-05-25 19:37 UTC by burtonquantil

…, Release14May2021. These have been checked by QA

2021-06-04 00:56 UTC, nibinqtl requested changes
A few changes are needed.

2021-06-04 00:56 UTC, nibinqtl commented on apispec/openapi.json
> +                        "description": "Whether the API account can access the edge hostname management (/cdn/edgeHostnames) endpoints. By default, read-only API accounts can call the endpoints using
I think this is not correct. The operator API account should be able to see everything.

2021-06-04 00:56 UTC, nibinqtl commented on apispec/openapi.json
> +                        "description": "Whether the API account can access the edge hostname management (/cdn/edgeHostnames) endpoints. By default, read-only API accounts can call the endpoints using
Same problem for the fields below.

2021-06-04 00:56 UTC, nibinqtl commented on apispec/openapi.json
> +      "description": "Deployment is the process of pushing out your property and certificate configurations to the CDN360 cache servers. You have the option of deploying to a <i>staging</i> environme
We'd better provide a link to the documentation page about staging test, instead of maintaining the details here.

2021-06-04 01:01 UTC, burtonquantil commented on apispec/openapi.json
> +                        "description": "Whether the API account can access the edge hostname management (/cdn/edgeHostnames) endpoints. By default, read-only API accounts can call the endpoints using
@nibinqtl  I'm pretty sure this is what our current implementation is doing even though it sounds odd.  Refer to https://quantil.atlassian.net/browse/NCAS-2757?focusedCommentId=202333

2021-06-04 01:12 UTC, burtonquantil commented on apispec/openapi.json
> +      "description": "Deployment is the process of pushing out your property and certificate configurations to the CDN360 cache servers. You have the option of deploying to a <i>staging</i> environme
That's a good idea @nibinqtl .
However, I just found another reference related to staging. We had an API returning the list of IP addresses.
https://docs.cdnetworks.com/cdn/apidocs#operation/getStagingServers
The backward incompatible change we made to the staging IP address behavior means the above instructions aren't really usable as is.  A customer could use one that is for China only without realizing it.

2021-06-04 01:31 UTC, burtonquantil commented on apispec/openapi.json
> +      "description": "Deployment is the process of pushing out your property and certificate configurations to the CDN360 cache servers. You have the option of deploying to a <i>staging</i> environme
I'm thinking of replacing that text with:

 
> We highly recommend you <a href="https://docs.cdnetworks.com/cdn/docs/portal/edge-config\
> urations/testing-property">deploy to our <i>staging</i> environment to test your configurations before deploying to <i>production</i></a>.

This gets rid of the big heading <h2>Testing a staged property</h2>  though. What do you think?

2021-06-04 15:37 UTC, marcfishelquantil commented
These look good to me. /Marc

2021-06-04 18:47 UTC, burtonquantil commented on apispec/openapi.json
> +                        "description": "Whether the API account can access the edge hostname management (/cdn/edgeHostnames) endpoints. By default, read-only API accounts can call the endpoints using
Lijo explained the implementation. I will correct the text here.

2021-06-04 21:07 UTC, burtonquantil commented
@nibinqtl  Please check again as I made some updates.

2021-06-06 06:40 UTC, nibinqtl approved these changes
Good enough to see it in dev

2021-06-06 06:40 UTC, merged