Latest changes to be released by 6/25
mileweb/docs-content-cdn pull request #186
Opened 2021-06-19 06:53 UTC by nibinqtl

2021-06-24 00:15 UTC, burtonquantil requested changes
I made several suggestions.

The apispec/openapi.json included in this pull request does not cover Release25Jun2021. I have an open bug to work on that update.

2021-06-24 00:15 UTC, burtonquantil commented on docs/edge-logic/multiple-origins.md
> +```nginx
I suggest "For example, with the configuration below:" be rewritten as "For example, consider the following configuration:"

2021-06-24 00:15 UTC, burtonquantil commented on docs/edge-logic/multiple-origins.md
> +When both `header-a` and `header-b` are present in the request, only `has-header-b` will be added to the response. This is not a bug, just how NGINX works. But it can be confusing to new users.
I don't believe we should begin sentences with "But".
Perhaps rewrite as:
"This is not a bug, just how NGINX works, but this can be confusing to new users."

2021-06-24 00:15 UTC, burtonquantil commented on docs/edge-logic/multiple-origins.md
> +*   Due to the issue mentioned above, you are recommended to refrain from using any declarative directive in `if` blocks, unless there is no other way around. This makes the configuration more readab
- Since you referred to "people" which is indicates multiple individuals, "expert" should be "experts" .
-  Suggestion: "The example above can be rewritten as follows to achieve the desired result:"

2021-06-24 02:35 UTC, marcfishelquantil commented on docs/edge-logic/multiple-origins.md
> +```nginx
Some suggestions:
- Please change "of NGINX configuration" to "of the NGINX configuration."
- Please change "For example, try to understand" to "In particular, try to understand."
- Please change "They are executed in an early phase which is before most..." to "They are executed in an early phase, which precedes most ..." Note that this phrase appears twice above.
- To have the adverb appear properly at the end of the sentence, please change "...so you can easily tell them apart" to "...so you can tell them apart easily." Note that this phrase appears twice above.
-

2021-06-24 02:36 UTC, marcfishelquantil commented on docs/edge-logic/multiple-origins.md
> +When both `header-a` and `header-b` are present in the request, only `has-header-b` will be added to the response. This is not a bug, just how NGINX works. But it can be confusing to new users.
Please reword "This is not a bug, just how NGINX works. But it can be confusing to new users." to "This how NGINX works and is not a bug. However, this behavior can be confusing to new users."

2021-06-24 04:08 UTC, marcfishelquantil commented
Marc provided comments.

2021-06-24 07:00 UTC, nibinqtl commented
@marcfishelquantil did you hit "Close" by accident?

2021-06-24 07:11 UTC, nibinqtl commented
Updated, please take another look.

2021-06-24 21:34 UTC, burtonquantil approved these changes
OK to merge.  However, please note Marc merged his portal help updates related to Release25Jun2021 to dev.  He describes Secret Management.  We have not deployed this release to production yet.

2021-06-24 22:42 UTC, nibinqtl commented
OK. Lets release this right after we release the code.

2021-07-12 17:06 UTC, burtonquantil submitted a review, later dismissed
OK to merge

2021-07-12 17:06 UTC, burtonquantil commented on docs/edge-logic/multiple-origins.md
> +<a id="ifcaution"></a>This example uses the [`if` directive in the rewrite module](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#if) to check the value in the request header `x-origin` a
"conflict of" should be "conflict between"

2021-07-13 00:45 UTC, burtonquantil approved these changes
OK to merge.   Ele made a big pull request to duplicate the help text into cn and en subdirectories in order to investigate the possibility of supporting multiple languages that way. He said he needed these to test locally with Lijo. The production docs.cdnetworks.com should not be affected by these two new directories since docs-app doesn't refer to them yet.

2021-07-13 01:05 UTC, merged