Updates GUI screens and describes Secret, an unreleased feature.
mileweb/docs-content-cdn pull request #187
Opened 2021-06-22 17:40 UTC by marcfishelquantil

Although the Secret feature is not yet released, I am seeking feedback on my write-up from Bin and Burton. That way, when the Secret feature is released, the CDN360 help will be ready to be released with it.

2021-06-23 00:21 UTC, burtonquantil requested changes
Some changes are needed.

2021-06-23 00:21 UTC, burtonquantil commented on docs/portal/secrets/deleting-secrets.md
> +**Note:** Secrets can be deleted only by their owner.
I'm checking with @nibinqtl  about what he meant by "owner" in the Google document. I presumed that anybody with "administrator" portal or API credential or "operator" API credential could create or delete a secret.

2021-06-23 00:21 UTC, burtonquantil commented on docs/portal/secrets/deleting-secrets.md
> +1. In the left pane, click **Edge Configurations**, and then select **Secret**.
The menu item is now "Secrets"

2021-06-23 00:21 UTC, burtonquantil commented on docs/portal/secrets/editing-secrets.md
> +1. In the left pane, click **Edge Configurations**, and then select **Secret**.
That should be "Secrets"

2021-06-23 00:21 UTC, burtonquantil commented on docs/portal/secrets/querying-secrets.md
> +1. In the left pane, click **Edge Configurations**, and then select **Secret**.
"Secrets"

2021-06-23 00:21 UTC, burtonquantil commented on docs/portal/secrets/querying-secrets.md
> +**Note:** Secrets can be queried only by their owner or parent.
I think the use of "parent" here will confuse people.

I presume that if the secret is listed on the portal, then the customer can query it. Is this right @yusongliu8 ?
If so, I don't see a need to mention that here.

2021-06-23 00:21 UTC, burtonquantil commented on docs/portal/secrets/editing-secrets.md
> +**Note:** Secrets can be edited only by their owner.
@nibinqtl  Yusong said a reseller could impersonate and edit and view the secret. Is this expected behavior?

2021-06-23 21:34 UTC, marcfishelquantil commented on docs/portal/edge-configurations/comparing-properties.md
> +1. In the left pane, click **Edge Configurations**, and then select **Property**.
Fix made.

2021-06-23 21:35 UTC, marcfishelquantil commented on docs/portal/edge-configurations/comparing-properties.md
> +1. In the left pane, click **Edge Configurations**, and then select **Property**.
Fix made.

2021-06-23 21:36 UTC, marcfishelquantil commented on docs/portal/edge-configurations/creating-property.md
> +1. In the left pane, click **Edge Configurations**, and then select **Property**.
Fix made.

2021-06-23 21:44 UTC, marcfishelquantil commented on docs/portal/edge-configurations/deleting-property.md
> -# Deleting a Property
Fixed.

2021-06-23 21:45 UTC, marcfishelquantil commented on docs/portal/edge-configurations/deploying-property.md
> +1. In the left pane, click **Edge Configurations**, and then select **Property**.
Fixed.

2021-06-23 21:46 UTC, marcfishelquantil commented on docs/portal/edge-configurations/editing-properties.md
> +1. In the left pane, click **Edge Configurations**, and then select **Property**.
Fixed.

2021-06-23 21:46 UTC, marcfishelquantil commented on docs/portal/secrets/deleting-secrets.md
> +1. In the left pane, click **Edge Configurations**, and then select **Secret**.
Fixed.

2021-06-23 21:47 UTC, marcfishelquantil commented on docs/portal/edge-configurations/managing-origins.md
> +1. In the left pane, click **Edge Configurations**, and then select **Property**.
Fixed.

2021-06-23 21:49 UTC, nibinqtl commented on docs/portal/secrets/deleting-secrets.md
> +**Note:** Secrets can be deleted only by their owner.
@burtonquantil , in the API spec, the "owner" of a resource is consistently defined to be the "customer" who created the resource.

2021-06-23 21:50 UTC, marcfishelquantil commented on docs/portal/secrets/overview.md
> +A secret usually is a password that you intend to share. For example, a secret might be the secret key that is used to access your origin on AWS or an HMAC key that is used to authenticate client req
Thank you. I changed the text to read as follows: "Typically, a secret is a password a password that you share with CDNetworks in order for the CDN configuration to work."

2021-06-23 21:52 UTC, nibinqtl commented on docs/portal/secrets/editing-secrets.md
> +**Note:** Secrets can be edited only by their owner.
Yes. But we don't need to mention it here, because this is the default behavior of impersonation.

2021-06-23 21:54 UTC, marcfishelquantil commented on docs/portal/secrets/overview.md
> +Secrets are managed from the Secrets page. To display this page, click **Edge Configurations** in the left pane, and then select **Secret**.
Fixed.

2021-06-23 21:56 UTC, marcfishelquantil commented on docs/portal/secrets/creating-secrets.md
> +1. In the left pane, click **Edge Configurations**, and then select **Secret**.
Fixed.

2021-06-23 21:56 UTC, marcfishelquantil commented on docs/portal/secrets/creating-secrets.md
> +| Secret Name             | Enter a unique name that helps you identify this secret. The name is case sensitive and can be 30 characters long, and must not contain special characters such as ^ " ~ ,
I will stay tuned.

2021-06-23 21:57 UTC, marcfishelquantil commented on docs/portal/secrets/deleting-secrets.md
> +**Note:** Secrets can be deleted only by their owner.
I will stay tuned.

2021-06-23 21:58 UTC, marcfishelquantil commented on docs/portal/secrets/editing-secrets.md
> +1. In the left pane, click **Edge Configurations**, and then select **Secret**.
Fixed.

2021-06-23 21:59 UTC, marcfishelquantil commented on docs/portal/secrets/querying-secrets.md
> +**Note:** Secrets can be queried only by their owner or parent.
I deleted the note, but will stay tuned for a reply from yusong.

2021-06-23 22:10 UTC, burtonquantil commented on docs/portal/secrets/deleting-secrets.md
> +**Note:** Secrets can be deleted only by their owner.
@nibinqtl  The reason why I brought this up is that in the current public portal help, we only talk about ownership on the page about certificates.  https://docs.cdnetworks.com/cdn/docs/portal/certificates/overview#certificates-page
We offer the ability for resellers to share a certificate with child customers. I'm unaware that a reseller can share a secret with a child.

Also, my impression from speaking to @yusongliu8  yesterday is that a reseller can impersonate a child customer and make changes to the secrets. I presume that includes deleting the secret on behalf of the customer.  (I did not test this scenario yet.)

2021-06-23 22:16 UTC, burtonquantil commented on docs/portal/secrets/editing-secrets.md
> +**Note:** Secrets can be edited only by their owner.
@nibinqtl  OK I just made a lengthier response elsewhere about this type of statement.
Why do we bother saying the "secrets can be edited only by their owner" then?  Is there something about secret management that differs from property or edge hostname management?  
Certificates are shareable. Are secrets? If not, it seems like we don't need that line in the help.

2021-06-23 22:18 UTC, burtonquantil commented on docs/portal/secrets/overview.md
> +A secret usually is a password that you intend to share. For example, a secret might be the secret key that is used to access your origin on AWS or an HMAC key that is used to authenticate client req
@marcfishelquantil  Please re-read what you just wrote.  " is a password a password "  ?

2021-06-24 20:06 UTC, burtonquantil commented on docs/portal/secrets/deleting-secrets.md
> +**Note:** Secrets can be deleted only by their owner.
@marcfishelquantil  please remove the note about deletion by owners. Bin responded to me in the Google doc "I agree that we don't need highlight this for most of the resources. They are not relevant to customers."   That note is confusing even internally, in my opinion..

2021-06-24 20:07 UTC, burtonquantil commented on docs/portal/secrets/editing-secrets.md
> +**Note:** Secrets can be edited only by their owner.
@marcfishelquantil  Please remove the note about editing by the owner.  It is unnecessary and confusing.

2021-06-24 20:08 UTC, burtonquantil commented on docs/portal/secrets/querying-secrets.md
> +**Note:** Secrets can be queried only by their owner or parent.
@marcfishelquantil  A reseller can impersonate and query the secret.  You can delete the note.

2021-06-24 20:10 UTC, marcfishelquantil commented on docs/portal/secrets/editing-secrets.md
> +**Note:** Secrets can be edited only by their owner.
Got it, thank you. I removed this note from this topic.

2021-06-24 20:45 UTC, burtonquantil requested changes
I requested a couple of changes to clarify things.

2021-06-24 20:45 UTC, burtonquantil commented on docs/portal/secrets/overview.md
> +Typically, a secret is a password that you share with CDNetworks in order for the CDN configuration to work.
You should provide a more specific example like what Bin put in the Google doc.  Otherwise, customers may still not really understand why they might want use a secret.  Some customers will not have any requirement.

"For example, it could be a key used to authenticate client requests to your origin server.  By creating a secret and referring to it in your edge logic using the secret's name  via the syntax  $SECRET(secretName),  the key itself would not be exposed when viewing a property through our portal or fetching it using our API. "

2021-06-24 20:45 UTC, burtonquantil commented on docs/portal/secrets/creating-secrets.md
> +| Secret Name             | Enter a unique name that helps you identify this secret. The name is case sensitive and can be 30 characters long, and must not contain special characters such as ^ " ~ ,
@marcfishelquantil  We're planning to trim space characters at the beginning and end. However, spaces are permitted between non-space characters. I think you should add some comment explaining this.

2021-06-24 20:54 UTC, marcfishelquantil commented on docs/portal/secrets/overview.md
> +Typically, a secret is a password that you share with CDNetworks in order for the CDN configuration to work.
I added such a blurb based on your example. Thank you
.

2021-06-24 21:25 UTC, burtonquantil approved these changes
OK to merge.

2021-06-24 21:29 UTC, merged