For 7/9 release
mileweb/docs-content-cdn pull request #191
Opened 2021-07-15 09:00 UTC by nibinqtl

2021-07-24 03:34 UTC, nibinqtl commented
@burtonquantil @marcfishelquantil , is everything good enough to be released to public?

2021-07-24 22:49 UTC, burtonquantil requested changes
@nibinqtl I think you intended to refer to "proxy_set"?

2021-07-24 22:49 UTC, burtonquantil commented on docs/edge-logic/built-in-variables.md
> +| <span id="realtime_log_ds_ratio"></span><span class="var">$realtime_log_ds_ratio</span> |<span class="badge small" title="numerical value">#</span> RT log downsample ratio. The value should be 1/N,
I'd just write "The value should be a decimal number between 0 and 1".

2021-07-24 22:49 UTC, burtonquantil commented on docs/edge-logic/built-in-variables.md
> +| <span id="time_http"></span><span class="var">$time_http</span> | current time in RFC7231 format that can be used for HTTP Date header | <span class="badge green">Yes</span> | <span class="badge gr
I'd put a space between RFC and the number (i.e., "RFC 7231"), but it's minor.

2021-07-24 22:49 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +proxt_set $no_store 1 if ($upstream_response_status ~ 30[12]);
proxt_set doesn't look like a directive. Do you mean "proxy_set" ?

2021-07-26 18:06 UTC, marcfishelquantil commented
I agree with Burton's suggestion and did not spot other issues.

2021-07-28 14:50 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +proxt_set $no_store 1 if ($upstream_response_status ~ 30[12]);
fixed.

2021-07-28 14:52 UTC, burtonquantil approved these changes
ok to merge

2021-07-28 15:07 UTC, burtonquantil approved these changes
Looks good.  I presume all the /en pages are just Lijo and Eleazar's tests which aren't yet exposed to the public.

2021-07-28 15:10 UTC, merged