Burton ngdoc88
mileweb/docs-content-cdn pull request #196
Opened 2021-07-29 22:38 UTC by burtonquantil

I created these CDN360 release notes based on internal release notes.  I added some details including relevant links (primarily to internal documentation) ; cleaned up some text ; and removed some information not meant for public consumption.

2021-07-29 23:43 UTC, burtonquantil commented
@marcfishelquantil Please check this pull request for text issues.

2021-07-29 23:50 UTC, marcfishelquantil commented on docs/release-notes.md
> +## Feburary 11, 2021
Month is misspelled.

2021-07-29 23:51 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Added [slice_ignore_etag directive](</cdn/docs/edge-logic/supported-directives#slice_ignore_etag>) to disable ETag cnosistency check of sliced files.
consistency is misspelled.

2021-07-29 23:52 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Updated limit on purge reuests to a maximum of 1000 files and 5 directories at a time.
requests is misspelled.

2021-07-29 23:52 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Fixed issues issues in report API calls.
Delete one instance of issues.

2021-07-29 23:55 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Improved edge logic validation to ensure that nested location blocks have a content handler.
Do we want to capitalize Edge Logic here and throughout the RNs?

2021-07-30 00:05 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Updated [deployment](</cdn/apidocs#operation/createDeployment>) to support the Check-Certificate header to bypass checking of expired certificates and hostnames missing from the certificate’s SAN.
1. Please add commas between "testing" and "though."
2. Please add commas between "production" and "since."
3. Please change "since visitors would be discouraged by their browsers" to "since browsers would discourage visitors".

2021-07-30 00:06 UTC, burtonquantil commented on docs/release-notes.md
> +* Improved edge logic validation to ensure that nested location blocks have a content handler.
@marcfishelquantil  I personally wouldn't because it is not a trademarked or copyrighted name.  Other companies also refer to "edge logic".  If the product manager says it's a special phrase we must capitalize, then we can change it easily.

2021-07-30 00:07 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Added support for “operation” report annotations which CDNetworks may use to identify operational changes. We expect these to be infrequent.
Please change "which" to "that" because this is a restrictive clause.

2021-07-30 00:09 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Made API query parameters case insensitive for ease of use.
Not a biggie, but you might want to hyphenate "case-insensitive"

2021-07-30 00:55 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Required you to confirm if you try to delete a recently active hostname or edge hostname. This helps prevent accidental deletion of resources still used by visitors.
Should we replace "Required..." with "We now require,,,"?

2021-07-30 00:57 UTC, burtonquantil commented on docs/release-notes.md
> +* Required you to confirm if you try to delete a recently active hostname or edge hostname. This helps prevent accidental deletion of resources still used by visitors.
@marcfishelquantil  I had started every other line with something in past tense, so I kept that consistent here.

2021-07-30 01:24 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Added "Secret Management" feature so you can hide sensitive text from being exposed in edge logic. To access, click “Secrets” under the “Edge Configurations” menu item.
How about "Added a..."

2021-07-30 01:25 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Updated child customers’ [list of users](</cdn/apidocs#operation/getContacts>) to indicate if the users have full access to all products.
"to indicate whether users have"

2021-07-30 01:25 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Ensured an error is returned if one tries to create a property with duplicate hostnames.
Are we using "one" or "you"?

2021-07-30 01:26 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Improved the latency associated with real-time log implementation.
We improved the latency? I think we want to say "Reduced the latency..."

2021-07-30 01:38 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Added support for origin_host in the realtime log feature.
In some places, we hyphenate "real-time". We should be consistent.

2021-07-30 01:41 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Ensured the portal shows a property version as frozen once it is deployed.
Perhaps change the dangler "it" to "the property."

2021-07-30 01:54 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Added support for [custom API account permissions](</cdn/apidocs#tag/API-Account-Management>) giving you more control over who can access or update your configurations.
Please add a comma in front of "...giving you more"

2021-07-30 01:57 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Allowed validation of a frozen property. This may be necessary due to cache version changes which obsolete previously validated properties.
Please replace "which" with "that."

2021-07-30 02:00 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Prevented certificates with the same names from being created.
"name" instead of "names".

2021-07-30 02:12 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Added support for non-standard HTTP and HTTPS ports by specifying them in a extraServicePorts field of a property configuration. Also return extraServicePorts in the [system configuration API](</cd
Please change "which" to "that."

2021-07-30 02:16 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Updated [edge requests report](</cdn/apidocs#operation/getEdgeRequests>) to support Accept header with quality values.
"support the Accept header"

2021-07-30 03:42 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Updated portal's links to help pages.
You could just say "portal" instead of "portal's."

2021-07-30 03:50 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Changed real time logging format field to make it easier to use.
Here's a case where "real time" are 2 words. Because it is being used as a modifier of "logging format," it should be hyphenated. When used as a noun, it should be two words.

2021-07-30 03:51 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Fixed listing pages’ display issue for screens of different sizes.
Even though there are several listing pages, we could say "listing page" and remove the "s".

2021-07-30 03:52 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Added validate link to check Real Time Logging URL.
"validate" or "validation"?

2021-07-30 03:53 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Fixed display of cache hit ratio when origin traffic is larger than edge.
larger than edge what? Edge traffic?

2021-07-30 03:54 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Fixed support for protocol downgrade to only apply if the property has a certificate.
Please replace "to only apply if" with "to apply only if".

2021-07-30 03:55 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Allowed everyone to use the [proxy_buffering](</cdn/docs/edge-logic/supported-directives#proxy_buffering>) directive.
Should we replace "everyone" with "all users"?

2021-07-30 03:55 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Added support for sorting of properties, tasks, edge hostnames, accounts, and customers returned by APIs.
We can remove the preposition "of".

2021-07-30 03:55 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Improved stripping of comments in Edge Logic.
Here "Edge Logic" is capitalized. We should be consistent.

2021-07-30 03:56 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Added “operator” role which can administer CDN functions but not manage users and roles.
Please add a comma between ""operator"" and "which".

2021-07-30 03:56 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Made self signed certificate expire in 10 days.
"self signed" should be hyphenated.

2021-07-30 03:57 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Added support for real time logs (also known as download notification).
Please hyphenate +real time".

2021-07-30 03:58 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Let users confirm changes before deploying a property.
Should we replace "Let users confirm..." with "Allowed users to confirm...."?

2021-07-30 03:59 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Added support for getting the customer ID which owns various resources.
Please replace "which" with "that".

2021-07-30 04:00 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Added allowedCacheDirectives to control access to resource intensive NGINX directives.
Please hyphenate "resource intensive".

2021-07-30 04:00 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Changed real time logging format field to make it easier to use.
Please hyphenate "real time".

2021-07-30 04:01 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Added validate link to check Real Time Logging URL.
Please hyphenate "real time". Also, elsewhere "real time" is lower case. We should be consistent.

2021-07-30 04:01 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Improved validation for real time logging settings.
Please hyphenate "real time".

2021-07-30 04:01 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Updated portal documentation to describe real time logging feature and AWS authentication support.
Please hyphenate "real time".

2021-07-30 04:01 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Added support for real time logs (also known as download notification).
Please hyphenate "real time".

2021-07-30 04:02 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Trimmed realtime log format string.
Please hyphenate "real time".

2021-07-30 04:02 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Added support for origin_host in the realtime log feature.
Please hyphenate "real time".

2021-07-30 04:04 UTC, marcfishelquantil commented on docs/release-notes.md
> +* Limited the [realtime_log_downsample](</cdn/docs/edge-logic/supported-directives#realtime_log_downsample>) directive to the server block of edge logic.
Please hyphenate "realtime".

2021-07-30 17:10 UTC, burtonquantil commented on docs/release-notes.md
> +* Added support for origin_host in the realtime log feature.
@marcfishelquantil  I am removing the hyphen and adding a space since that's what merriam webster contains

2021-07-30 17:19 UTC, burtonquantil commented on docs/release-notes.md
> +* Added validate link to check Real Time Logging URL.
@marcfishelquantil  I'm changing to "Validate" because that is what appears in the portal.

2021-07-30 17:19 UTC, burtonquantil commented on docs/release-notes.md
> +* Changed real time logging format field to make it easier to use.
@marcfishelquantil  OK.. I have changed instances to be hyphenated throughout the document.

2021-07-31 02:14 UTC, marcfishelquantil approved these changes
I approve.

2021-08-03 08:15 UTC, ronyayoung requested changes
The rest of the

2021-08-03 08:15 UTC, ronyayoung commented on docs/release-notes.md
> +* Fixed [portal user list API](</apidocs#operation/getContacts>)'s handling of the ids query parameter.
Should the "ids query parameter" be "id query parameter"?

2021-08-03 15:24 UTC, burtonquantil commented on docs/release-notes.md
> +* Fixed [portal user list API](</apidocs#operation/getContacts>)'s handling of the ids query parameter.
@ronyayoung  No, it is "ids" in the Google doc https://docs.google.com/document/d/1ElMnkIqPA3MVA3FwHiWQWrZm4UiUenQCnpSHk7Ya-n0/edit#heading=h.lg31crd7tnc5  and that is what we implemented.

2021-08-03 15:24 UTC, burtonquantil commented
> The rest of the

@ronyayoung  Did you omit some text?

2021-08-05 15:53 UTC, ronyayoung commented on docs/release-notes.md
> +* Fixed [portal user list API](</apidocs#operation/getContacts>)'s handling of the ids query parameter.
@burtonquantil Got it.  It looks this item is related to the "Get List of Customers" API function in the CDN360 API Reference document.  Perhaps we want to use the API function corresponding to the document instead of using the "portal user list API".

2021-08-05 19:15 UTC, burtonquantil commented on docs/release-notes.md
> +* Fixed [portal user list API](</apidocs#operation/getContacts>)'s handling of the ids query parameter.
@ronyayoung  Sorry for the confusion. It is correct. This note is related to https://quantil.atlassian.net/browse/NCAS-2792  . Bin modified the Google doc spec to add an ids parameter to the portal user list API.
I'm waiting for the QA team to verify  http://cdn360doc.quantil.com/apidocs/beta/api.html#operation/getContacts
Then, I'll create a pull request for the docs-content-cdn repository.

2021-08-06 14:29 UTC, ronyayoung commented on docs/release-notes.md
> +* Fixed [portal user list API](</apidocs#operation/getContacts>)'s handling of the ids query parameter.
I see.  This is a new parameter added to the API.  
I don't have any other feedback on the release note.  They look good to me.

2021-08-06 14:29 UTC, ronyayoung commented on docs/release-notes.md
> +* Fixed [portal user list API](</apidocs#operation/getContacts>)'s handling of the ids query parameter.
I see.  This is a new parameter added to the API.  
I don't have any other feedback on the release note.  They look good to me.

2021-08-06 14:29 UTC, ronyayoung approved these changes

2021-08-06 17:59 UTC, merged