Changes per Release06Aug2021
mileweb/docs-content-cdn pull request #204
Opened 2021-08-19 20:18 UTC by marcfishelquantil

Please review these edits that correspond to Release06Aug2021.

2021-08-19 20:42 UTC, burtonquantil requested changes
There are several things that need to be fixed.

2021-08-19 20:42 UTC, burtonquantil commented on en/docs/portal/edge-configurations/editing-properties.md
> +**Note:** A lock icon next to the version number means the version has been deployed. Editing this version is not permitted and the **Edit** button changes to **Clone** to ensure that CDN360 can reli
The statement about the editing button changing is no longer appropriate.
This is true:
"Editing this version is not permitted to ensure that CDN360 can reliably roll back to any version that has been deployed."

2021-08-19 20:42 UTC, burtonquantil commented on en/docs/portal/edge-configurations/editing-properties.md
> +3. To change the name of the property before editing or cloning it, click the pencil icon to the right of the property name at the top of the form, enter the new name, and click the checkmark at the
It is unnecessary to click the pencil icon.  The user can just click on the property name itself to get a text field where he can change the name.

2021-08-19 20:42 UTC, burtonquantil commented on en/docs/portal/edge-configurations/validating-property.md
> +4. When a message says that the configuration has been validated and is ready to deploy, click **Deploy It**. When the Deployment Target dialog box appears, select whether to deploy to staging (defau
the reference to /docs/portal/certificates/standby-tasks.md is odd.
The link on https://docs.cdnetworks.com/cdn/docs/portal/edge-configurations/deploying-property to "standby queue" is also broken since it refers to a nonexistent page, https://docs.cdnetworks.com/cdn/docs/portal/certificates/standby-tasks

2021-08-19 20:58 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/editing-properties.md
> +**Note:** A lock icon next to the version number means the version has been deployed. Editing this version is not permitted and the **Edit** button changes to **Clone** to ensure that CDN360 can reli
Change made, thank you.

2021-08-19 21:02 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/editing-properties.md
> +3. To change the name of the property before editing or cloning it, click the pencil icon to the right of the property name at the top of the form, enter the new name, and click the checkmark at the
This is true, as I tested and confirmed this behavior as well. However, I felt the pencil was a good icon to cue users to. Nevertheless, I'll change this text accordingly: To change the name of the property before editing or cloning it, click the current name, enter the new name, and click the checkmark at the bottom right of the field in which you typed the name.

2021-08-19 21:23 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/validating-property.md
> +4. When a message says that the configuration has been validated and is ready to deploy, click **Deploy It**. When the Deployment Target dialog box appears, select whether to deploy to staging (defau
I moved the standby-task.md file into the Tasks topic, which seems more appropriate than where it was placed previously. I also corrected the links that point to the standby-task.md file from the "Deploying a Certificate" and "Deploying Your Property" topics.

2021-08-19 23:51 UTC, burtonquantil commented on en/docs/portal/edge-configurations/validating-property.md
> +4. When a message says that the configuration has been validated and is ready to deploy, click **Deploy It**. When the Deployment Target dialog box appears, select whether to deploy to staging (defau
As of 450PM Friday, the Validating a Property section still refers to </docs/portal/certificates/standby-tasks.md>).

2021-08-20 00:16 UTC, burtonquantil approved these changes
OK to merge.

2021-08-20 00:16 UTC, merged