sprint 118 changes
mileweb/docs-content-cdn pull request #241
Opened 2021-10-20 19:48 UTC by marcfishelquantil

I updated the English-language and Chinese topics to account for the revised roles implementation and the Purge Again button for content management. In a separate Word document, I noted for Keven the text and graphics changes in this push, so he can update the Chines topics accordingly.

2021-10-20 20:06 UTC, burtonquantil requested changes
Please address the issues I reported and request a review again.

2021-10-20 20:06 UTC, burtonquantil commented on en/docs/portal/content-management.md
> +   **Note:** When the purge completes, a **purge again** button at the bottom right allows you to repeat a purge.
The button is labeled "Purge Again" with capitalized words. I think our description should match.

2021-10-20 20:06 UTC, burtonquantil commented on en/docs/portal/identities-and-access/managing-roles.md
> +| Role Status          | Select between **Local** and **Remote**: <br><ul><li><strong>Local</strong> = only this customer account can use this role.</br></ul></li><ul><li><strong>Remote</strong> = al
Please remove this.
I thought I discussed before. At the moment, only our internal staff sees this option and can create a new role visible to other customers.  By the way, you wrote "Remote" which is not what I see on console-integration.cdnetworks.com.  I see "Global".  Are you actually seeing the word "Remote"?  Be sure to update your screenshot.

2021-10-20 21:36 UTC, marcfishelquantil commented on en/docs/portal/identities-and-access/managing-roles.md
> +| Role Status          | Select between **Local** and **Remote**: <br><ul><li><strong>Local</strong> = only this customer account can use this role.</br></ul></li><ul><li><strong>Remote</strong> = al
Per our Skype chat, I retained this parameter because I see it in console. However, I did change "Remote" to "Global."

2021-10-21 23:37 UTC, burtonquantil approved these changes
OK to merge

2021-10-21 23:38 UTC, merged