changes to be release to production by 11/5
mileweb/docs-content-cdn pull request #249
Opened 2021-10-28 13:11 UTC by nibinqtl

2021-11-05 21:42 UTC, burtonquantil requested changes
I made a few suggestions on wording. 
They are not critical.  At a minimum, replace "a.k.a." which is not a valid abbreviation or word.

2021-11-05 21:42 UTC, burtonquantil commented on en/docs/edge-logic/supported-directives.md
> +This directive allows you to add up to 2 customized fields into the access log. The id can be either 1 or 2. The value can contain variables. The 2 fields can be referred to by the keywords "custom1"
Minor: "The 2 fields" should be "The two fields"

2021-11-05 21:42 UTC, burtonquantil commented on en/docs/intro.md
> +CDN Pro is a platform we architected from scratch based on the latest technology and our 20+ years of practice in the content delivery industry. It is designed to give you unprecedented flexibility t
The sentence is valid English, but I prefer the word "experience" to "practice".  The word has different meanings. One is doing something over and over to get better at.  Yes, the new CDN is better, but I don't want to imply too much that the old system was poor. It is a real product that was effective as well.

@ronyayoung

2021-11-05 21:42 UTC, burtonquantil commented on en/docs/intro.md
> +The platform comes with a friendly yet powerful user interface that allows 100% self-service of even the most complicated delivery configurations. Its application programming interface (API) enables
Minor:  "to explore for the best trade-off between performance and cost."
I prefer:  "to balance performance and cost."
The word "trade-off" is certainly valid. It refers to balancing of things that cannot be attainable at the same time. To me, it has more negative connotations than "balance"... like you will  get good performance from our CDN only if you pay the most. This isn't necessarily true.  
@ronyayoung

2021-11-05 21:42 UTC, burtonquantil commented on en/docs/manifest.json
> +      "description": "CDN Pro (a.k.a. CDN360) leads the evolution of the industry by giving the content owners unprecedented flexibility to deliver their digital assets globally with the best possibl
I prefer "previously known as CDN360" which was used in the intro.md to "a.k.a. CDN360" . Not everyone will recognize that abbreviation. Also, it should have been written as "aka" if you really want to use that.

2021-11-06 07:01 UTC, nibinqtl commented
Updated. Please review again. @burtonquantil

2021-11-07 04:53 UTC, burtonquantil requested changes
made some additional suggestions.

2021-11-07 04:53 UTC, burtonquantil commented on en/docs/edge-logic/supported-directives.md
> +This directive allows you to add up to 2 customized fields into the access log. The id can be either 1 or 2. The value can contain variables. The two fields can be referred to by the keywords "custom
Minor: "2 customized fields" is better as "two customized fields"
"The two fields can be referred to by the keywords "custom1" and "custom2" when you configure the format of the download log or when using our advanced analytical tool"  could be written as
'Refer to the two fields using the keywords "custom1" and "custom2" when configuring the download log format or when using our advanced analytical tool.'

By the way, what exactly does "advanced analytical tool" refer to?

2021-11-07 04:53 UTC, burtonquantil commented on en/docs/intro.md
> +CDN Pro is a platform we architected from scratch based on the latest technology and our 20+ years of experience in the content delivery industry. It is designed to give you unprecedented flexibility
"These factors are important to keep the cost down and outages away."
"outages away" is not normal English.
Suggestion:  "This helps reduce costs and outages."
Alternative:  combine into one sentence...
"Under the hood, we made sure the system has a very clean structure that is easy to operate and extend in the future, thereby reducing costs and outages."

Marc might have other suggestions.

2021-11-07 04:53 UTC, burtonquantil commented on en/docs/intro.md
> +The platform comes with a friendly yet powerful user interface that allows 100% self-service of even the most complicated delivery configurations. Its application programming interface (API) enables
Instead of referring to "The platform" and "Its application programming interface", you could 
say "Our platform" and "Our application programming interface" since you do use the word "We" twice.

2021-11-07 06:17 UTC, nibinqtl commented on en/docs/edge-logic/supported-directives.md
> +This directive allows you to add up to 2 customized fields into the access log. The id can be either 1 or 2. The value can contain variables. The two fields can be referred to by the keywords "custom
updated.

2021-11-07 06:17 UTC, nibinqtl commented on en/docs/intro.md
> +CDN Pro is a platform we architected from scratch based on the latest technology and our 20+ years of experience in the content delivery industry. It is designed to give you unprecedented flexibility
Made some changes, but decided to keep "outages away"

2021-11-07 06:18 UTC, nibinqtl commented on en/docs/intro.md
> +The platform comes with a friendly yet powerful user interface that allows 100% self-service of even the most complicated delivery configurations. Its application programming interface (API) enables
Use "Our" for the first sentence.

2021-11-07 14:34 UTC, burtonquantil approved these changes
"outages away" is not English that would be written by people in the US, but we won't block the deployment for that.

2021-11-07 15:38 UTC, merged