NGDOC-121 updates
mileweb/docs-content-cdn pull request #259
Opened 2021-11-17 18:25 UTC by marcfishelquantil

These edits reflect the changes made to the HGDOC-121 release. The Chinese-language topics that got revised had not yet been translated. I welcome your comments.

2021-11-17 19:53 UTC, burtonquantil requested changes
I think we need to expand on the advanced filtering that we support now.

2021-11-17 19:53 UTC, burtonquantil commented on en/docs/portal/edge-configurations/creating-property.md
> +When you click the <b>Wizard</b> button, a prompt appears with the following choices. <ul><li><b>Start with a baseline setting for website acceleration</b>. Initializes settings for a typical website
for the second case, I suggest "Initializes settings to accelerate large file downloads or video on demand."

2021-11-17 19:53 UTC, burtonquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +| 1            | A search box for filtering properties by ID, name, description, or hostname. Multiple search strings can be separated by a tab or carriage return. Typing the carat character at the b
Our search is more powerful now. Our test engineer posted some examples of what she tried:
https://quantil.atlassian.net/browse/NCP-2355?focusedCommentId=226059
You can look at the API documentation for additional examples too https://docs.cdnetworks.com/en/cdn/apidocs#operation/createProperty mentions fields that could be referenced. I'm not sure the best way to present this. It is more advanced filtering.

2021-11-17 22:45 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/creating-property.md
> +When you click the <b>Wizard</b> button, a prompt appears with the following choices. <ul><li><b>Start with a baseline setting for website acceleration</b>. Initializes settings for a typical website
Change made.

2021-11-17 22:45 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +| 1            | A search box for filtering properties by ID, name, description, or hostname. Multiple search strings can be separated by a tab or carriage return. Typing the carat character at the b
I updated this in my second upload. Please review and provide feedback.

2021-11-17 23:02 UTC, burtonquantil requested changes
Need to improve.

2021-11-17 23:02 UTC, burtonquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +| hasConfig=hasBeian:true&hasConfig=realTimeLog	 | Returns only the properties that match all the values (<b>Has ICP Beian</b> setting is Yes and have real-time log is enabled).    |
In the API, we separate multiple hasConfig using the "&" character because it's on the URL.
In the portal, the user should enter  "hasConfig=hasBeian:true"  and then the Enter key followed by entering "hasConfig=realTimeLog" and another Enter. 
Please try it out.
You may also want to explicitly say the user can search for properties matching multiple settings by entering separate hasConfig fields or something like that.

2021-11-18 01:55 UTC, burtonquantil requested changes
I think there can still be some improvement. Also, some of the earlier feedback was not addressed  , in particular, my comments about fields 2 and 4  in the page.

2021-11-18 01:55 UTC, burtonquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +| 1            | A search box for filtering properties by ID, name, description, or hostname using one or more search strings. If you enter multiple search strings, separate each one with a carriage
" A search box for filtering properties by ID, name, description, or hostname using one or more search strings"
We're also supporting search by configuration setting, so I think this sentence should mention that.

2021-11-18 01:55 UTC, burtonquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +| 1            | A search box for filtering properties by ID, name, description, or hostname using one or more search strings. If you enter multiple search strings, separate each one with a carriage
"Filtering Properties" should be a link

2021-11-18 01:55 UTC, burtonquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +If you have many properties, use <b>hasConfig=<i><'value'></i></b> to find properties that match a specific configuration. In this advanced search string, <b><i><'value'></b></i> is a keyword support
link to the API help.
'In this advanced search string,'  sounds kind of strange.

2021-11-18 02:11 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +##Filtering Properties
Done.

2021-11-18 02:11 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +###Using the Carat
Done

2021-11-18 02:11 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +###Using hasConfig
Done

2021-11-18 02:13 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +| 2            | Check to display the children associated with the properties.  |
Done.

2021-11-18 02:18 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +| 4            | Icons to filter properties by Staging Version and Production Version.                            |
Done

2021-11-18 02:20 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +| 4            | Icons to filter properties by Staging Version and Production Version.                            |
Done

2021-11-18 02:22 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +| 1            | A search box for filtering properties by ID, name, description, or hostname. Multiple search strings can be separated by a tab or carriage return. For more information, see Filtering
Done

2021-11-18 02:23 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +| hasConfig=hasBeian:true&hasConfig=realTimeLog	 | Returns only the properties that match all the values (<b>Has ICP Beian</b> setting is Yes and have real-time log is enabled).    |
Done

2021-11-18 02:38 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +If you have many properties, use <b>hasConfig=<i><'value'></i></b> to find properties that match a specific configuration. In this advanced search string, <b><i><'value'></b></i> is a keyword support
I changed this to "In an advanced search string..."

2021-11-18 04:40 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +| 1            | A search box for filtering properties by ID, name, description, or hostname using one or more search strings. If you enter multiple search strings, separate each one with a carriage
All done.

2021-11-18 17:01 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +If you have many properties, use <b>hasConfig=<i><'value'></i></b> to find properties that match a specific configuration. In this advanced search string, <b><i><'value'></b></i> is a keyword support
Change made, Bin. Thank you.

2021-11-18 20:10 UTC, burtonquantil requested changes
Please review my feedback.

2021-11-18 20:10 UTC, burtonquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +| 2            | Appears only for resellers, allowing them to search the properties of their child customers.                |
I don't like the switch to '3rd person' .
This isn't a blocker though.

2021-11-18 20:10 UTC, burtonquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +| 4            | Icons to filter properties by Staging Version and Production Version.                                                 |
Your phrasing  implies the user can specify the version to filter by, but that's not true.
Did you actually try it?
When you click it, there is actually a checkbox. We're filtering based on whether the property is deployed to staging OR to production depending on which one is checked. it is not by 'version'.

2021-11-18 20:10 UTC, burtonquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +If you have many properties, use <b>hasConfig=<i><'configuration'></i></b> to find properties that match a specific configuration. In an advanced search string, <b><i><'configuration'></b></i> is a k
why don't you link to our API help?

2021-11-18 20:16 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +| 2            | Appears only for resellers, allowing them to search the properties of their child customers.                |
Very well. I will leave this as is.

2021-11-18 20:29 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +| 4            | Icons to filter properties by Staging Version and Production Version.                                                 |
I can see where this is confusing. Changed wording to "Icons to filter properties based on whether they have been deployed to staging or production."

2021-11-18 20:42 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +If you have many properties, use <b>hasConfig=<i><'configuration'></i></b> to find properties that match a specific configuration. In an advanced search string, <b><i><'configuration'></b></i> is a k
Done.

2021-11-18 23:18 UTC, burtonquantil approved these changes
OK to merge.

2021-11-18 23:19 UTC, merged