add the descriptions for the 5 new variables
mileweb/docs-content-cdn pull request #263
Opened 2021-11-29 09:47 UTC by Keven-Lin

Add the descriptions for the 5 new variables:
$request_end_time 
$turn_around_time 
$transfer_time 
$download_time 
$extra_deliver_time_ms

2021-11-29 18:01 UTC, yongguangbai requested changes
@Keven-Lin I believe you said Apple wanted to use the timing variables with millisecond. Please check my comments. Thanks.

2021-11-30 01:27 UTC, Keven-Lin commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="download_time"></span><span class="var">$download_time</span> |<span class="badge small" title="numerical value">#</span> the time from CDN Pro receives the client request to CDN Pro send
Yes cache support both transfer_time_ms and transfer_time. But it will be repetitive if we put them both in the document. So I just put transfer_time.
What Apple wants is transfer_time_ms, I will comment that we have another _ms variable

2022-01-13 07:01 UTC, nibinqtl commented on zh/docs/portal/accessing-portal/navigating-ui.md
> +默认菜单列出了您可以执行的 CDN Pro 活动。
”操作“比”活动“好

2022-01-13 07:01 UTC, nibinqtl commented on zh/docs/portal/accessing-portal/navigating-ui.md
> +## 仪表盘
页面实际用的是”信息中心“

2022-01-13 07:04 UTC, nibinqtl commented on zh/docs/portal/accessing-portal/navigating-ui.md
> +## 流量管理
”调度管理“

2022-01-13 07:06 UTC, nibinqtl commented on zh/docs/portal/accessing-portal/navigating-ui.md
> +## 异步任务
查看任务

2022-01-13 16:31 UTC, nibinqtl approved these changes

2022-01-13 16:31 UTC, nibinqtl commented on zh/docs/portal/accessing-portal/navigating-ui.md
> +默认菜单列出了您可以操作的 CDN Pro 活动。
应该改成：”您在 CDN Pro 上可以进行的操作“

2022-01-14 23:21 UTC, yongguangbai requested changes
Please check the inline comment. Thanks.

2022-01-14 23:21 UTC, yongguangbai commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="extra_deliver_time_ms"></span><span class="var">$extra_deliver_time_ms</span> |<span class="badge small" title="numerical value">#</span> the estimated time for cache buffer to send the w
in milliseconds is the correct grammar.

2022-01-19 08:23 UTC, Keven-Lin commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="extra_deliver_time_ms"></span><span class="var">$extra_deliver_time_ms</span> |<span class="badge small" title="numerical value">#</span> the estimated time for cache buffer to send the w
Thanks it has been updated to milliseconds

2022-01-20 18:15 UTC, yongguangbai approved these changes
Looks good to me.

2022-01-21 01:12 UTC, merged