Edits per NCP-2675 and NGDOC-126
mileweb/docs-content-cdn pull request #268
Opened 2021-12-16 21:15 UTC by marcfishelquantil

Kindly review and provide feedback.

2021-12-16 23:49 UTC, burtonquantil requested changes
Please review my comments.

2021-12-16 23:49 UTC, burtonquantil commented on en/docs/portal/content-management.md
> +| Purge Type | Select whether you want to purge a file, wildcard, or regular expression pattern used to match character combinations in strings ([0-9a-zA-Z_-]{1,28}). Default is file. <br><br><strong
Is the phrasing right?
When I read it, it is purge one of 3 things, but it doesn't really make sense to say "purge a wildcard" or "purge a regular expression pattern".
It may make more sense to say .. "Select whether you want to purge a single file, multiple cache entries matching a wildcard, or all entries matching a regular expression".
We should provide a more concrete example of a regular expression.
You can find one in the API doc
https://docs.google.com/document/d/155m9F0oFIDXRLeFmLqbdb0gWiHAyTWB8rPLWdRVGXoI/edit#heading=h.wl87jiasdj2w
There are more limitations in there that we should document in the portal help. I added to our API help.
I don't understand where you got this from: " character combinations in strings ([0-9a-zA-Z_-]{1,28})"  -

2021-12-16 23:49 UTC, burtonquantil commented on en/docs/portal/edge-configurations/creating-property.md
> +If you signed an agreement with CDNetworks for accessing the real-time log, use the **Real-Time Log** section to "stream" an access log in real time to your designated HTTP or HTTPS endpoint. You can
you have an extra period after "actual values in the notifications."

2021-12-16 23:58 UTC, marcfishelquantil commented on en/docs/portal/content-management.md
> +| Purge Type | Select whether you want to purge a file, wildcard, or regular expression pattern used to match character combinations in strings ([0-9a-zA-Z_-]{1,28}). Default is file. <br><br><strong
I adopted your comments. FYI, the character combination information I found in the apispec.

2021-12-17 07:54 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/creating-property.md
> +If you signed an agreement with CDNetworks for accessing the real-time log, use the **Real-Time Log** section to "stream" an access log in real time to your designated HTTP or HTTPS endpoint. You can
Fixed.

2021-12-20 20:03 UTC, burtonquantil requested changes
please update

2021-12-20 20:03 UTC, burtonquantil commented on en/docs/portal/content-management.md
> +**Note:** A parent can purge a child's domain without impersonation and should use the parent's purge quota.
The above line was a note copied directly from our development spec.  It was implemented for NCAS-2229 to help our partner Wangsu.    You should not mention "parent" because typical  customers will not understand the reference.     It's possible we could leave this note here but change "parent" to "reseller" :

> If you are a reseller, you can purge a child customer's domain. Your purge quota applies.

Try to learn our product and think about the context versus just copying everything verbatim.

2021-12-21 04:41 UTC, marcfishelquantil commented on en/docs/portal/content-management.md
> +**Note:** A parent can purge a child's domain without impersonation and should use the parent's purge quota.
Done.

2021-12-21 04:41 UTC, marcfishelquantil commented on en/docs/portal/content-management.md
> +When <code>tags</code> is specified, cached content with an Edge-Cache-Tag header whose value contains one of the tags will be purged.
Done.

2021-12-21 04:44 UTC, marcfishelquantil commented on en/docs/portal/content-management.md
> +| Purge Type | Select whether you want to purge a single file, multiple cache entries that match a wildcard, or all entries that match a regular expression. Default is file. For more information abou
Done. Also, created a link out of "Examples of Directory Purging" in the same table.

2021-12-21 19:22 UTC, burtonquantil approved these changes
OK to merge. We may actually permit more than 2 regex patterns, but we can edit the text later if necessary.

2021-12-21 19:27 UTC, merged