Added Load Balancer Logic
mileweb/docs-content-cdn pull request #289
Opened 2022-01-24 21:58 UTC by marcfishelquantil

I added new text and an updated screen shot of Advanced Settings to cover the new Load Balancer Logic option.

2022-01-24 22:30 UTC, burtonquantil requested changes
Please review my comments.

2022-01-24 22:30 UTC, burtonquantil commented on en/docs/portal/edge-configurations/creating-property.md
> +**Load Balancer Logic:** Enter Edge Logic to customize load balancing. You can use a subset of the directives, including `if`, `set`, `return`, `eval_func`, `add_header`, `client_max_body_size`, `den
I had suggested linking directly to the section on the system configuration API.
https://docs.cdnetworks.com/en/cdn/apidocs#operation/get-cdn-systemConfigs

2022-01-24 22:30 UTC, burtonquantil commented on en/docs/portal/edge-configurations/advanced-settings.md
> +| Has ICP Beian           | Specify whether all hostnames in this property have [Beian in China](</docs/edge-logic/faq.md#china-delivery-and-beian>). <ul><li>If **No** is selected, the CDN Pro proxy
> Note that you can set **Has ICP Beian** to **Yes** without contacting CDNetworks; however, the functionality <ins>**WILL NOT**</ins> be enabled until you request activation from CDNetworks.

I'm not sure it's necessary to include that.
However, if you want to mention something,  perhaps it could be simplified by:   "If you have ICP Beian, please contact  CDNetworks to enable the option to deploy to China-based servers."

2022-01-25 00:28 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/advanced-settings.md
> +| Has ICP Beian           | Specify whether all hostnames in this property have [Beian in China](</docs/edge-logic/faq.md#china-delivery-and-beian>). <ul><li>If **No** is selected, the CDN Pro proxy
I replaced my wording with yours, Burton. Thank you.

2022-01-25 00:42 UTC, burtonquantil requested changes
please check the links.

2022-01-25 00:42 UTC, burtonquantil commented on en/docs/portal/edge-configurations/advanced-settings.md
> +| Load Balancer Logic           | Enter Edge Logic to customize load balancing. You can use a subset of the directives, including `if`, `set`, `return`, `eval_func`, `add_header`, `client_max_body_si
I believe the link can just be  </apidocs#operation/get-cdn-systemConfigs>
Our system should automatically handle the "en" and "cdn"

2022-01-25 00:42 UTC, burtonquantil commented on en/docs/portal/edge-configurations/creating-property.md
> +**Load Balancer Logic:** Enter Edge Logic to customize load balancing. You can use a subset of the directives, including `if`, `set`, `return`, `eval_func`, `add_header`, `client_max_body_size`, `den
I believe the link can just be </apidocs#operation/get-cdn-systemConfigs>
Our system should automatically handle the "en" and "cdn"

2022-01-25 02:27 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/advanced-settings.md
> +| Load Balancer Logic           | Enter Edge Logic to customize load balancing. You can use a subset of the directives, including `if`, `set`, `return`, `eval_func`, `add_header`, `client_max_body_si
Changes made, thank you.

2022-01-25 03:09 UTC, burtonquantil approved these changes
good to merge

2022-01-25 03:19 UTC, merged