New log topic
mileweb/docs-content-cdn pull request #307
Opened 2022-03-01 20:31 UTC by marcfishelquantil

Please review new topic and provide feedback. Screenshots are TBD when Eleazar becomes available.

2022-03-01 23:21 UTC, burtonquantil requested changes
There are some errors in the text.

2022-03-01 23:21 UTC, burtonquantil commented on en/docs/manifest.json
> +                "title": "Managing Purge Requests",
Why does "Managing Purge Requests" appear under Reports?

2022-03-01 23:21 UTC, burtonquantil commented on en/docs/portal/reports/generating-reports.md
> -| Hostname | For Access Log Download reports, select a property hostname. Logs of visitors to the hostname will be generated for you to view and download.
I expect the Access Log Download report to be removed from the dropdown list under Reports-Charts since it is moved to Reports-Access Log. Do you intend to change  "https://docs.cdnetworks.com/en/cdn/docs/portal/reports"  Supported Report Types?

2022-03-01 23:21 UTC, burtonquantil commented on en/docs/portal/reports/generating-reports.md
> -| Edge Hostnames  | For Edge Hostname Request, select one or more edge hostnames.         |
why are you deleting these lines? We still have an Edge Hostname Request report.

2022-03-01 23:21 UTC, burtonquantil commented on en/docs/portal/reports/managing-logs
> +CDN Pro allows you to export logs that contain data from requests made to one or more hosts. Before you export logs, you must specify the format of the logs by creating a log configuration. Otherwise
"one or more hosts" is wrong.
Each log corresponds to a single hostname.
Suggestion
CDN Pro allows you to export logs showing requests made to a hostname.  Before you export logs, you must specify the format of the logs by creating a log configuration for the hostname. Otherwise, no logs will be available for exporting.

2022-03-01 23:21 UTC, burtonquantil commented on en/docs/portal/reports/managing-logs
> +2. In the top field, select one ore more hostnames. Separate multiple hostnames with a space or carriage return.
Change "ore more hostnames" to "hostname"
Remove the second sentence.
The user should only pick one hostname.

2022-03-01 23:21 UTC, burtonquantil commented on en/docs/portal/reports/managing-logs
> +<strong>Note:</strong> If no configurations match the specified hostname, a message asks whether you want to create a log configuration for the host name.
Change "host name" to "hostname"

2022-03-01 23:21 UTC, burtonquantil commented on en/docs/portal/reports/managing-logs
> +3. To edit a log configuration without viewing it first, click the ellipsis to the right of the log configuration, and then select **Edit**.<br>OR</br>To see a log before you edit it, click the log I
I prefer omitting  "To edit a log configuration without viewing it first," and "To see a log before you edit it,"  That  looks unnecessarily verbose. 

I suggest simplifying to something like:
"To edit a log configuration,  either click the ellipses to the right of the log configuration and choose Edit or open the log configuration and click the Edit button."

The same suggestion applies to the description of deletion below.

2022-03-01 23:29 UTC, marcfishelquantil commented on en/docs/portal/reports/generating-reports.md
> -| Hostname | For Access Log Download reports, select a property hostname. Logs of visitors to the hostname will be generated for you to view and download.
Yes, I will remove the Access Log Download report from the drop-down list under Reports > Charts.

2022-03-01 23:30 UTC, marcfishelquantil commented on en/docs/portal/reports/managing-logs
> +CDN Pro allows you to export logs that contain data from requests made to one or more hosts. Before you export logs, you must specify the format of the logs by creating a log configuration. Otherwise
Thanks. I changed my text to read as follows: CDN Pro allows you to export logs that show requests made to a hostname. Before you export logs, you must specify the format of the logs by creating a log configuration for the hostname. Otherwise, no logs will be available for exporting.

2022-03-01 23:31 UTC, marcfishelquantil commented on en/docs/portal/reports/managing-logs
> +2. In the top field, select one ore more hostnames. Separate multiple hostnames with a space or carriage return.
Done

2022-03-01 23:32 UTC, marcfishelquantil commented on en/docs/portal/reports/managing-logs
> +<strong>Note:</strong> If no configurations match the specified hostname, a message asks whether you want to create a log configuration for the host name.
Done

2022-03-01 23:35 UTC, marcfishelquantil commented on en/docs/portal/reports/managing-logs
> +3. To edit a log configuration without viewing it first, click the ellipsis to the right of the log configuration, and then select **Edit**.<br>OR</br>To see a log before you edit it, click the log I
Done

2022-03-01 23:38 UTC, marcfishelquantil commented on en/docs/manifest.json
> +                "title": "Managing Purge Requests",
Fixed

2022-03-01 23:45 UTC, marcfishelquantil commented on en/docs/portal/reports/generating-reports.md
> -| Edge Hostnames  | For Edge Hostname Request, select one or more edge hostnames.         |
Added it back.

2022-03-02 01:52 UTC, burtonquantil approved these changes
OK to merge.

2022-03-04 20:08 UTC, burtonquantil requested changes
[en/docs/resources/images/reports/configure-log2.png] can be more useful. This is something I'm asking Jungho to improve in our implementation.
What you can do in the interim is enter the default log format
https://docs.quantil.com/cdn/apidocs#operation/post-cdn-report-logConfigs
%cltip %rmtuser [%utctime] \"%method %url %protocol\" %statuscode %rspsize \"%referer\" \"%ua\" %rsptime

into the Log Format field. You will see how the Sample Record.
I think this would be useful to see.

2022-03-09 20:58 UTC, burtonquantil approved these changes
OK to merge.

2022-03-09 20:59 UTC, merged