NCP-2875 and the advanced property search
mileweb/docs-content-cdn pull request #319
Opened 2022-04-01 04:28 UTC by marcfishelquantil

Burton, please comment on the text and ignore missing or old GUI screenshots. I'll work with Eleazar on the screenshots.

2022-04-01 17:22 UTC, burtonquantil requested changes
Aside from updating images, you will also need to remove "Need this hostname to be resolved to edge servers in mainland China" in traffic-management/creating-edge-hostname

I see no Advanced Settings in edge hostnames.
Remove from https://docs.cdnetworks.com/en/cdn/docs/portal/traffic-management/creating-edge-hostname and https://docs.cdnetworks.com/en/cdn/docs/portal/traffic-management/editing-edge-hostname ?

2022-04-01 17:22 UTC, burtonquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +   <p align=center><img src="/docs/resources/images/edge-configurations/advanced-filter-icon.png" alt="advfilter icon" width="900"></p>
I don't see the image file in your pull request.

2022-04-01 17:22 UTC, burtonquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +| Add New +    | To search based on conditions, click **Add New +**. Select a field name and operand from the first two lists. If a value is required, enter it in the rightmost field. Click **Add New
Are you sure "operand" is the right word? That is something to be operated on.
We shouldn't use "operator"?

2022-04-01 17:22 UTC, burtonquantil commented on en/docs/portal/traffic-management/creating-edge-hostname.md
> +| Server Group      | If <strong>Action Type</strong> is set to <strong>Deliver</strong>, select one or more server groups to deliver the content for this client zone. CDN Pro servers are organized i
There are more than 5 server groups now.

ChinaBase and ChinaUltra are for those customers WITH ICP Beian license for their hostnames and want the content served from servers in China.
Only NearChina is for those without ICP Beian and want better performance.

2022-04-01 18:13 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +   <p align=center><img src="/docs/resources/images/edge-configurations/advanced-filter-icon.png" alt="advfilter icon" width="900"></p>
I made the text changes you noted above. The image you flagged is one I will need Eleazar to capture for me.

2022-04-01 21:55 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/managing-properties.md
> +| Add New +    | To search based on conditions, click **Add New +**. Select a field name and operand from the first two lists. If a value is required, enter it in the rightmost field. Click **Add New
Changed to "operator."

2022-04-01 22:24 UTC, marcfishelquantil commented on en/docs/portal/traffic-management/creating-edge-hostname.md
> +| Server Group      | If <strong>Action Type</strong> is set to <strong>Deliver</strong>, select one or more server groups to deliver the content for this client zone. CDN Pro servers are organized i
I made these changes, thank you.

2022-04-06 18:16 UTC, burtonquantil approved these changes
OK to merge.

2022-04-06 18:17 UTC, merged