Addresses NGDOC-150
mileweb/docs-content-cdn pull request #325
Opened 2022-04-12 14:55 UTC by marcfishelquantil

I added Authentication Certificate with a description and renamed Verify Origin to Verify Origin Certificate.

2022-04-12 23:25 UTC, burtonquantil requested changes
Let's simplify the text for verify origin certificate
Is there supposed to be a screenshot of the origin configuration dialog in https://docs.cdnetworks.com/en/cdn/docs/portal/edge-configurations/managing-origins
?

2022-04-12 23:25 UTC, burtonquantil commented on en/docs/portal/edge-configurations/managing-origins.md
> +| Authentication Certificate        |Select a certificate you want to use to authenticate with the origin server. The certificate must be created and deployed like other certificates. Because this ce
@marcfishelquantil  Let's get rid of the referenceto  the auto-renewed certificate and just point the user to https://docs.cdnetworks.com/en/cdn/docs/portal/certificates/creating-certificates#uploading-an-existing-certificate

The certificate must be uploaded and then deployed like other certificates.

uploaded can link to https://docs.cdnetworks.com/en/cdn/docs/portal/certificates/creating-certificates#uploading-an-existing-certificate


"deployed" should link to https://docs.cdnetworks.com/en/cdn/docs/portal/certificates/deploying-certificates

2022-04-13 00:07 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/managing-origins.md
> +| Authentication Certificate        |Select a certificate you want to use to authenticate with the origin server. The certificate must be created and deployed like other certificates. Because this ce
Good points. fixes made to the English- and Chinese-language files.

2022-04-13 00:20 UTC, burtonquantil approved these changes
OK to merge

2022-04-13 00:22 UTC, marcfishelquantil commented
Merging approved edits.

2022-04-13 00:22 UTC, merged