deploy recent updates to production
mileweb/docs-content-cdn pull request #334
Opened 2022-05-07 08:20 UTC by nibinqtl

2022-05-09 00:25 UTC, burtonquantil requested changes
I made a few suggestions.

I'll upload the updated CDN Pro OpenAPI spec on Monday to reflect our most recent deployment's changes.

2022-05-09 00:25 UTC, burtonquantil commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="request_uri"></span><span class="var">$request_uri</span> | request URI from the client, starting from '/' and with query string | <span class="badge green">Yes</span> | <span class="badg
I suggest "request URI from the client, beginning with '/' and including the query string"

2022-05-09 00:25 UTC, burtonquantil commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="uri"></span><span class="var">$uri</span> | [normalized](http://nginx.org/en/docs/http/ngx_http_core_module.html#location) request uri starting from '/' and without query string. The valu
I suggest  "request URI beginning with '/' and excluding the query string. "

2022-05-09 00:25 UTC, burtonquantil commented on en/docs/edge-logic/supported-directives.md
> +This directive allows the edge to serve staled content if it has not expired for too long to give the end user a better experience. It has the same functionality as the parameters `stale-if-error` an
Suggestion: This directive allows serving of stale content that did not expire too long ago to give the end user a better experience."

2022-05-09 03:03 UTC, nibinqtl commented
updated with Burton's suggestions

2022-05-09 04:23 UTC, burtonquantil requested changes
couple minor things.

2022-05-09 04:23 UTC, burtonquantil commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="request_uri"></span><span class="var">$request_uri</span> | request URI from the client, beginning with '/' and including query string | <span class="badge green">Yes</span> | <span class
I'd add "the" before "query string"

2022-05-09 04:23 UTC, burtonquantil commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="uri"></span><span class="var">$uri</span> | [normalized](http://nginx.org/en/docs/http/ngx_http_core_module.html#location) request uri beginning with '/' and excluding the query string. T
"uri" should be capitalized "URI"

2022-05-09 10:21 UTC, nibinqtl commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="uri"></span><span class="var">$uri</span> | [normalized](http://nginx.org/en/docs/http/ngx_http_core_module.html#location) request uri beginning with '/' and excluding the query string. T
fixed.

2022-05-09 21:24 UTC, burtonquantil approved these changes
OK to merge

2022-05-09 22:27 UTC, merged

2022-05-10 16:12 UTC, nibinqtl commented
It seems the production site is not showing the latest content?