NGDOC-134 added introduction to LB7 and ES
mileweb/docs-content-cdn pull request #342
Opened 2022-05-11 12:05 UTC by nibinqtl

And some other related changes on other pages.

2022-05-11 18:48 UTC, burtonquantil requested changes
Please check my suggestions.

2022-05-11 18:48 UTC, burtonquantil commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="request_cpu_time"></span><span class="var">$request_cpu_time</span> |<span class="badge small" title="numerical value">#</span> CPU time, in nanoseconds, spent on processing the request b
The commas around nanoseconds are probably not really necessary though it's OK.

@marcfishelquantil ?

2022-05-11 18:48 UTC, burtonquantil commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="qtl_cpu_cycle"></span><span class="var">$qtl_cpu_cycle</span> |<span class="badge small" title="numerical value">#</span> CPU Time in nanoseconds（1e-9s) spent in LB7, and in ES before tra
"Time" should be "time"

2022-05-11 18:48 UTC, burtonquantil commented on en/docs/edge-logic/declarative-imperative.md
> +## Declarative and Imperative Directives
Are you adding anything else to this file?

2022-05-11 18:48 UTC, burtonquantil commented on en/docs/edge-logic/lb7-es-structure.md
> +The edge network of CDN Pro consists of hundreds of nodes around the world and in each
How about this rewrite: "CDN Pro's edge network consists of hundreds of nodes around the world, each of which is a farm of physical server."

2022-05-11 18:48 UTC, burtonquantil commented on en/docs/edge-logic/lb7-es-structure.md
> +node is a farm of physical servers. To most efficiently utilize these servers, we need our design to meet the following criteria:
Suggestion:  "To most efficiently utilize these servers, our design satisfies the following criteria:"

2022-05-11 18:48 UTC, burtonquantil commented on en/docs/edge-logic/lb7-es-structure.md
> +'load' includes network bandwidth, CPU power and disk usage.
Minor:  I'd add a comma after "power"

2022-05-12 00:17 UTC, marcfishelquantil reviewed
Bin, I hope my comments help.

2022-05-12 00:17 UTC, marcfishelquantil commented on en/docs/edge-logic/built-in-variables.md
>  | <span id="download_time"></span><span class="var">$download_time</span> |<span class="badge small" title="numerical value">#</span> the time from CDN Pro receives the client request to CDN Pro send
May I suggest replacing "...the time from CDN Pro receives the client request to CDN Pro..." with "...the time from when CDN Pro receives the client request until CDN Pro..."

2022-05-12 00:17 UTC, marcfishelquantil commented on en/docs/edge-logic/built-in-variables.md
>  If you use the CDN Pro portal to edit the property, the autocompletion feature will list all the supported variables if you type `$` at a position where a variable is allowed.
How about rewording this to: "If you use the CDN Pro portal to edit the property, typing `$` at a position where a variable is allowed will list all the supported variables"

2022-05-12 00:17 UTC, marcfishelquantil commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="request_cpu_time"></span><span class="var">$request_cpu_time</span> |<span class="badge small" title="numerical value">#</span> CPU time, in nanoseconds, spent on processing the request b
@burtonquantil Please let's retain the commas.

2022-05-12 00:17 UTC, marcfishelquantil commented on en/docs/edge-logic/lb7-es-structure.md
> +The edge network of CDN Pro consists of hundreds of nodes around the world and in each
@burtonquantil In your suggested rewrite, should "physical server" be plural (physical servers)?

2022-05-12 00:35 UTC, burtonquantil commented on en/docs/edge-logic/lb7-es-structure.md
> +The edge network of CDN Pro consists of hundreds of nodes around the world and in each
@marcfishelquantil  yes..

2022-05-12 04:36 UTC, nibinqtl commented on en/docs/edge-logic/declarative-imperative.md
> +## Declarative and Imperative Directives
This is a placeholder where I plan to add content in the future

2022-05-12 04:46 UTC, nibinqtl commented
Thanks. just addressed all your comments.

2022-05-12 05:14 UTC, burtonquantil requested changes
You didn't respond to a few of my earlier suggestions.
I didn't see any comment from Marc saying they were incorrect suggestions.

2022-05-12 05:14 UTC, burtonquantil commented on en/docs/edge-logic/lb7-es-structure.md
> +2. For cacheable objects, avoid caching duplicated copies in the same farm.
@nibinqtl any reason why this shouldn't be "duplicate"?

2022-05-12 05:14 UTC, burtonquantil commented on en/docs/edge-logic/lb7-es-structure.md
> +<p align=center src=“https://docs.google.com/drawings/d/1Q-UdhK7w5Yzkjg53NTlzYAzKOOBmW_Rou5IgdGvl7-s/edit”><img src="/docs/edge-logic/lb7-es-structure.png" alt="Node Logical Structure" width="600"></
@nibinqtl  Any reason why we point to your Google doc? It seems unnecessary.

2022-05-12 05:14 UTC, burtonquantil commented on en/docs/edge-logic/lb7-es-structure.md
> +based on a consistent hash algorithm and the hash key involves the request URI and a [customizable](/docs/portal/edge-configurations/creating-property#advanced-settings)
@nibinqtl suggested change not accepted?

2022-05-12 05:14 UTC, burtonquantil commented on en/docs/edge-logic/lb7-es-structure.md
> +the LB7 than in the ES. If a request can be responded in
@nibinqtl  how about the above suggestion?s

2022-05-12 08:40 UTC, nibinqtl commented on en/docs/edge-logic/lb7-es-structure.md
> +<p align=center src=“https://docs.google.com/drawings/d/1Q-UdhK7w5Yzkjg53NTlzYAzKOOBmW_Rou5IgdGvl7-s/edit”><img src="/docs/edge-logic/lb7-es-structure.png" alt="Node Logical Structure" width="600"></
this reminds people (including myself) where to find the source of the image in case we need to change it in the future.

2022-05-12 08:41 UTC, nibinqtl commented
It looks not all comments are displayed on the "Conversation" tab...

2022-05-12 19:39 UTC, burtonquantil approved these changes
OK to merge

2022-05-12 22:59 UTC, merged