Chinese language screenshots
mileweb/docs-content-cdn pull request #343
Opened 2022-05-11 18:23 UTC by marcfishelquantil

Please confirm these are satisfactory. There were a few screens, such as password reset, that I could not capture.

2022-05-11 19:12 UTC, burtonquantil requested changes
1) Your pull request has conflicts.
2) You're changing more than just the images.
3) You still refer to filenames with zh in them.  This shouldn't be necessary

2022-05-12 04:49 UTC, nibinqtl commented on en/docs/manifest.json
> +            },
This seems to be a unmatched closing brace.

2022-05-12 04:49 UTC, nibinqtl requested changes

2022-05-12 04:49 UTC, nibinqtl commented on zh/docs/manifest.json
> +            },
This seems to be a unmatched closing brace.

2022-05-12 04:51 UTC, burtonquantil commented on zh/docs/manifest.json
> +            },
@nibinqtl  i expect Marc will close this pull request. It has a lot of problems. I talked to him about creating a new pull request starting with a clean copy of the repository.

2022-05-12 15:31 UTC, marcfishelquantil commented
I am closing this pull request and will generate a new one when posting the latest files and English and Chinese screen shorts to a new branch.

2022-05-12 15:31 UTC, closed without merging