Updated screenshots
mileweb/docs-content-cdn pull request #347
Opened 2022-05-16 22:33 UTC by marcfishelquantil

Updated one English screen shot and added 2 Chinese screen shots that were mistakenly shown in English.

2022-05-17 14:43 UTC, nibinqtl requested changes
@marcfishelquantil , almost all the screenshots you made have these 2 common problems:
1. The resolution is much lower than the original ones. For example, this picture: zh/docs/resources/images/edge-configurations/property-versions.png, the original one has 1940x364 pixels. Yours has only 801x170
2. The size of the text in the picture is proportionally too small. They are really hard to read.
I think you need to redo all the images.

2022-05-18 19:47 UTC, marcfishelquantil commented
@nibinqtl  Bin thank you for your suggestion. Yesterday, Eleazar tried your suggestion, among others. The results were less than satisfactory. He and I confirmed that my graphics card supports the required higher resolution needed to capture crisp screen shots, but that my monitor is the limiting factor. Thous high-res, it cannot reach the 4k resolution needed to capture acceptable screen shots. To rectify this situation, I have identified three 4k monitors and will check availability my Wednesday. I'll provide an update accordingly, as I realize I need to be able to accommodate this requirement to be as helpful as possible to the company.

2022-05-20 01:20 UTC, burtonquantil requested changes
Please make an adjustment to the help about annotations.

2022-05-20 01:20 UTC, burtonquantil commented on zh/docs/portal/reports/generating-reports.md
> +| Annotation Type | Select the type of annotation you want to add.<ul><li> <strong>Client</strong> = an event affecting clients, such as the release of a popular game.</ul></li><ul><li><strong>Config
@marcfishelquantil  please do not mention "superusers".
The customer cannot create the Operation annotation. It will not be an option for them, so it should be omitted from this section.
It can be referenced in your description of the reports page showing annotations. In that case, you can also mention something like:
"Annotations created by CDNetworks to indicate operations events may also appear in your reports."

2022-05-20 01:28 UTC, marcfishelquantil commented on zh/docs/portal/reports/generating-reports.md
> +| Annotation Type | Select the type of annotation you want to add.<ul><li> <strong>Client</strong> = an event affecting clients, such as the release of a popular game.</ul></li><ul><li><strong>Config
@burtonquantil Thank you for pointing this out. I revised the definition for Annotation Type accordingly.

2022-05-20 21:38 UTC, burtonquantil approved these changes
OK to merge

2022-05-20 21:47 UTC, merged