Merge recent updates to master
mileweb/docs-content-cdn pull request #348
Opened 2022-05-18 16:36 UTC by nibinqtl

2022-05-18 16:40 UTC, nibinqtl reviewed
@marcfishelquantil , almost all pictures you merged to dev has the same "text too small" issue. Please try to recapture with larger text.

2022-05-18 16:41 UTC, nibinqtl reviewed
@marcfishelquantil , almost all pictures you merged to dev has the same "text too small" issue. Please try to recapture with larger text.

2022-05-21 17:35 UTC, burtonquantil requested changes
I made a few suggestions.

2022-05-21 17:35 UTC, burtonquantil commented on en/docs/edge-logic/declarative-imperative.md
> +Nginx supports conditions to be specified by the `location` and `if` directives. In addition, CDN Pro introduced `elseif` and `else` for more flexibility. The pair of curly braces following each of t
there seems to be an extraneous apostrophe after "levels"

2022-05-21 17:35 UTC, burtonquantil commented on en/docs/edge-logic/declarative-imperative.md
> +When a client request comes in, nginx first tries to determine a context for request, then apply the corresponding flat configuration to the remaining processing workflow, just like how the waiter co
slight edit....  "...   to determine a context for **the** request, then **applies** ...."

2022-05-21 17:35 UTC, burtonquantil commented on en/docs/edge-logic/declarative-imperative.md
> +1. Among all the matching `if` blocks, the last one is picked. Nginx does not merge configurations dynamically so the declarative directives in the other `if` blocks are ignored;
Would this sound better as the first sentence of #1?
"If there are multiple matching `if` blocks, pick the last one."
and for #2.  "If there are multiple matching `location blocks`, pick one based on this [precendence]...

2022-05-21 17:35 UTC, burtonquantil commented on en/docs/edge-logic/declarative-imperative.md
> +3. `location` blocks have higher precedence than the "if" blocks.
is there a reason to switch between use of  the ` character versus the " character around   "if" ?

2022-05-21 17:35 UTC, burtonquantil commented on en/docs/edge-logic/declarative-imperative.md
> +In principle, users do not need to care about the time when each declarative directive is executed. But having some knowledge about the timing can help you to avoid some common mistakes. In fact, the
I'd combine the first two sentences with a comma instead of starting the sentence with "But".
For example,   " ... is executed, but having some knowledge..."

2022-05-21 17:35 UTC, burtonquantil commented on en/docs/edge-logic/declarative-imperative.md
> +A mistake often made by new users is attempting to put `$upstream_*` variables in the condition of an `if` directive, hoping to alter the behavior based on the origin's response. However, the `if` di
In the last sentence, I think you meant:   
"...this is how to force **removal of** the..."    ?

2022-05-21 17:35 UTC, burtonquantil commented on en/docs/edge-logic/declarative-imperative.md
> +The support of variables is a powerful feature of nginx. Some of the variables are continuously updated during the request processing workflow. The value seen by each directive depends on its executi
I suggest beginning with:   "Support for variables is a powerful feature of nginx."  and  "updated continuously" instead of "continuously updated"

Also change, "request is received" to "request was received"

2022-05-21 17:35 UTC, burtonquantil commented on en/docs/edge-logic/declarative-imperative.md
> +New users may be surprised to see different values in the two response header fields. This is because `set` is executed early in the workflow so it gets an earlier snapshot of `$request_time` and sav
I'd add a comma after "early in the workflow" and another one after "... to the client".

2022-05-21 17:35 UTC, burtonquantil commented on en/docs/edge-logic/simple-caching.md
> +One thing you might have noticed is the support of comments in the Edge Logic, which we believe is important for managing complicated configurations. In this code snippet, there are two "[location](h
I prefer "complex" to "complicated"

2022-05-21 17:35 UTC, burtonquantil commented on en/docs/edge-logic/simple-caching.md
> +Based on the description of the directive in the [official NGINX documentation](http://nginx.org/en/docs/http/ngx_http_core_module.html#location), the regex matching has higher priority than the pref
I'd start the second sentence with "Therefore, all the matching file types.."
It's odd to begin a sentence with "So"

I recommend "handled by" instead of "handled with"

2022-05-21 17:35 UTC, burtonquantil commented on en/docs/edge-logic/simple-caching.md
> +*   [`proxy_cache_valid`](</docs/edge-logic/supported-directives.md#proxy_cache_valid>) – this directive is the standard NGINX way of specifying cache time for objects without caching instructions fr
Here, you capitalized NGINX. Elsewhere, in the pull request, you used "nginx".

2022-05-21 17:35 UTC, burtonquantil commented on en/docs/edge-logic/supported-directives.md
> +* `consistent_hash` : Another way to distribute the origin traffic, based on hash value of the URL. If the origin server has cache, this option should help with the hit ratio.
should it say "If the origin server has **a** cache" ?

2022-05-21 17:35 UTC, burtonquantil commented on en/docs/edge-logic/supported-directives.md
> +* `sorted_list` : Select the peer based on the probed network quality. When the origin peers are geographically distributed (such as another CDN), this option should be helpful to ensure consistent p
".... this option should help ensure consistent performance."

2022-05-22 23:34 UTC, burtonquantil requested changes
i noticed one grammar error.

2022-05-22 23:34 UTC, burtonquantil commented on en/docs/edge-logic/declarative-imperative.md
> +Declarative and imperative are two different programming paradigms. Many good articles can [be found on the internet](https://www.google.com/search?q=imperative+declarative) about this topic. In summ
"a imperative "  should be "an imperative"

2022-05-22 23:34 UTC, burtonquantil commented on en/docs/edge-logic/multiple-origins.md
> +When both `header-a` and `header-b` are present in the request, only `has-header-b` will be added to the response. This is not a bug, just how NGINX works. However, this behavior can be counterintuit
"...just how NGINX works."  - we should use capitalized NGINX or lowercase nginx consistently.

2022-05-23 00:35 UTC, nibinqtl commented on en/docs/edge-logic/declarative-imperative.md
> +Declarative and imperative are two different programming paradigms. Many good articles can [be found on the internet](https://www.google.com/search?q=imperative+declarative) about this topic. In summ
It seems "their respective ... " is a very common paradigm:
https://www.merriam-webster.com/dictionary/respective

2022-05-23 03:56 UTC, marcfishelquantil reviewed
Bin, thank you for allowing me to review your content. Please let me know whether you have questions about them.

2022-05-23 03:56 UTC, marcfishelquantil commented on en/docs/edge-logic/declarative-imperative.md
> +Let's return to the coffee ordering example. Suppose you also tell the waiter "add milk only if it's from brand M." An experienced waiter should know the milk inventory and based on the availability
Sentence 1: please change "tell the waiter "add milk only" to "tell the waiter to add milk only..." and remove the quotation marks.
Sentence 2, please insert a comma after "and". 
Also, please replace "give a "flat" instruction "make a cup of coffee with sugar and milk" or "make a cup of coffee with sugar only" to the staff behind the counter." with "give a "flat" instruction to the staff behind the counter to make a cup of coffee with sugar and milk or with sugar only".

2022-05-23 03:56 UTC, marcfishelquantil commented on en/docs/edge-logic/declarative-imperative.md
> +Nginx supports conditions to be specified by the `location` and `if` directives. In addition, CDN Pro introduced `elseif` and `else` for more flexibility. The pair of curly braces following each of t
Last sentence: please add the word "the" between "in" and "case".

2022-05-23 03:56 UTC, marcfishelquantil commented on en/docs/edge-logic/declarative-imperative.md
> +When a client request comes in, nginx first tries to determine a context for the request, then applies the corresponding flat configuration to the remaining processing workflow, just like how the wai
Sentence 1: please change "nginx" to "Nginx".
Same sentence: please replace "just like how the" with "in a way similar to how the".

2022-05-23 03:56 UTC, marcfishelquantil commented on en/docs/edge-logic/declarative-imperative.md
> +Rule #1 above is probably the most confusing nginx behavior to new users since it is different from most other programming languages. We have some suggestions [on this page](multiple-origins) regardi
Sentence 1: please change "nginx" to "Nginx". 
Sentence 2: please change "regarding how to deal with it" to "about how to work with this rule".

2022-05-23 03:56 UTC, marcfishelquantil commented on en/docs/edge-logic/declarative-imperative.md
> +In principle, users do not need to care about the time when each declarative directive is executed, but having some knowledge about the timing can help you to avoid some common mistakes. In fact, the
Sentence 1: the words "to" and "some" are not necessary and can be removed.
Sentence 2: please replace "figured out" with "determined" or "ascertained". Also, please replace "sketched" with "described".

2022-05-23 03:56 UTC, marcfishelquantil commented on en/docs/edge-logic/declarative-imperative.md
> +People who are familiar with imperative programming often forget that the place a declarative directive appears in the configuration does not affect its execution time. Consider the following configu
Sentence 1: please replace "People" with "Programmers." Please delete the words "who are". Please consider changing "often" to "might". Please replace "the place" with "the location where".

2022-05-23 03:56 UTC, marcfishelquantil commented on en/docs/edge-logic/declarative-imperative.md
> +Although the access control directives `allow` and `deny` are placed at the server level before the `location` blocks, they are still executed after the location context is determined for the request
Sentence 1: please delete the word "still". Because the sentence has 2 instances of "after," consider replacing the first instance with "following" or the "which is after" with "which follows".

2022-05-23 03:56 UTC, marcfishelquantil commented on en/docs/edge-logic/declarative-imperative.md
> +Support of variables is a powerful feature of nginx. Some of the variables are updated continuously during the request processing workflow. The value seen by each directive depends on its execution t
Sentence 1: please change "nginx" to "Nginx".
Sentence 2: please delete the words "of the".

2022-05-23 03:56 UTC, marcfishelquantil commented on en/docs/edge-logic/multiple-origins.md
> +When both `header-a` and `header-b` are present in the request, only `has-header-b` will be added to the response. This is not a bug, just how nginx works. However, this behavior can be counterintuit
Sentence 2: please change "just how nginx works" to "but rather how Nginx works".

2022-05-23 03:56 UTC, marcfishelquantil commented on en/docs/edge-logic/multiple-origins.md
>  *   Not all directives can be used in an `if` block. This is documented in the "Context" of each directive. For the ones not allowed in an `if` block, if they support variable as parameter, you can s
Sentence 2: please consider replacing:

"For the ones not allowed in an `if` block, if they support variable as parameter, you can still control their behavior based on `if` conditions using the [`set`](</docs/edge-logic/supported-directives.md#set>) directive." 

with:

"If the directives that are not allowed in an `if` block support variable as parameter, you can control their behavior based on `if` conditions using the [`set`](</docs/edge-logic/supported-directives.md#set>) directive."

2022-05-23 03:56 UTC, marcfishelquantil commented on en/docs/edge-logic/multiple-origins.md
> +*   Due to the issues mentioned above, you are recommended to refrain from using any declarative directive in `if` blocks, unless there is no other way around. This makes the configuration more reada
Sentence 1: please change "unless there is no other way around" to "unless there is no alternative".
Sentence 2: please change "nginx" to "Nginx".

2022-05-23 03:56 UTC, marcfishelquantil commented on en/docs/edge-logic/simple-caching.md
> +*   [`proxy_cache_valid`](</docs/edge-logic/supported-directives.md#proxy_cache_valid>) – this directive is the standard nginx way of specifying cache time for objects without caching instructions fr
Please replace "nginx" and "NGINX" with "Nginx".

2022-05-23 03:56 UTC, marcfishelquantil commented on en/docs/edge-logic/simple-caching.md
>  *   [`proxy_cache_min_age`](</docs/edge-logic/supported-directives.md#proxy_cache_min_age>)  – this is a CDN Pro-proprietary directive that takes one parameter. If the "max-age" value from origin is
Please remove the hyphen between "Pro" and "proprietary".

2022-05-23 03:56 UTC, marcfishelquantil commented on en/docs/edge-logic/simple-caching.md
>  *   [`origin_pass`](</docs/edge-logic/supported-directives.md#origin_pass>) – this is another proprietary directive to access the origin. It is a wrapper of NGINX’s "[proxy_pass](http://nginx.org/en/
Please change "NGINX" to "Nginx".

2022-05-23 03:56 UTC, marcfishelquantil commented on en/docs/edge-logic/supported-directives.md
> +* `round_robin` : Rotate all the peers sequentially. This is the default setting which tries to evenly distribute the origin traffic on all the peers.
Sentence 2: either add a comma before "which" or consider the following:  "Evenly distributes the origin traffic on all peers. This is the default setting."

2022-05-23 03:56 UTC, marcfishelquantil commented on en/docs/edge-logic/supported-directives.md
> +* `consistent_hash` : Another way to distribute the origin traffic, based on hash value of the URL. If the origin server has a cache, this option should help with the hit ratio.
Please change "Another way to distribute the origin traffic, based on hash value of the URL." to "Distributes the origin traffic based on the hash value of the URL. "

2022-05-23 03:56 UTC, marcfishelquantil commented on zh/docs/edge-logic/declarative-imperative.md
> +Declarative and imperative are two different programming paradigms. Many good articles can [be found on the internet](https://www.google.com/search?q=imperative+declarative) about this topic. In summ
Kindly see my comments above.

2022-05-23 03:56 UTC, marcfishelquantil commented on en/docs/edge-logic/declarative-imperative.md
> +1. If there are mutiple matching `if` blocks, pick the last one. Nginx does not merge configurations dynamically so the declarative directives in the other `if` blocks are ignored;
Sentence 1: please change "mutiple" to "multiple".

2022-05-23 08:58 UTC, nibinqtl commented on en/docs/edge-logic/declarative-imperative.md
> +Declarative and imperative are two different programming paradigms. Many good articles can [be found on the internet](https://www.google.com/search?q=imperative+declarative) about this topic. In summ
About sentence 6, I need to keep the quotation. Because it is important to emphasize the exact order given to the waiter.

2022-05-23 08:58 UTC, nibinqtl commented on en/docs/edge-logic/declarative-imperative.md
> +Let's return to the coffee ordering example. Suppose you also tell the waiter "add milk only if it's from brand M." An experienced waiter should know the milk inventory and based on the availability
I need to keep the quotation marks. Because it is important to emphasize the exact order given to the waiter.

2022-05-23 22:04 UTC, burtonquantil requested changes
fix one spelling error.

2022-05-24 00:54 UTC, burtonquantil approved these changes
OK to merge

2022-05-24 02:20 UTC, merged