added an example in proxy_cache_valid on system level inheritance; ad…
mileweb/docs-content-cdn pull request #419
Opened 2022-10-05 05:04 UTC by ronyayoung

…ded near china info in zh faq file

2022-10-07 04:19 UTC, nibinqtl requested changes

2022-10-07 04:19 UTC, nibinqtl commented on zh/docs/edge-logic/faq.md
> +如果您的CDN域名没有ICP备案，但仍然需要加速并分发内容到中国大陆，CDN Pro 为您提供了Near China专线的解决方案。 这个解决方案利用 CDN Pro 的特殊服务组nearChina，以部署在香港的优质节点线路，底延时高性能的下发您的内容到中国大陆。
Please change "下发" to "分发"。
Did you update the English version?

2022-10-08 00:26 UTC, ronyayoung commented on zh/docs/edge-logic/faq.md
> +如果您的CDN域名没有ICP备案，但仍然需要加速并分发内容到中国大陆，CDN Pro 为您提供了Near China专线的解决方案。 这个解决方案利用 CDN Pro 的特殊服务组nearChina，以部署在香港的优质节点线路，底延时高性能的下发您的内容到中国大陆。
Ok, will change "下发" to "分发"。
Yes，I have added the English version in the pull of ronya-ngdoc-181.

2022-10-08 01:00 UTC, burtonquantil requested changes
I suggested a couple of changes.

2022-10-08 01:00 UTC, burtonquantil commented on en/docs/edge-logic/supported-directives.md
> +The configuration at the server level is inherited by a location block only when this directive is not present in the location block. If you need the directive to configure on both server level and l
The first sentence is really confusing to me.  @nibinqtl  However, I'm not sure I understand it enough to suggest a rewording yet.

I suggest the second can be improved to:
If you need to use the proxy_cache_valid directive at both the server level and in a location block, use the following example as a guide:

2022-10-18 17:42 UTC, nibinqtl commented
@ronyayoung please address Burton's suggestions.

2022-10-18 18:08 UTC, burtonquantil approved these changes
OK to merge

2022-10-18 18:22 UTC, merged