NGDOC-174 Add anycast feature to FAQ
mileweb/docs-content-cdn pull request #437
Opened 2022-11-06 14:22 UTC by Jianghai-Quantil

@nibinqtl @burtonquantil @marcfishelquantil Please help review, thanks.

2022-11-07 08:28 UTC, nibinqtl requested changes

2022-11-07 08:28 UTC, nibinqtl commented on en/docs/edge-logic/faq.md
> +However, if your domain to be accelerated is an Apex domain, i.e. a root domain (e.g. example.com) that does not contain a subdomain, adding a CNAME record to the Apex domain would become an issue, d
The purpose of our Anycast IP is to provide a highly available address for the Apex domain, and the edge logic should simply respond with a 30x redirection to the "www" domain. The Anycast IP includes only a small portion of our PoPs so the performance and capacity is not comparable to the edge hostnames. It should be used only for Apex domains.

2022-11-07 09:31 UTC, Jianghai-Quantil commented on en/docs/edge-logic/faq.md
> +However, if your domain to be accelerated is an Apex domain, i.e. a root domain (e.g. example.com) that does not contain a subdomain, adding a CNAME record to the Apex domain would become an issue, d
@nibinqtl Thanks for the comment. Just make some changes. Please review again.

2022-11-08 00:02 UTC, burtonquantil commented on en/docs/edge-logic/faq.md
> +However, if your domain to be accelerated is an Apex domain, i.e. a root domain (e.g. example.com) that does not contain a subdomain, adding a CNAME record to the Apex domain would become an issue, d
Are you referring to a particular section of the RFC 1034 ?

2022-11-08 00:38 UTC, burtonquantil requested changes
I posted questions and suggested a change to improve the grammar

2022-11-08 00:38 UTC, burtonquantil commented on en/docs/edge-logic/faq.md
> +Note that each anycast IP address is broadcast only in a small subset of our global PoPs. And the list of PoPs where anycast is available might be subject to changes without prior notice. So the perf
I'd combine the first two sentences.

Note that each anycast IP address is broadcast only in a small subset of our global PoPs, and the list of PoPs where anycast is available is subject to changes without prior notice. Therefore, the performance  and capacity behind an anycast IP address are not comparable to that of an edge  hostname.   We recommend using the CNAME-based edge hostnames to route traffic as much as possible. Anycast should be used only for Apex domains.

2022-11-08 00:38 UTC, burtonquantil commented on en/docs/edge-logic/faq.md
> +However, if your domain to be accelerated is an Apex domain, i.e. a root domain (e.g. example.com) that does not contain a subdomain, adding a CNAME record to the Apex domain would become an issue, d
Based on what I've seen on other companies' sites, I don't believe it is necessary to capitalize "apex" as "Apex".

2022-11-08 13:13 UTC, Jianghai-Quantil commented
Descriptions revised per @burtonquantil 's comments.

2022-11-08 20:32 UTC, burtonquantil requested changes
Thanks for the revisions. I made a few more suggestions.

2022-11-08 20:32 UTC, burtonquantil commented on en/docs/edge-logic/faq.md
> +Our [CNAME-based traffic management system](</docs/portal/traffic-management/overview>) is designed to make routing decisions dynamically, factoring in performance, costs, compliance requirements and
I recommend removing ", etc." because it is vague.

2022-11-08 20:32 UTC, burtonquantil commented on en/docs/edge-logic/faq.md
> +Our [CNAME-based traffic management system](</docs/portal/traffic-management/overview>) is designed to make routing decisions dynamically, factoring in performance, costs, compliance requirements and
"edgeHostname" should be "edge hostname". That is what we use in the rest of the documentation.

2022-11-08 20:32 UTC, burtonquantil commented on en/docs/edge-logic/faq.md
> +However, if your domain to be accelerated is an apex domain, i.e. a root domain (e.g. example.com) that does not contain a subdomain, adding a CNAME record to the apex domain would become an issue, d
I suggest changing "CNAME record to the apex domain" to "CNAME record for the apex domain".

2022-11-09 08:08 UTC, Jianghai-Quantil commented on en/docs/edge-logic/faq.md
> +Our [CNAME-based traffic management system](</docs/portal/traffic-management/overview>) is designed to make routing decisions dynamically, factoring in performance, costs, compliance requirements and
Removed

2022-11-09 08:08 UTC, Jianghai-Quantil commented on en/docs/edge-logic/faq.md
> +Our [CNAME-based traffic management system](</docs/portal/traffic-management/overview>) is designed to make routing decisions dynamically, factoring in performance, costs, compliance requirements and
Changed to edge hostname.

2022-11-09 08:09 UTC, Jianghai-Quantil commented on en/docs/edge-logic/faq.md
> +However, if your domain to be accelerated is an apex domain, i.e. a root domain (e.g. example.com) that does not contain a subdomain, adding a CNAME record to the apex domain would become an issue, d
Changed as suggested

2022-11-09 19:51 UTC, burtonquantil commented on en/docs/edge-logic/faq.md
> +Our [CNAME-based traffic management system](</docs/portal/traffic-management/overview>) is designed to make routing decisions dynamically, factoring in performance, costs, compliance requirements and
Minor: I prefer a comma after "requirements" before "and",  though it's technically still OK as is.

I prefer to replace "In most cases, you can leverage" with a stronger sounding  "Leverage"

2022-11-09 19:52 UTC, burtonquantil submitted a review, later dismissed
I made a couple of minor suggestions, but it is OK to merge.

2022-11-10 03:04 UTC, Jianghai-Quantil commented on en/docs/edge-logic/faq.md
> +Our [CNAME-based traffic management system](</docs/portal/traffic-management/overview>) is designed to make routing decisions dynamically, factoring in performance, costs, compliance requirements and
Suggestions accepted.

2022-11-10 03:09 UTC, burtonquantil approved these changes
OK to merge

2022-11-10 05:38 UTC, merged