added more information about DAY_PERIOD
mileweb/docs-content-cdn pull request #446
Opened 2022-11-24 15:28 UTC by nibinqtl

2022-11-25 01:40 UTC, Jianghai-Quantil commented on zh/docs/edge-logic/supported-directives.md
> +| 一日之内<br>的时间| DAY_PERIOD| ```eval_func $out DAY_PERIOD 19:00+0800 12h CN-night;```<br>如果时间在19:00+0800之后的12小时内，则返回'CN-night'，否则返回空字符串|
An ending period is missing. We'd better add this to be consistent with other paragraphs.

2022-11-25 01:41 UTC, Jianghai-Quantil commented on zh/docs/edge-logic/supported-directives.md
>  | 字符串<br>修改 | SUBSTR | ```eval_func $output SUBSTR <start> <length> $input;```<br>获取输入字符串的一个子串，长度为```<length>```，起始位置为```<start>```。```<start>```可以是一个负数，就像Javascript的[substr()](https://www.w3schools.
I suggest changing the ending period to ‘。’ to be consistent with other paragraphs.

2022-11-25 01:42 UTC, Jianghai-Quantil requested changes
There are 2 minor issues related to punctuation. The texts look good to me.

2022-11-30 02:06 UTC, nibinqtl commented on zh/docs/edge-logic/supported-directives.md
>  | 字符串<br>修改 | SUBSTR | ```eval_func $output SUBSTR <start> <length> $input;```<br>获取输入字符串的一个子串，长度为```<length>```，起始位置为```<start>```。```<start>```可以是一个负数，就像Javascript的[substr()](https://www.w3schools.
updated

2022-11-30 02:37 UTC, Jianghai-Quantil approved these changes

2022-11-30 02:38 UTC, Jianghai-Quantil commented
Changes reviewed. Look good to me now. Changes can be merged.

2022-11-30 04:07 UTC, merged