Marcdev4
mileweb/docs-content-cdn pull request #453
Opened 2022-12-09 17:38 UTC by marcfishelquantil

Burton, I fixed the issue. Please confirm that this looks good and let me know of any edits required.

2022-12-09 20:31 UTC, burtonquantil requested changes
Please review my comments.
Also, it looks like you're deleting standby_tasks.png. Is that intentional?

2022-12-09 20:31 UTC, burtonquantil commented on en/docs/manifest.json
> +          },
Please check the manifest.json.
It appears to be invalid JSON.

2022-12-09 20:31 UTC, burtonquantil commented on en/docs/portal/edge-configurations/working-with-test-suites.md
> +| Description     | Description for the test suite.                        |
Should "for" be "of"?

2022-12-09 20:31 UTC, burtonquantil commented on en/docs/portal/edge-configurations/working-with-test-suites.md
> +| Description     | Description for the test suite.                        |
Should "for" be "of"?

2022-12-09 20:31 UTC, burtonquantil commented on en/docs/portal/edge-configurations/working-with-test-suites.md
> +<p align=center><img src="/docs/resources/images/edge-configurations/create-a-test-case.png" alt="test case" width="900"></p>
I think you should use an image that shows the test case corresponding to a deployed property instead of one with an error that it is reference a property that isn't yet deployed.

2022-12-09 20:31 UTC, burtonquantil commented on en/docs/portal/edge-configurations/working-with-test-suites.md
> +| Description     | Description for the test case.                                                                  |
Should "for" be "of"?

2022-12-09 20:31 UTC, burtonquantil commented on en/docs/portal/edge-configurations/working-with-test-suites.md
> +| Expected Result | Select one or more HTTP response status codes.                                                  |
Although we allow the user to pick multiple, I think it's more typical to have just one expected code. You don't need to make any change at this point.

2022-12-09 20:31 UTC, burtonquantil commented on en/docs/portal/edge-configurations/working-with-test-suites.md
> +## Running a Test Case within a Test Suite
don't your steps here run all the test cases in the test suite not just a single test suite?
It is technically possible to open the test suite and then pick one specific test case within it to run.

2022-12-09 20:58 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/working-with-test-suites.md
> +| Description     | Description for the test suite.                        |
Good catch. Fixed.

2022-12-09 20:59 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/working-with-test-suites.md
> +| Description     | Description for the test suite.                        |
Fixed

2022-12-09 21:00 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/working-with-test-suites.md
> +| Description     | Description for the test case.                                                                  |
Fixed

2022-12-09 21:00 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/working-with-test-suites.md
> +| Expected Result | Select one or more HTTP response status codes.                                                  |
Okay

2022-12-09 22:58 UTC, marcfishelquantil commented on en/docs/portal/edge-configurations/working-with-test-suites.md
> +<p align=center><img src="/docs/resources/images/edge-configurations/create-a-test-case.png" alt="test case" width="900"></p>
Done.

2022-12-12 06:18 UTC, marcfishelquantil commented on en/docs/manifest.json
> +          },
json file has been corrected,

2022-12-12 23:17 UTC, burtonquantil requested changes
Per our Skype chat.
1) please revisit manifest.json by getting an original file and adding only the few lines that need to be added
2) remove Standby_Tasks.png  as that has nothing to do with NGDOC-199.

2022-12-14 00:22 UTC, burtonquantil approved these changes
I think you're mistakenly deleting standby_tasks.png from the zh /resources/images directory.
If it is the case, I will restore it.

2022-12-14 00:24 UTC, merged