NGDOC-201 Introduce new directives and variables
mileweb/docs-content-cdn pull request #461
Opened 2023-01-03 12:24 UTC by Jianghai-Quantil

@nibinqtl pls review

2023-01-03 22:51 UTC, burtonquantil requested changes
I recommended some changes to improve the English.
Bin needs to confirm whether these variables should all be exposed to customers and check the Chinese translations.

2023-01-03 22:51 UTC, burtonquantil commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="server_name"></span><span class="var">$server_name</span> | Name of the nginx server_name that matches an incoming request. | <span class="badge green">Yes</span> | <span class="badge gre
"nginx" should be "Nginx".
I think the text should be "Name of the Nginx server that matches an incoming request."

2023-01-03 22:51 UTC, burtonquantil commented on en/docs/edge-logic/supported-directives.md
> +Specifies if invalid range header shall be ignored. When turned on, invalid range header is ignored and 200 full content is returned to client. Otherwise, the client will receive a 416 status code.
I presume you are referring to https://www.rfc-editr.org/rfc/rfc7233#section-3.1
If so, I suggest replacing range with the capitalized  "Range"
Suggestion:

"Specifies whether to ignore an invalid Range header.  When turned on, an invalid Range header is ignored, and a 200  response with full content is returned to the client. Otherwise, the client will receive a 416 status code. "

2023-01-03 22:51 UTC, burtonquantil commented on en/docs/edge-logic/supported-directives.md
> +This directive can be used to instruct the proxy server to reorder and merge multiple byte-ranges in one request. When range_reorder is enabled, multiple ranges requested in descending order will be
change " multiple ranges that are overlapped " to "multiple ranges that overlap"
I also suggest changing "returned to client" with "returned to the client"

2023-01-03 22:51 UTC, burtonquantil commented on en/docs/edge-logic/supported-directives.md
> +The header_name must be of a value other than "etag". The value is case insensitive.
I believe "case insensitive" should be hyphenated as "case-insensitive"

2023-01-04 01:15 UTC, Jianghai-Quantil commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="server_name"></span><span class="var">$server_name</span> | Name of the nginx server_name that matches an incoming request. | <span class="badge green">Yes</span> | <span class="badge gre
The way we name variables is confusing. For example, if you look at $server_name and $server_region, you'll find that the term "server" is used to refer to nginx server_name (virtual host) in one variable and to the cache server in another variable. 
I intentionally use "nginx server_name" here, hoping that this variable won't be interpreted as representing the cache server.
Maybe we can improve it to "The Nginx server_name that matches an incoming request."

2023-01-04 01:34 UTC, Jianghai-Quantil commented on en/docs/edge-logic/supported-directives.md
> +Specifies if invalid range header shall be ignored. When turned on, invalid range header is ignored and 200 full content is returned to client. Otherwise, the client will receive a 416 status code.
Updated.

2023-01-04 01:34 UTC, Jianghai-Quantil commented on en/docs/edge-logic/supported-directives.md
> +This directive can be used to instruct the proxy server to reorder and merge multiple byte-ranges in one request. When range_reorder is enabled, multiple ranges requested in descending order will be
Updated.

2023-01-04 01:34 UTC, Jianghai-Quantil commented on en/docs/edge-logic/supported-directives.md
> +The header_name must be of a value other than "etag". The value is case insensitive.
Updated.

2023-01-04 02:17 UTC, burtonquantil commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="server_name"></span><span class="var">$server_name</span> | Name of the nginx server_name that matches an incoming request. | <span class="badge green">Yes</span> | <span class="badge gre
@Jianghai-Quantil I see.   I had made the suggestion since it is odd to have the word you're trying to explain used in the explanation.

2023-01-04 23:04 UTC, burtonquantil approved these changes
OK to merge

2023-01-11 09:46 UTC, nibinqtl approved these changes
I made some updates to [Neil-NGDOC-201](https://github.com/mileweb/docs-content-cdn/tree/Neil-NGDOC-201) about the $server_name variable.

2023-01-11 12:10 UTC, merged