NCAS-3339 Disallow origin_set_header host ...
mileweb/docs-content-cdn pull request #467
Opened 2023-01-17 10:02 UTC by nibinqtl

2023-01-17 18:25 UTC, burtonquantil requested changes
Please check my suggested changes to fix the grammar.

2023-01-17 18:25 UTC, burtonquantil commented on en/docs/edge-logic/supported-directives.md
> +2. Do not use this directive to set the `Host` header to origin, instead, use the "origins.hostHeader" field of [the property JSON](/cdn/apidocs#operation/createPropertyVersion). Otherwise you will g
1) Start a second sentence:
"Do not use this directive to set the `Host` header to origin. Instead, use the "origins.hostHeader" field... 

2) Modify the last sentence to:
Otherwise, you will get a validation error.

2023-01-21 17:30 UTC, nibinqtl commented on en/docs/edge-logic/supported-directives.md
> +2. Do not use this directive to set the `Host` header to origin, instead, use the "origins.hostHeader" field of [the property JSON](/cdn/apidocs#operation/createPropertyVersion). Otherwise you will g
updated

2023-01-21 23:04 UTC, burtonquantil approved these changes
I'd put a comma after "Otherwise". OK to merge.

2023-01-23 16:27 UTC, nibinqtl commented
> 
added the comma.

2023-01-23 17:24 UTC, burtonquantil approved these changes
OK to merge

2023-01-24 17:44 UTC, merged