NGDOC-210 Add upstream_origin_only
mileweb/docs-content-cdn pull request #480
Opened 2023-02-14 09:17 UTC by Jianghai-Quantil

@nibinqtl @burtonquantil Added a new directive upstream_origin_only. Please help review.

2023-02-14 23:21 UTC, burtonquantil requested changes
I suggest some additional detail to make it clearer to a customer the scenario when they may want to use this new directive.

2023-02-14 23:21 UTC, burtonquantil commented on en/docs/edge-logic/supported-directives.md
> +Enables or disables an origin only upstreaming. When set to on, a matching request is forwarded directly to the origin, bypassing any intermediate cache (including [origin shields](/cdn/apidocs#opera
I asked Ramprasad to clarify the functionality. Based on my understanding, I would like to modify to describe a bit more:

Enable or disable origin only upstreaming. When set to on, a matching request is forwarded directly to the origin, bypassing any intermediate cache including [origin shields](/cdn/apidocs#operation/get-cdn-shields).  For example, you may have configured your property's directConnection setting to "noDirect" to always use an intermediate cache or "auto" for us to dynamically determine the best course, by default.  The upstream_origin_only directive lets you bypass that setting and allow a subset of requests to go directly to the origin

2023-02-17 12:58 UTC, Jianghai-Quantil commented on en/docs/edge-logic/supported-directives.md
> +Enables or disables an origin only upstreaming. When set to on, a matching request is forwarded directly to the origin, bypassing any intermediate cache (including [origin shields](/cdn/apidocs#opera
Suggestion accepted.

2023-02-17 20:26 UTC, burtonquantil approved these changes
OK to merge

2023-02-18 01:26 UTC, merged