NGDOC-232 Introduce $content_code
mileweb/docs-content-cdn pull request #523
Opened 2023-08-23 16:28 UTC by Jianghai-Quantil

@nibinqtl @burtonquantil Please review. 
Although $content_code can be used in both loadBalancerLogic and edgeLogic, I delibrately do not mention its usage in edgeLogic. This is because currently no reported based on $content_code in edgeLogic are available.

2023-08-24 21:44 UTC, burtonquantil requested changes
I suggested some improvements to the English text.

2023-08-24 21:44 UTC, burtonquantil commented on en/docs/edge-logic/faq.md
> +You can assign codes on a per property basis. This is useful when you have properties that fall into several groups, and you want to be able to get reports per groups. The following shows an example
I'd replace "This is useful when you have properties that fall into several groups, and you want to be able to get reports per groups." with 
"This is useful if you have properties belonging to different groups, and you want to get reports based on the groups."

For the last sentence, how about "The following is an example where properties A and B belong to group1 while property C belongs to group2."

2023-08-24 21:44 UTC, burtonquantil commented on en/docs/edge-logic/faq.md
> +> While we encourage you to make the most out of this **content code** feature to conveniently tag your content and then identify traffic, we also have in mind the potential for abuse. Therefore, a r
"make the most out of this" could be replaced by "use this"
"and then identify traffic" seems unnecessary.

2023-08-24 21:44 UTC, burtonquantil commented on en/docs/edge-logic/faq.md
> +set $content_code group1;
Below, you say " the value assigned to the $content_code variable must be a literal string"
Wouldn't that mean the line should say

_set $content_code "group1"_

2023-08-24 21:44 UTC, burtonquantil commented on en/docs/edge-logic/faq.md
> +> While we encourage you to make the most out of this **content code** feature to conveniently tag your content and then identify traffic, we also have in mind the potential for abuse. Therefore, a r
"to set value" should be "to set a value"

2023-08-24 21:44 UTC, burtonquantil commented on en/docs/edge-logic/faq.md
> +You can use these report APIs to get reports based on content codes. For instance, if you need a time series report of traffic volume for the content which is identified by the codes "abc" and "xyz",
"in request body" should be "in the request body"

2023-08-24 21:44 UTC, burtonquantil commented on en/docs/edge-logic/faq.md
> +> As the names indicate, the APIs return layer 7 traffic only. The data returned does not include TCP/IP/MAC overheads.
I think "TCP/IP/MAC overheads"  should be "TCP, IP, and MAC overhead"

2023-08-25 15:35 UTC, Jianghai-Quantil commented on en/docs/edge-logic/faq.md
> +When utilizing the CDN Pro network to deliver a broad range of content at the edge, you probably would like to be able to identify, in one way or another, the traffic served by CDN Pro. For instance,
"in one way or another", I am trying to say customers might want to understand their traffic from different perspectives, for which $content_code could be the most flexible approach for them to do so. 
Multiple domains mean the same as multiple hostnames. I understand that users can do filtering by hostnames. As you can see, this FAQ talks about not only $content_code, but also traffic reports in general.

2023-08-25 15:42 UTC, Jianghai-Quantil commented on en/docs/edge-logic/faq.md
> +In general, the paremeters along with the options mentioned above shall already meet most of the needs. However, if you would like to take a closer look at the traffic, or if you want to tailor the r
Actually, I intend to explain how the feature is implemented to let users have a brief idea. The simplified text tells users less.

2023-08-25 15:47 UTC, Jianghai-Quantil commented on en/docs/edge-logic/faq.md
> +> While we encourage you to make the most out of this **content code** feature to conveniently tag your content and then identify traffic, we also have in mind the potential for abuse. Therefore, a r
"make the most out of this": I believe this is more inviting and is more indicative of the potentials of this feature.
"and then identify traffic": identify traffic is the very purpose. tag content is the way to achieve this purpose.

2023-08-25 20:33 UTC, marcfishelquantil commented on en/docs/edge-logic/faq.md
> +In general, the paremeters along with the options mentioned above shall already meet most of the needs. However, if you would like to take a closer look at the traffic, or if you want to tailor the r
Instead of saying "Say you want to check the breakdowns of traffic per domains," how about this: "For example, if you want to check the breakdowns of traffic per domains,"
Also, "specify" is misspelled.
In the sentence that starts "Then when CDN Pro cache", please add a comma after "Then".
In the sentence " This then enables queries of report data based on such content codes." please remove "then:.

2023-08-25 20:35 UTC, marcfishelquantil commented on en/docs/edge-logic/faq.md
> +> While we encourage you to make the most out of this **content code** feature to conveniently tag your content and then identify traffic, we also have in mind the potential for abuse. Therefore, a r
Please consider replacing "we also have in mind the potential for abuse" with "there remains the potential for abuse".
Replace "Therefore" with "For this reason".

2023-08-28 23:18 UTC, burtonquantil commented on en/docs/edge-logic/faq.md
> +In general, the parameters along with the options mentioned above can meet most requirements. However, if you would like to take a closer look at the traffic, or if you want to tailor the reports in
You did not remove the "then" from "This then enables queries of report data" as recommended by Marc.

2023-08-28 23:22 UTC, burtonquantil commented on en/docs/edge-logic/faq.md
> +> While we encourage you to make the most out of this **content code** feature to conveniently tag your content and then identify traffic, we also have in mind the potential for abuse. Therefore, a r
I agree with Marc that  "there remains the potential for abuse" sounds better than "we also have in mind the potential for abuse".

2023-08-28 23:25 UTC, burtonquantil commented on en/docs/edge-logic/faq.md
> +> As the names indicate, the APIs return layer 7 traffic only. The data returned does not include TCP, IP and MAC overheads.
add a comma after "IP"

2023-08-29 19:50 UTC, burtonquantil approved these changes
The English text looks good enough to me.
You should remind Bin to review it and check the Chinese version.

2023-08-30 07:55 UTC, nibinqtl requested changes
Made a few suggestions.
And I'm suprised that we only support it Load Balancer Logic.
We should support setting $content_code in Edge Logic, and the cache should pass it to LB, just like the custom_log_fields.

2023-08-30 07:55 UTC, nibinqtl commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="content_code"></span><span class="var">$content_code</span> code assigned to the content requested by client | <span class="badge green">Yes</span> | <span class="badge green">Yes</span>
"requested by client" is redundant. I suggest to change the sentence to: "A code assigned to content for reporting and billing purposes."

2023-08-30 07:55 UTC, nibinqtl commented on en/docs/edge-logic/faq.md
> +### How to identify traffic?
How about: "How to classify traffic in reports based on custom rules?"

2023-08-30 07:55 UTC, nibinqtl commented on zh/docs/edge-logic/faq.md
> +### 如何标记内容和识别流量？
如何在报表中对数据进行分类？

2023-08-30 07:55 UTC, nibinqtl commented on zh/docs/portal/edge-configurations/creating-property.md
> +| $content_code                | Code assigned to the content requested by client.|
A code assigned to content for reporting and billing purposes.

2023-08-30 07:55 UTC, nibinqtl commented on zh/docs/portal/edge-configurations/creating-property.md
> +| $content_code                | Code assigned to the content requested by client.|
Wait, isn't this the Chinese version? How about the English version?

2023-08-30 08:53 UTC, Jianghai-Quantil commented
> Made a few suggestions. And I'm suprised that we only support it Load Balancer Logic. We should support setting $content_code in Edge Logic, and the cache should pass it to LB, just like the custom_log_fields.

We do support setting the variable in edge logic, but it is not passed to load balancer logic. Per current implementation, $content_code set in edge logic will be available only in upstream log, and $content_code set in load balancer logic will be available only in access log.

2023-08-30 08:57 UTC, Jianghai-Quantil commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="content_code"></span><span class="var">$content_code</span> code assigned to the content requested by client | <span class="badge green">Yes</span> | <span class="badge green">Yes</span>
Accepted. I use lower case "a" and remove the period, to be consistent with the existing format for other variables.

2023-08-30 09:10 UTC, Jianghai-Quantil commented on zh/docs/portal/edge-configurations/creating-property.md
> +| $content_code                | Code assigned to the content requested by client.|
The English version is also changed. Maybe you somehow missed reviewing the file. 
And, although this is the Chinese version, I did not use Chinese text here, because the whole page is in English. The page is not yet translated to Chinese. And we have many such pages to be translated. I am aware of this issue long time ago. But I barely have time to translate the documentation (which is very time consuming).

2023-08-30 09:13 UTC, Jianghai-Quantil commented on en/docs/edge-logic/faq.md
> +### How to identify traffic?
Accepted and revision made.

2023-08-30 09:13 UTC, Jianghai-Quantil commented on en/docs/edge-logic/faq.md
> +When utilizing the CDN Pro network to deliver a broad range of content at the edge, you probably would like to be able to identify, in one way or another, the traffic served by CDN Pro. For instance,
Accepted and revision made.

2023-08-30 11:53 UTC, nibinqtl approved these changes

2023-08-30 11:53 UTC, merged

2023-08-30 16:55 UTC, nibinqtl commented
Just created [NCCS-4536](https://quantil.atlassian.net/browse/NCCS-4536)