NGDOC-240 Document writeable variables
mileweb/docs-content-cdn pull request #528
Opened 2023-09-02 06:59 UTC by nibinqtl

2023-09-02 14:57 UTC, Jianghai-Quantil requested changes
The variable $cache_misc is also writable.

2023-09-02 16:45 UTC, nibinqtl commented
> The variable $cache_misc is also writable.

Good point, just updated.

2023-09-03 01:06 UTC, burtonquantil requested changes
Looks pretty good. I made a few text suggestions.

2023-09-03 01:06 UTC, burtonquantil commented on en/docs/edge-logic/built-in-variables.md
> +The table below lists all the built-in variables supported by the CDN Pro servers. You can use them in Edge Logic or [Load Balancer Logic](lb7-es-structure). Not all variables are supported in both p
I'd write   "Most variables here are read-only. The writeable ones are indicated by <span class="badge green">R/W</span."

2023-09-03 01:06 UTC, burtonquantil commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="realtime_log_ds_factor"></span><span class="var">$realtime_log_ds_factor</span> |<span class="badge small" title="numerical value">#</span> RT log downsample factor. A value N means one l
I'd change "Users can write to this variable to ..."  to   "Users can set a value.... "

2023-09-03 01:06 UTC, burtonquantil commented on en/docs/edge-logic/supported-directives.md
> +Overrides the main "Sample Rate" specified for the [Real-Time Log](/docs/portal/edge-configurations/creating-property#real-time-log). `factor` can be an integer in [0, 65535] or a variable. A value o
What does "main" mean in this context"?    "Main" implies there is a secondary or other settings.

2023-09-03 19:08 UTC, burtonquantil requested changes
made a couple of suggestions.

2023-09-03 19:08 UTC, burtonquantil commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="realtime_log_ds_factor"></span><span class="var">$realtime_log_ds_factor</span> |<span class="badge small" title="numerical value">#</span> RT log downsample factor. A value N means one l
you should write:  "Users can set a value"

2023-09-03 19:08 UTC, burtonquantil commented on en/docs/edge-logic/supported-directives.md
> +# if origin responds with a "cachetime" header, use it to  the default
Did you accidentally delete the word 'override', or were you intending to replace it with something else?

2023-09-04 15:24 UTC, burtonquantil approved these changes
OK to merge.. I made one small suggestion.

2023-09-04 15:24 UTC, burtonquantil commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="content_code"></span><span class="var">$content_code</span> | a writable variable to [assign code to content for reporting and billing purposes](/docs/edge-logic/faq#how-to-classify-traff
"assign code"  would be better as "assign a code"

2023-09-04 17:34 UTC, nibinqtl commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="content_code"></span><span class="var">$content_code</span> | a writable variable to [assign code to content for reporting and billing purposes](/docs/edge-logic/faq#how-to-classify-traff
OK, fixed. In the future, for English grammatical problems, you can directly update the code to save some time and efforts.

2023-09-05 00:10 UTC, burtonquantil approved these changes
OK to merge

2023-09-05 03:14 UTC, nibinqtl commented
@Jianghai-Quantil , still needs your approval.

2023-09-05 03:27 UTC, Jianghai-Quantil approved these changes
OK to merge.

2023-09-05 06:21 UTC, merged