some-minor-changes
mileweb/docs-content-cdn pull request #584
Opened 2024-03-01 09:30 UTC by Jianghai-Quantil

@nibinqtl Please review.
Correct the unit for origin_fast_route
Mention unit for origin_limit_rate
Mention that $request_time is the same as $down_time

2024-03-01 18:22 UTC, burtonquantil commented on en/docs/edge-logic/built-in-variables.md
> +| <span id="download_time"></span><span class="var">$download_time</span> |<span class="badge small" title="numerical value">#</span> the time from when CDN Pro receives the client request until CDN
I cannot comment on technical correctness, but I'd suggest some minor English improvements.

the time in seconds from when CDN Pro receives the client request until CDN Pro sends the response body to the system buffer. The value should be equal to the sum of $request_end_time/$turn_around_time/$transfer_time.
Another variable, download_time_ms, shares the same meaning but is measured in milliseconds. The meaning of $download_time is the same as another variable, $request_time.

2024-03-01 18:24 UTC, burtonquantil requested changes
I suggested some corrections to the English  text

2024-03-01 18:24 UTC, burtonquantil commented on en/docs/edge-logic/supported-directives.md
> +This directive enables a fast route to be used to access the origin. It is powered by our proprietary HDT technology which provides more reliable connection with reduced latency. The traffic transfer
correction to the English of two sentences.

 The traffic transferred through this fast route may be charged **at** a higher rate than the edge traffic.  The traffic is restricted to a rate of 3 MByte/s.

2024-03-01 18:24 UTC, burtonquantil commented on en/docs/edge-logic/supported-directives.md
> +This is a wrapper of the [proxy_limit_rate](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_limit_rate) directive. It limits the speed at which the response is read from the origin ser
remove one "in" from the least phrase.

2024-03-05 09:52 UTC, Jianghai-Quantil commented
@burtonquantil Revised per your suggestions. Please review again.

2024-03-05 18:21 UTC, burtonquantil approved these changes
The English version looks fine to merge.
Thanks for the updates.

2024-03-06 12:40 UTC, merged