Create paths-to-origins.md
mileweb/docs-content-cdn pull request #585
Opened 2024-03-16 08:50 UTC by nibinqtl

A new page to introduce:
The hierachical PoP structure
Variables related to cache level
Explain the origin access preferences
The fast route to origin

2024-04-11 04:27 UTC, nibinqtl commented
@burtonquantil @marcfishelquantil @Jianghai-Quantil please review the English version.
I will work on the ZH version. And we need to update ZH text on the portal before we can make sceenshot.

2024-04-11 04:34 UTC, nibinqtl commented
Created https://quantil.atlassian.net/browse/NCP-3628 to update the ZH UI

2024-04-11 12:46 UTC, Jianghai-Quantil commented on en/docs/edge-logic/paths-to-origins.md
> +
I think we shall mention that the config of "directConnect" is respected with best effort only. In extreme cases when none of parent cache servers is accessible, edge server will retry and upstream to origin directly, even if "directConnect" is set to "noDirect". And in cases when origin is not accessible directly, edge server might retry and upstream to parent cache, even if "directConnect" is set to "alwaysDirect". The directive "upstream_origin_only" can be configured to bypass upstream to parent cache forcefully.

2024-04-11 12:50 UTC, Jianghai-Quantil commented on en/docs/edge-logic/paths-to-origins.md
> +* The "peerFailureTimeout" field can be used to specify the detailed retry and backoff policy if an instance of the origin is not accessible.
Shall we mention "proxy_next_upstream" as well?
https://docs.cdnetworks.com/en/cdn/docs/edge-logic/supported-directives#proxy_next_upstream

2024-04-11 17:26 UTC, burtonquantil requested changes
I suggested some text changes.

2024-04-11 17:26 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +CDN Pro has implemented an edge-parent structure such that when a static object is
Suggestion:  
"CDN Pro has implement an edge-parent structure in which a static object not available on an edge server will be  first looked up  in the cache of a parent server."

2024-04-11 17:26 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +If it is a hit, cache it on the edge and respond to the end user.
Suggestion: "If there is a hit, cache the object on the edge, and respond to the end user."

2024-04-11 17:26 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +To enable the parent cache for an origin, you need to configure its "directConnect" setting to "No Direct".
It may be useful to add another line to explain the benefit of using "No Direct" if possible to reduce origin traffic?

2024-04-11 17:26 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +Shield is also useful when the origin only allows a very short IP whitelist for access control.
Change "Shield" to "A shield"

2024-04-11 17:26 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +
Append the sentence  " If you require this feature, please contact our support team."
We use this sentence in https://docs.cdnetworks.com/en/cdn/apidocs#operation/get-cdn-shields

2024-04-11 17:26 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +An intermediate server may provide some routing advantage in some cases but the extra processing time usually kills it.
I suggest adding a comma after "cases".

2024-04-11 17:26 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +If it is very important to keep the origin traffic at the minimum possible level, you can enable the "shield". This feature essentially
I suggest changing "shield" to "origin shield" and "This feature" to "This advanced feature".

2024-04-11 17:26 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +If you have an origin that servers both static and dynamic content, your best choice is to configure its "directConnect" to "Auto".
Please change "servers" to "servers"

2024-04-11 17:26 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +For a property with mixed content, we highly recommend you to use this directive to specify the cacheablity of each request
minor suggestion:

Change "recommend you to use"  to "recommend that you use"

2024-04-11 17:26 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +accelerated by our highspeed data transmission (HDT) platform. This platform features our proprietary protocol based on UDP and smart routing technology to ensure
https://www.cdnetworks.com/high-speed-data-transmission/  
We refer to "High-speed Data Transmission" with the hyphenated "High-speed".
Also, I think we should use "service" instead of "platform" when referencing it.

2024-04-11 17:26 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +a stable layer-4 performance regardless of any fluctuation in the public internet.
I suggest omitting the article "a" .

2024-04-11 17:26 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +Due to the higher cost of HDT, the traffic transmitted through this channel is charged seperately from the edge delivery traffic.
I suggest adding a line here to suggesting they contact our support team if they require the origin fast route feature.

2024-04-11 17:26 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +This variable is available in the load balancer logic and it indicates if you are on an edge server (value=1) or a parent server (value=2).
Change  "logic and it indicates" to "logic and indicates"

2024-04-11 17:26 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +The main usage of it is when you have a complicated access control logic, you may want to skip it on the parent servers to save time and cost:
Suggested rewrite: "The main use of this variable is to allow you to skip complicated access control logic on the parent servers to save time and cost."

2024-04-11 17:26 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +* The "peerSelectionAlgorithm" field can be used to optimize the choice of origin servers. Use "round_robin" to balance all the server instances,
Change "to balance all" to "to balance among all"

2024-04-11 17:26 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +"sorted_list" to get the best connectivity and "consistent_hash" to maximize caching on the origin.
add a comma after "connectivity"

2024-04-11 17:37 UTC, marcfishelquantil commented on en/docs/edge-logic/paths-to-origins.md
> +Based on geography and ISP, we divide our global PoPs into a few "parent zones" with each having a group of designated parent servers.
Please allow me to offer the following rewording: Global PoPs are organized into "cache zones" based on geography and ISP, with each zone having its own group of designated parent servers.

2024-04-13 07:28 UTC, nibinqtl commented on en/docs/edge-logic/paths-to-origins.md
> +Different kinds of content have different requirements when they need to access the origin.
For dynamic content, many times we are posting to the origin. So I use "access" instead of "fetch"

2024-04-13 07:38 UTC, nibinqtl commented on en/docs/edge-logic/paths-to-origins.md
> +To enable the parent cache for an origin, you need to configure its "directConnect" setting to "No Direct".
I already mentioned the purpose of "no direct" is to enable parent cache, which can lead to reduced origin traffic. Is this not clear enough?

2024-04-13 07:58 UTC, nibinqtl commented on en/docs/edge-logic/paths-to-origins.md
> +
added this.

2024-04-13 23:18 UTC, burtonquantil requested changes
Please check my latest comments. Thanks.

2024-04-13 23:18 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +as possible off the cache without fetching from the origin.
I suggest using "from" rather than "off"

2024-04-13 23:18 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +A Shield is also useful when the origin only allows a very short IP whitelist for access control.
"Shield" should be "shield".  It's not a product name or something requiring capitalization in my opinion.

2024-04-13 23:18 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +Please note that the setting of "directConnect" is respected with best effort only. In extreme cases when none of the parent servers is available, edge server will try origin directly, even if the se
change "edge server will try origin directly"  to  "edge servers will try the origin directly"

2024-04-13 23:18 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +For a property with mixed content, we highly recommend that you use this directive to specify the cacheablity of each request
Please fix the spelling of "cacheablity " to "cacheability"

2024-04-13 23:18 UTC, burtonquantil commented on en/docs/edge-logic/paths-to-origins.md
> +* The "maxConnections" field sets the maximum number of simutaneous connections that can be made to the origin to avoid overloading.
Fix the spelling of "simutaneous" to "simultaneous"

2024-04-14 14:44 UTC, burtonquantil approved these changes
The English portion is OK

2024-04-14 17:26 UTC, merged