Mention caching POST with body in cache key
mileweb/docs-content-cdn pull request #619
Opened 2024-05-18 10:53 UTC by nibinqtl

2024-05-19 03:24 UTC, burtonquantil requested changes
I suggested a few changes to improve the text.

2024-05-19 03:24 UTC, burtonquantil commented on en/docs/edge-logic/faq.md
> +In many cases, "dynamic" does not mean the content is not cacheable. For example, end users will not experiance the difference if you cache the score of a basketball game for 1 second. If you have 10
Suggestion:
For example, end users will typically not notice if you cache the score of a basketball game for 1 second.

2024-05-19 03:24 UTC, burtonquantil commented on en/docs/recipes/api-acceleration.md
> +You can use the [proxy_cache_methods](/docs/edge-logic/supported-directives#proxy_cache_methods) directive to cache other responses. Refer to the [FAQ for an example](/docs/edge-logic/faq#how-do-i-in
Suggestion:  add the word "the" before  "request body".

In other words, change the sentence to end with
.... requests with the request body in the cache key.

2024-05-20 10:38 UTC, Jianghai-Quantil commented on zh/docs/recipes/api-acceleration.md
> +You can use the [proxy_cache_methods](/docs/edge-logic/supported-directives#proxy_cache_methods) directive to cache other responses. Refer to the [FAQ for an example](/docs/edge-logic/faq#如何将问号后参数，请求
I suggest changing the link to:
Refer to [this FAQ] (/docs/edge-logic/faq#如何将问号后参数，请求头，或者请求正文加入到缓存key中) for an example that explains how to cache `POST` requests with the request body in the cache key.

2024-05-20 10:39 UTC, Jianghai-Quantil commented on en/docs/recipes/api-acceleration.md
> +You can use the [proxy_cache_methods](/docs/edge-logic/supported-directives#proxy_cache_methods) directive to cache other responses. Refer to the [FAQ for an example](/docs/edge-logic/faq#how-do-i-in
I suggest changing the link to:
Refer to [this FAQ] (/docs/edge-logic/faq#how-do-i-include-query-parameters-request-headers-and-body-in-the-cache-key) for an example that explains how to cache `POST` requests with the request body in the cache key.

2024-05-20 10:41 UTC, Jianghai-Quantil commented on en/docs/recipes/api-acceleration.md
>  applications in the industry. By default, only responses to `GET` method are cached.
We actually cache GET and HEAD methods by default.

2024-05-20 10:43 UTC, Jianghai-Quantil commented on zh/docs/edge-logic/faq.md
> +  proxy_request_buffering on; # 必须打开此配置 proxy_request_body_in_cache_key 才能工作
I suggest changing the text to:
必须开启该配置，proxy_request_body_in_cache_key才能生效

2024-05-20 10:47 UTC, Jianghai-Quantil commented on zh/docs/edge-logic/faq.md
> +在许多情况下，“动态文件”并不意味着内容完全不可缓存。例如，如果您将篮球比赛的得分缓存 1 秒，客户端几乎体验不到任何差异。如果每秒有 10 个请求来获取分数，则可以节省 90% 的源站带宽和CDN执行损耗。需要注意的是，如果客户端收到的响应依赖请求 URL 中的参数或者请求头部值，或者请求正文的话，请确保所有相关参数都被[添加到缓存 key 中](#如何将问号后参数，请求头，或者请求正文加入到
“CDN执行损耗” 改成 “算力”？ 这里节省的算力，也是源站的，不是CDN吧？

2024-05-20 10:54 UTC, Jianghai-Quantil commented on zh/docs/edge-logic/supported-directives.md
> +第一个参数设置每个与客户端 keep-alive 连接的最长空闲时间。服务器会关闭空闲过长的连接。设置为 0 将会禁用 keep-alive 连接。第二个参数（非必填）用于设置 “Keep-Alive: timeout=time” 这个响应头里的值。这两个参数的数值可以不同，但皆不能超过300s。
I suggest changing the text to:
第一个参数用来设置CDN服务端与客户端 keep-alive 长连接的空闲超时时长。超过超时时长后，CDN服务端会断开连接。设置为 0 表示禁用 keep-alive 长连接。第二个参数（非必填）用于设置 “Keep-Alive: timeout=time” 这个响应头里的值。这两个参数的数值可以不同，但都不能超过300s。

2024-05-20 10:57 UTC, Jianghai-Quantil requested changes
Suggested some changes

2024-05-20 11:41 UTC, Jianghai-Quantil commented on zh/docs/recipes/api-acceleration.md
> +下面是本次假想任务的一些背景和需求:
I suggest changing the text to:
假设需要加速的API服务，其基本信息如下：

2024-05-20 11:55 UTC, Jianghai-Quantil commented
I pushed this commit, because I noticed that the current image file in production is broken. 
https://github.com/mileweb/docs-content-cdn/pull/619/commits/0f2d870d671c9f03d2426baa9c6ee797f3d67914

2024-05-20 17:42 UTC, nibinqtl commented on en/docs/recipes/api-acceleration.md
>  applications in the industry. By default, only responses to `GET` method are cached.
Updated

2024-05-20 17:59 UTC, nibinqtl commented on zh/docs/recipes/api-acceleration.md
> +下面是本次假想任务的一些背景和需求:
这个我更喜欢我的文风。

2024-05-20 18:22 UTC, burtonquantil approved these changes
The English updates look OK to me

2024-05-21 01:34 UTC, Jianghai-Quantil approved these changes
OK to merge.

2024-05-21 03:11 UTC, merged