Merge recent changes to production
mileweb/docs-content-cdn pull request #92
Opened 2020-08-25 09:09 UTC by nibinqtl

2020-09-03 20:59 UTC, burtonquantil requested changes
Can you double check the limit_rate_after description?

2020-09-03 20:59 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
> +**Default**: `limit_rate_after 0;` <br/>
It is inconsistent to show a default of "0" when the following text indicates the values are restricted between 1 and 8.

2020-09-03 23:43 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +**Default**: `limit_rate_after 0;` <br/>
updated with the latest default of '4m'.

2020-09-04 18:31 UTC, burtonquantil submitted a review, later dismissed
Looks good. OK to merge.

2020-09-07 22:18 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +### [`custom_log_field`](https://docs.cdnetworks.com/cdn/docs/edge-logic/supported-directives#custom_log_field)
@marcfishelquantil please remove all these self-links. You are hard coding them to cdnetworks.com.
They will be automatically generated, as you can see from https://docs.quantil.com/cdn/docs/edge-logic/supported-directives#custom_log_field

2020-09-08 17:56 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +### [`custom_log_field`](https://docs.cdnetworks.com/cdn/docs/edge-logic/supported-directives#custom_log_field)
With pleasure. Next upload will have all of these removed.

2020-09-12 09:53 UTC, nibinqtl commented on docs/edge-logic/supported-directives.md
> +### [`custom_log_field`](https://docs.cdnetworks.com/cdn/docs/edge-logic/supported-directives#custom_log_field)
@marcfishelquantil , you still haven't done so.

2020-09-13 01:05 UTC, burtonquantil submitted a review, later dismissed
Looks OK to me

2020-09-14 15:57 UTC, marcfishelquantil commented on docs/edge-logic/supported-directives.md
> +**Default**: `limit_rate_after 0;` <br/>
How about rewording the one sentence to the following, and then providing an example:

"We limit the value to an integer from [1-8] followed by ‘m’. For example:

2020-09-15 00:35 UTC, snikitin-qtl approved these changes
look good to me

2020-09-15 03:14 UTC, merged