Edits for Release21Aug2020-NGCDN1.1-SC88-1312
mileweb/docs-content-cdn pull request #93
Opened 2020-09-02 19:00 UTC by marcfishelquantil

These content edits reflect Release21Aug2020-NGCDN1.1-SC88-1312. I have captured low-res screenshots of the GUI screens that have changed. However, they are not included in this upload. Instead, I will work with Eleazar to capture high-res screenshots and upload them to GitHub when Eleazar returns from vacation next week.

2020-09-03 20:48 UTC, burtonquantil requested changes
Please check my comments.

2020-09-03 20:48 UTC, burtonquantil commented on docs/edge-logic/supported-directives.md
>  <span class="badge dark">advanced</span> <span class="badge primary">CDN360 Proprietary</span> <span class="badge yellow">ETA: Aug 2020</span>
Your file is obsolete. You still have an ETA for custom_log_field even though it was removed in production.
https://docs.cdnetworks.com/cdn/docs/edge-logic/supported-directives#custom_log_field
Please reconcile the differences. I suspect someone else already checked in some changes

2020-09-03 20:48 UTC, burtonquantil commented on docs/portal/certificates/deleting-certificate.md
> +2. Below the **Actions** column on the Certificates page, click the vertical ellipsis of the certificate you want to delete, and then select **Delete**.
Why do you use "Below the **Actions** column" ?   The ellipsis is **IN** the Actions column.

2020-09-03 23:50 UTC, marcfishelquantil commented on docs/portal/certificates/deleting-certificate.md
> +2. Below the **Actions** column on the Certificates page, click the vertical ellipsis of the certificate you want to delete, and then select **Delete**.
It's semantics. I used "below" because it is more specific than "in." In fact, the word "below" includes the meaning of "in" and adds a location to the meaning of "in" that instructs where the ellipsis button is in the column.

2020-09-04 00:47 UTC, burtonquantil commented on docs/portal/certificates/deleting-certificate.md
> +2. Below the **Actions** column on the Certificates page, click the vertical ellipsis of the certificate you want to delete, and then select **Delete**.
I think your interpretation is wrong.  Consider a spreadsheet with a column A.
If you are filling out a field at row 2 within column A, that's how you'd refer to it.  
I have never heard of anybody saying fill out row 2 **below**  column A.
That's why I'm confused.

2020-09-04 01:23 UTC, marcfishelquantil commented on docs/portal/certificates/deleting-certificate.md
> +2. Below the **Actions** column on the Certificates page, click the vertical ellipsis of the certificate you want to delete, and then select **Delete**.
Either way, I do not think users will be confused. That said, we can use "in" instead of "below" if you deem it a better term to use. In fact, the word "column" implies above and below, so we can certainly use "in." I will make this change Friday and appreciate your attention to detail.

2020-09-04 01:47 UTC, burtonquantil commented on docs/portal/certificates/deleting-certificate.md
> +2. Below the **Actions** column on the Certificates page, click the vertical ellipsis of the certificate you want to delete, and then select **Delete**.
Let's use "in" since you are simply referring to "column".
Here's a third party example.
https://support.google.com/docs/answer/3256570?hl=en  is an example of text written by Google about Google sheets.
They refer to a cell **in** a column.

If you had instead referred to the "Actions column heading", then something like 
"Click the ellipsis under the Actions column heading" or "Click the ellipsis below the Actions column heading." would be OK, but they're a bit verbose.     I believe "... in the Actions column" is a simpler and easier to translate if we ever needed to.

2020-09-04 15:23 UTC, marcfishelquantil commented on docs/portal/certificates/deleting-certificate.md
> +2. Below the **Actions** column on the Certificates page, click the vertical ellipsis of the certificate you want to delete, and then select **Delete**.
Great. I will make this fix today.

2020-09-04 18:32 UTC, burtonquantil approved these changes
OK to merge.

2020-09-04 18:38 UTC, merged